### ISSUE TITLE
[BUG] AI-Win does not clear user config on uninstall

### ISSUE THREAD

**Issue by jalkire** [microsoft/accessibility-insights-windows#1007]
**Describe the bug**
When AI-Win is uninstalled, its user configuration is not cleared. If someone opts in (or out) of telemetry, uninstalls, and then reinstalls the software, they are thus not asked to opt in to telemetry a second time.

**To Reproduce**
1. Install AI-Win
2. Opt in or out of telemetry
3. Uninstall AI-Win
4. Reinstall AI-Win
5. Launch AI-Win

**Expected behavior**
The user sees the telemetry opt-in dialog

**Actual behavior**
The user does not see the telemetry opt-in dialog (but their previous selection is respected)

**Additional context**
Reported by @LiLoDavis

**Comment by DaveTryon** [comment]
@adarshrema, retaining the settings across uninstall is both intentional and required for upgrade and channel switching scenarios. If we opt to delete the config file during uninstall, we'll need to add some code to VersionSwitcher so that it stashes the config file before uninstalling the installed version and restores it (updating the release channel if changing channels) after installing the new version (but before launching the new version)

**Comment by DaveTryon** [comment]
@adarshrema, should this be reclassified as a feature request?

**Comment by adarshrema** [comment]
Keeping this open to investigate the scope of the issue.

**Comment by ferBonnin** [comment]
@adarshrema @DaveTryon if we cannot do a clear user config on uninstall, we should document in our website how to completely delete the app and config (similar to how we do for [Accessibility Insights for Android - Uninstall](https://accessibilityinsights.io/docs/en/android/getstarted/setup/#uninstalling-accessibility-insights-for-android))

**Comment by adarshrema** [comment]
Fix to delete user config on explicit uninstall scenario and save/ restore it for upgrade and version switch scenarios.

**Comment by ferBonnin** [comment]
marking this as resolved and assigning to @LiLoDavis

**Comment by DaveTryon** [comment]
@LiLoDavis, I'll add a link once this is in the Canary pipeline

**Comment by DaveTryon** [comment]
The fix ran into issues in the signed build, so I had to back it out. Moving this back to active ☹️

**Comment by DaveTryon** [comment]
@LiLoDavis, this is fixed as of build [1.1.1489.01](https://github.com/microsoft/accessibility-insights-windows/releases/tag/v1.1.1489.01). If you install this build, then uninstall it, the config files will be deleted. If you then install it again, you'll be prompted to allow telemetry when the app boots up. The Config files are removed only on uninstall--they are preserved if you change channels or if you upgrade over an existing build.

**Comment by LiLoDavis** [comment]
It does, indeed, behave exactly as you describe. Looks good to me.

**Comment by DaveTryon** [comment]
Closing on behalf of LiLoDavis
