### ISSUE TITLE
[Feature Request] MSAA support

### ISSUE THREAD

**Issue by leonardder** [microsoft/accessibility-insights-windows#1008]
**Is your feature request related to a problem? Please describe.**
Many controls (like in Win Forms and other Win32 based apps) don't implement UIAutomation natively, but use MSAA to expose accessibility properties. Currently Accessibility Insights only presents UIA data about these controls, but as they aren't native UIA controls, it can  cause confusion for users not familiar with UIA.

**Describe the solution you'd like**
MSAA/IAccessible2 support in AI

**Comment by adarshrema** [comment]
@leonardder, thank you for your interest in Accessibility Insights and this feature request. Given that MSAA has been legacy (receives no active investment) for a while, the focus on more performant & reliable UIA, and available bridge from MSAA to UIA, we think the incremental value in this would not substantiate the effort involved.
