### ISSUE TITLE
[BUG] How to fix popup item  : The Name property of focusable element must not be null. ( windows '' issue)

### ISSUE THREAD

**Issue by meichunwu** [microsoft/accessibility-insights-windows#1087]
Please check whether the bug has [already been filed](https://github.com/Microsoft/accessibility-insights-windows/issues).

**Describe the bug**
How to fix popup item : The Name property of focusable element must not be null.  (windows '' issue )

**To Reproduce**
1. Open popup'
2. Run accessibility tool
3. Issue report The Name property of focusable element must not be null.  - windows ''

**Expected behavior**
1. AutomationProperties.Name="test" within popup
2. https://social.msdn.microsoft.com/Forums/vstudio/en-US/d4ba12c8-7a87-478e-b064-5620f929a0cf/how-to-set-automationid-and-name-for-popup?forum=wpf

**Actual behavior**
1. AutomationProperties.Name="test" not work for popup
2. Not work as well via  https://social.msdn.microsoft.com/Forums/vstudio/en-US/d4ba12c8-7a87-478e-b064-5620f929a0cf/how-to-set-automationid-and-name-for-popup?forum=wpf

**Screenshots or .GIF**
![image](https://user-images.githubusercontent.com/55374679/111864600-f26c0100-899c-11eb-8a6a-0cfffebbbd97.png)

**Desktop (please complete the following information):**
 - OS:1909
 - Accessibility Insights for Windows Version: 1.1.1467
 - Target Application: WPF application

**Comment by DaveTryon** [comment]
Hi, @meichunwu! Can you please elaborate on exactly what you mean when you say "Open popup" as the first repro step? There are lots of different ways that could be interpreted, and we want to make sure that we're looking at the same thing. Please be as specific as possible, including the app that you were using. If it's helpful, please feel free to include a GIF showing the actions.

**Comment by meichunwu** [comment]
Hi DaveTryon,

Please check my the below sample code and accessibility test result. And repo steps screenshot as below
[Popup_Forms_name_Popup_Tapstop_issue.zip](https://github.com/microsoft/accessibility-insights-windows/files/6187169/Popup_Forms_name_Popup_Tapstop_issue.zip)

[Popup accessibility result 03-23-21.zip](https://github.com/microsoft/accessibility-insights-windows/files/6187204/Popup.accessibility.result.03-23-21.zip)

![#1_Open Popup_Forms_name_Popup_Tapstop_issue exe](https://user-images.githubusercontent.com/55374679/112100119-9513c200-8bdf-11eb-8d56-c09530b1d8a6.png)

<img width="960" alt="#2_Set element count down timer" src="https://user-images.githubusercontent.com/55374679/112100140-9ba23980-8bdf-11eb-8d41-ceeacfb81e01.png">

<img width="960" alt="#3_Open popup and wait for tool" src="https://user-images.githubusercontent.com/55374679/112100150-a066ed80-8bdf-11eb-9e1a-ec5daa640ffa.png">

**Comment by DaveTryon** [comment]
Thanks, @meichunwu! I have a repro and am investigating

**Comment by DaveTryon** [comment]
Are you familiar with the old joke about a man who tells his doctor, "It hurts when I twist my head like this", and the doctor says "Don't twist your head like that" ? Well, that's sort of the answer here. The Popup class uses UIA in a very unusual way. The [reference sources](https://referencesource.microsoft.com/#PresentationFramework/src/Framework/System/Windows/Controls/Primitives/Popup.cs,3599) include a workaround to try to bridge a deficiency in the UIAutomation provider, but ultimately they don't quite succeed. We tried different ways to set the Name property, but none of them worked. In essence, the `Popup` class suffers from a significant accessibility problem.

WPF for .NET Framework is not making changes for accessibility issues. WPF for .NET Core has a stated goal of fixing accessibility issues, but that would involve reporting the issue, migrating to .NET Core, and then waiting for the change to occur--which is potentially a lot of work with no guarantee of when you would have a workable solution. That's not really a great option.

Our recommendation would be to replace the `Popup` object with either a `ContextMenu` or a full dialog, depending on the complexity of the popup (in this case a `ContextMenu` should be fine. Either of these options will allow you to easily set the various name properties, and they both provide better accessibility for keyboard-only users (for example, I could find no keyboard-only way to select any of the radio buttons in your popup). 

I'm assigning this issue back to you. Please close it out at your convenience, Thanks for using Accessibility Insights!

**Comment by meichunwu** [comment]
Use ContextMenu replace popup which could resolve keyboard focus issue, but there is name issue as well "The Name property of focusable element must not be null. ( windows '' issue)" as below

        private void PerformanceControlMode_Btn_Click(object sender, RoutedEventArgs e)
        {
            //PerformanceControlModePopup.IsOpen = true;

            e.Handled = true; //need to suppress empty menu
            FrameworkElement fe = e.Source as FrameworkElement;
            fe.ContextMenu = BuildMenu();
            fe.ContextMenu.IsOpen = true;
            fe.ContextMenu.StaysOpen = true;
            fe.ContextMenu.SetValue(System.Windows.Automation.AutomationProperties.NameProperty, "popupMenu");
            fe.SetValue(System.Windows.Automation.AutomationProperties.NameProperty, "popup");
            fe.Parent.SetValue(System.Windows.Automation.AutomationProperties.NameProperty, "popupParent");
        }
        ContextMenu BuildMenu()
        {
            ContextMenu theMenu = new ContextMenu();
            MenuItem mia = new MenuItem();
            mia.Header = "Item1";
            MenuItem mib = new MenuItem();
            mib.Header = "Item2";
            MenuItem mic = new MenuItem();
            mic.Header = "Item3";
            theMenu.Items.Add(mia);
            theMenu.Items.Add(mib);
            theMenu.Items.Add(mic);
            return theMenu;
        }

<img width="960" alt="Screenshot (6395)" src="https://user-images.githubusercontent.com/55374679/112265566-a6c39b00-8cad-11eb-8eb2-88ced87ca9d3.png">

<img width="960" alt="Screenshot (6396)" src="https://user-images.githubusercontent.com/55374679/112265584-ad521280-8cad-11eb-9459-8e6b659bc4f2.png">

**Comment by DaveTryon** [comment]
Thanks, @meichunwu! I've confirmed that you can set an automation name on a ContextMenu via XAML, but haven't yet found the code equivalent. I haven't yet found how to set an automation name on sub-menus within a ContextMenu. We'll take another look at this and try to determine the best path forward.

**Comment by DaveTryon** [comment]
@juchampa, we should triage this along with #1093, which is a spin-off of a specific ContextMenu in AIWin. I'll consult with @RobGallo before we convene for triage, just for time efficiency.

**Comment by DaveTryon** [comment]
@meichunwu, I wanted to close the loop on this. We've decided that we'll modify the rule here so there's no longer any need to set the accessible name for context menus or for popups. Please see https://github.com/microsoft/axe-windows/issues/556 for details of what we intend to do. At this point, you can just ignore these errors, as they'll go away in our next release (no firm date at this time). There's still the issue of not being able to get keyboard focus onto the popup, but the ContextMenu should handle that. I think we're done with this issue for now, so I'm assigning it back to you for closing. 

To avoid morphing the bug over time, please file a new issue if you have issues not directly related to the name errors on Popup and ContextMenu objects. Thanks!

**Comment by meichunwu** [comment]
Close by request and open new bug for contextmenu
