### ISSUE TITLE
[Feature Request] How can we test tab stops on a transient control?

### ISSUE THREAD

**Issue by meichunwu** [microsoft/accessibility-insights-windows#1088]
Please check whether the bug has [already been filed](https://github.com/Microsoft/accessibility-insights-windows/issues).

**Describe the bug**
How to test  tabstop test of accessibility on popup item

**To Reproduce**
1. Open popup
2. Run accessibility tool
3. Run tab stops test
4. The focused Pop up item will be disappeared, and tab stops test cannot be continued

**Expected behavior**
Could test  tab stops 

**Actual behavior**
Pop up item is not focusable, and tab stops test cannot be continued 

**Screenshots or .GIF**
![image](https://user-images.githubusercontent.com/55374679/111871508-6e7a3f00-89c5-11eb-9ecb-1e8dca26817e.png)

**Desktop (please complete the following information):**
1. OS:1909
2. Accessibility Insights for Windows Version: 1.1.1467
3. Target Application: WPF application

**Comment by DaveTryon** [comment]
Hi, @meichunwu! Can you please elaborate on exactly what you mean when you say "Open popup" as the first repro step? There are lots of different ways that could be interpreted, and we want to make sure that we're looking at the same thing. Please be as specific as possible, including the app that you were using. If it's helpful, please feel free to include a GIF showing the actions.

**Comment by meichunwu** [comment]
Hi DaveTryon,

Please check my the below sample code and accessibility test result. And repo steps screenshot as below
[Popup_Forms_name_Popup_Tapstop_issue.zip](https://github.com/microsoft/accessibility-insights-windows/files/6187350/Popup_Forms_name_Popup_Tapstop_issue.zip)

[Popup_TapStop 03-23-21.zip](https://github.com/microsoft/accessibility-insights-windows/files/6187347/Popup_TapStop.03-23-21.zip)

![#1_Open Popup_Forms_name_Popup_Tapstop_issue exe](https://user-images.githubusercontent.com/55374679/112102329-0d2fb700-8be3-11eb-9454-f11c3379717c.png)

<img width="960" alt="#2_Open popup and test by tool" src="https://user-images.githubusercontent.com/55374679/112102340-11f46b00-8be3-11eb-95b2-cf174a98f761.png">

![#3_tool result](https://user-images.githubusercontent.com/55374679/112102352-17ea4c00-8be3-11eb-9d18-473f8d63bdbb.png)

<img width="960" alt="#4_TabStop test" src="https://user-images.githubusercontent.com/55374679/112102368-1f115a00-8be3-11eb-9e45-10b890d8f3f0.png">

**Comment by DaveTryon** [comment]
Thanks, @meichunwu! I have a repro and am investigating

**Comment by DaveTryon** [comment]
@juchampa, we currently have no way to test tab stops on a transient control. We can trigger automated tests based on a timer, but there's no corresponding way to trigger tab stops on a timer. The workflow goes like this:

1. Use AIWin's timer to set up for automated tests (test the entire application, not just an element)
2. Before the timer counts down to 0, expose the transient control
3. Automated tests run, but the transient control disappears when the focus returns to AIWin
4. Click on tab stops
5. The transient control appears in the screen shot, but it has closed in the actual app
6. Start the tab stops test

In some cases, it _might_ be possible to re-trigger the transient control, but it's not 100% guaranteed. Fixing this would probably require that we support running tab stops without first running the automated tests, and that we provide a timer delay to start recording tab stops. I don't know if this is feasible, but I'm assigning this to for consideration as a feature request.

**Comment by meichunwu** [comment]
Use ContextMenu replace popup  as below, there is can not test TapStop problem as well 

    private void PerformanceControlMode_Btn_Click(object sender, RoutedEventArgs e)
    {
        //PerformanceControlModePopup.IsOpen = true;

        e.Handled = true; //need to suppress empty menu
        FrameworkElement fe = e.Source as FrameworkElement;
        fe.ContextMenu = BuildMenu();
        fe.ContextMenu.IsOpen = true;
        fe.ContextMenu.StaysOpen = true;
        fe.ContextMenu.SetValue(System.Windows.Automation.AutomationProperties.NameProperty, "popupMenu");
        fe.SetValue(System.Windows.Automation.AutomationProperties.NameProperty, "popup");
        fe.Parent.SetValue(System.Windows.Automation.AutomationProperties.NameProperty, "popupParent");
    }
    ContextMenu BuildMenu()
    {
        ContextMenu theMenu = new ContextMenu();
        MenuItem mia = new MenuItem();
        mia.Header = "Item1";
        MenuItem mib = new MenuItem();
        mib.Header = "Item2";
        MenuItem mic = new MenuItem();
        mic.Header = "Item3";
        theMenu.Items.Add(mia);
        theMenu.Items.Add(mib);
        theMenu.Items.Add(mic);
        return theMenu;
    }

![Screenshot (6397)](https://user-images.githubusercontent.com/55374679/112267800-f5266900-8cb0-11eb-97dd-cf9abd122947.png)

![Screenshot (6398)](https://user-images.githubusercontent.com/55374679/112267819-fbb4e080-8cb0-11eb-8e34-2c9f23635a55.png)

**Comment by RobGallo** [comment]
I'd like to understand why running tab stops is linked to running automated checks, that seems like it will influence potential solutions.

**Comment by DaveTryon** [comment]
Unfortunately, this is out of scope given our current priorities.

Thanks for using Accessibility Insights!
