### ISSUE TITLE
Add a timer to the color contrast analyzer

### ISSUE THREAD

**Issue by LiLoDavis** [microsoft/accessibility-insights-windows#1115]
**Is your feature request related to a problem? Please describe.**
To verify compliance with WCAG success criterion [1.4.11 Non-text contrast](https://w3c.github.io/wcag/understanding/non-text-contrast.html), users must check the contrast of UI components in various states, including mouse hover and focused. It's difficult to use our color contrast analyzer for these tasks because selecting the eyedropper moves focus to our tool. 

**Describe the solution you'd like**
Add a timer to the command bar in the **Color contrast analyzer**. The timer would look and behave exactly as it does in **Live inspect**, except:

- The timer text would say something like, "Enable eyedropper in [5] seconds."
- When the countdown reached zero, the snapshot would be taken and the eyedropper would be enabled.

**Describe alternatives you've considered**
The current solution is to instruct users to use a screenshot tool like Snip & Sketch, which has a built-in timer, to take a screenshot after a delay, and then to use the eyedropper to capture colors from the screenshot. It's a cumbersome process.

**Additional context**
This feature will become even more important when WCAG 2.2 guidelines are finalized. To verify conformance with [2.4.1 Focus Appearance (Minimum)](https://w3c.github.io/wcag/understanding/focus-appearance-minimum.html), users will have to verify both the contrast and area of focus indicators. Simplifying the process as much as possible will be a great help to our users.

**Comment by petewu100** [comment]
+1. This would be very helpful for hover states, focus states, light dismiss dropdowns, etc.

**Comment by DaveTryon** [comment]
Unfortunately, this is out of scope given our current priorities.

Thanks for using Accessibility Insights!
