### ISSUE TITLE
[BUG] AccessibilityInsights1.1 and inspect.exe show different BoundingRectangle for notepad.exe's MenuItemControl in DPI scale mode

### ISSUE THREAD

**Issue by yinkaisheng** [microsoft/accessibility-insights-windows#1122]
Hi
My OS is Windows 10 19042.928 Home Edition.
I have 2 1080P monitors, let me name them A and B.
The rect of A is (0,0,1920,1080) and the rect of B is (1920,0,3840,1080).
A is 100% DPI and B is 150% DPI.
I run notepad.exe, put it in screen B and set notepad window maximize.
Then I use AccessibilityInsights.exe 1.1 and inspect.exe 7.2 to get Notepad controls' BoundingRectangle.
AccessibilityInsights.exe and inspect.exe show the same BoundingRectangle for notepad's EditControl,
but different BoundingRectangle for notepad's MenuItemControl.

![uiauto-notepad](https://user-images.githubusercontent.com/5846696/117288916-9868c180-ae9e-11eb-978f-c9241c5cc164.png)

For the same MenuItemControl,
AccessibilityInsights.exe gets 2117,23,2168,42.
Inspect.exe gets 2215,34,2292,63

Note that:
1920+(2117-1920) * 1.5 = 2215.5
23 * 1.5 = 34.5
1920+(2168-1920) * 1.5 = 2292
42 * 1.5 = 63
![uiauto-notepad4](https://user-images.githubusercontent.com/5846696/117288954-a6b6dd80-ae9e-11eb-9984-1d505cfbd16d.png)

Inspect can get the correct physical BoundingRectangle for the MenuItemControl and MenuBarControl while AccessibilityInsights gets logical positions.

Why AccessibilityInsights.exe and inspect.exe behave differently only for a part of Notepad's controls?

**Expected behavior**
AccessibilityInsights should behave the same as Inspect.

**Comment by yinkaisheng** [comment]
Thanks for quick response.
I'm interested in how to fix it.
I'm using python to call UIAutomation COM API via the python module [comtypes](https://pypi.org/project/comtypes/).
My python program behaves the same as AccessibilityInsights.exe, has the same issue.
Please let me know if you know how to fix it. Thanks.

Here is the python script:
```
#!python3
# -*- coding: utf-8 -*-
import ctypes
import comtypes
import comtypes.client
from typing import Any, Callable
TreeNode = Any
EditControl = 50004
MenuBarControl = 50010
MenuControl = 50009
MenuItemControl = 50011
TypeName = {EditControl: 'EditControl', MenuBarControl: 'MenuBarControl', MenuControl: 'MenuControl', MenuItemControl: 'MenuItemControl', }


def WalkTree(top, getFirstChild: Callable[[TreeNode], TreeNode] = None, getNextSibling: Callable[[TreeNode], TreeNode] = None, includeTop: bool = False, maxDepth: int = 0xFFFFFFFF):
    if maxDepth <= 0:
        return
    depth = 0
    if includeTop:
        yield top, 0
    child = getFirstChild(top)
    childList = [child]
    while depth >= 0:  # or while childList:
        lastItem = childList[-1]
        if lastItem:
            yield lastItem, depth + 1
            child = getNextSibling(lastItem)
            childList[depth] = child
            if depth + 1 < maxDepth:
                child = getFirstChild(lastItem)
                if child:
                    depth += 1
                    childList.append(child)
        else:
            del childList[depth]
            depth -= 1


def TestNotepad():
    ctypes.windll.shcore.SetProcessDpiAwareness(2)  # per monitor
    UIAutomationCore = comtypes.client.GetModule("UIAutomationCore.dll")
    IUIAutomation = comtypes.client.CreateObject("{ff48dba4-60ef-4201-aa87-54103eef594e}", interface=UIAutomationCore.IUIAutomation)
    ViewWalker = IUIAutomation.RawViewWalker

    desktop = IUIAutomation.GetRootElement()
    notepad = None
    for ele, depth in WalkTree(desktop,
                               getFirstChild=lambda e: ViewWalker.GetFirstChildElement(e),
                               getNextSibling=lambda e: ViewWalker.GetNextSiblingElement(e),
                               maxDepth=1):
        if ele.CurrentClassName == 'Notepad':
            notepad = ele
            break
    else:
        print('Can not find Notepad, exit.')
        return
    rect = notepad.CurrentBoundingRectangle
    print(f'Name: {notepad.CurrentName}, ClassName: {notepad.CurrentClassName}, ControlType: {notepad.CurrentControlType}, LocalizedControlType: {notepad.CurrentLocalizedControlType}, BoundingRectangle: {rect.left},{rect.top},{rect.right},{rect.bottom}\n')

    for ele, depth in WalkTree(notepad,
                               getFirstChild=lambda e: ViewWalker.GetFirstChildElement(e),
                               getNextSibling=lambda e: ViewWalker.GetNextSiblingElement(e)):
        if ele.CurrentControlType in TypeName:
            rect = ele.CurrentBoundingRectangle
            print(f'{" "*depth}Name: {ele.CurrentName}, ClassName: {ele.CurrentClassName}, ControlType: {TypeName[ele.CurrentControlType]}, BoundingRectangle: {rect.left},{rect.top},{rect.right},{rect.bottom}')


TestNotepad()

```
![uiauto-notepad6](https://user-images.githubusercontent.com/5846696/117416088-9a3c8e80-af4b-11eb-9b1e-a9be7798f055.png)

**Comment by pownkel** [comment]
I was only able to repro this with the x64 version of inspect.exe. x86 inspect.exe gives results that are consistent with Accessibility Insights, which is also built for x86.

**Comment by yinkaisheng** [comment]
I didn't try x86 inspect.exe yesterday.
x86 and x64 inspect.exe also give different results on My PC.
Then I tried my python script with 64 bit Python. 
It behaves the same as x64 inspect.exe and gets the correct CurrentBoundingRectangle.
So it's not my script problem now.
![image](https://user-images.githubusercontent.com/5846696/117523533-7df02e80-afeb-11eb-9b16-a7d16cd62bf4.png)

**Comment by DaveTryon** [comment]
Hi, @yinkaisheng! We've looked at this behavior and it looks like it's a problem in the x86 implementation of UIA. As pointed out above, it works correctly in the x64 UIA implementation, but moving Accessibility Insights to Windows (and Axe.Windows, which is the core library) to x64 isn't currently on our roadmap.

The "real" fix is to communicate this issue to the Windows team so they'll correct the UIA provider that is returning the incorrect data. The fact that this error occurs in only some controls (in this case, the menu bar) might suggest that a very targeted fix could be possible once the Windows team is made aware of the problem.

If this is a blocking issue for you, you might leave your text scaling at 100%, but modify your display resolution, as shown below. You'll get more on-screen pixelation, but the numbers from UIA should be correct. 

![image](https://user-images.githubusercontent.com/45672944/118559594-00c86600-b71d-11eb-91b3-3457f4ca367b.png)

Since we don't have any immediate plans to change anything in our code at this time, we've marked this issue as resolved & are assigning it back to you for feedback. Please close it out at your convenience. Thanks!

**Comment by yinkaisheng** [comment]
OK, Thanks.
