### ISSUE TITLE
The tooltip displays previously selected item in a combo box

### ISSUE THREAD

**Issue by SergeySmirnov-Akvelon** [microsoft/accessibility-insights-windows#1123]
**Describe the bug**
We found oddities in Accessibility Insights behavior.  We have a ComboBox that contains "bbk" and "dd" items. For this case, the AI ​​works correctly and correctly highlights the selected items.
![issue-4364-expectedbehavior](https://user-images.githubusercontent.com/23376742/117785032-d96d2700-b24c-11eb-8ab7-5273abc534e9.gif)

But if I make the elements have the same number of characters ("bb" and "dd"), then the Accessibility Insights ​​​​starts to behave incorrectly.
![issue-4364-wrongbehavior](https://user-images.githubusercontent.com/23376742/117785341-28b35780-b24d-11eb-8611-284144e87368.gif)

Although in the Accessibility Insights ​​itself, it correctly indicates which element is selected now:
![image](https://user-images.githubusercontent.com/23376742/117785842-9d869180-b24d-11eb-9147-bde94cbb8ca0.png)

I have verified that this problem is reproducible for other applications as well:
**Microsoft Word**
![issue-4364-word](https://user-images.githubusercontent.com/23376742/117785884-a9725380-b24d-11eb-96ec-7a910145511a.png)

**WPF**
![issue-4364-WPF](https://user-images.githubusercontent.com/23376742/117785917-b2632500-b24d-11eb-8a36-13b92f504c9b.png)

**To Reproduce**
1. Create application with the Combobox.
2. Add the "aa" and "bb" items to ComboBox.
3. Run application and run Accessibility Insights
4.  Expand the Combobox and hover the mouse cursor over the "aa" and "bb" items

**Expected behavior**
Correct item should be displayed in ‘specific item focusable’ form

**Actual behavior**
Incorrect item is displayed in ‘specific item focusable’ form

**Desktop (please complete the following information):**
 - Microsoft Windows [Version 10.0.19041.388]
 - Accessibility Insights for Windows Version: v1.1.1562.01

**Comment by jalkire** [comment]
I was able to repro on Word.

**Comment by DaveTryon** [comment]
Here's a small sample app to demo this behavior. Note that it occurs even though all of the list items are the same length.
[ComboBoxTestSampleApp.zip](https://github.com/microsoft/accessibility-insights-windows/files/6497289/ComboBoxTestSampleApp.zip)

**Comment by karanbirsingh** [comment]
@SergeySmirnov-Akvelon Thanks for the detailed bug report. The fix has been pushed to canary. https://github.com/microsoft/accessibility-insights-windows/releases/tag/v1.1.1599.01
