### ISSUE TITLE
Application Title Bar obscures UI

### ISSUE THREAD

**Issue by Tom-Wells-NW** [microsoft/accessibility-insights-windows#1128]
The application's title bar obscures the top part of the applications main UI panel

![accessibility-insights-bug-report](https://user-images.githubusercontent.com/41094813/119195072-e225e000-ba38-11eb-9d45-d48edfcc11c1.png)

System
-----------------------------
Edition:    Windows 10 Pro
Version:    20H2
OS Build:   19042.985
Experience: Windows Feature Experience Pack 120.2212.2020.0

Resolution: 1920 x 1080 (scale 100%)

**Comment by jalkire** [comment]
Thank you for reporting this issue! To help me reproduce it on my end, are there any non-default themes or Windows settings you might be using? Does the problem occur with the app at all times for you or only in particular scenarios?
