### ISSUE TITLE
Toggle Pattern issue in all Radio buttons in Google Chrome Windows

### ISSUE THREAD

**Issue by yakkala1** [microsoft/accessibility-insights-windows#1142]
When I run tests on radio button in Chrome in Windows, I am getting an issue saying that the given ControlType must not support TogglePattern referring to an accessibility standard saying "A list of all actions that can be executed on an object shall be programmatically determinable". This is repeating for all the radio buttons in Chrome. Is the issue correct?
![image](https://user-images.githubusercontent.com/32043510/123683568-ff38a480-d869-11eb-84a7-d7d1b9f8bab0.png)

**Comment by pownkel** [comment]
@yakkala1 The results from Accessibility Insights for Windows may not be relevant for web pages or apps that use web-based frameworks. Accessibility Insights for Windows checks against accessibility rules for Windows applications, but there are different accessibility standards for web content. We recommend checking web accessibility with our [chrome extension](https://chrome.google.com/webstore/detail/accessibility-insights-fo/pbjjkligggfmakdaogkfomddhfmpjeni?hl=en) instead to get the most relevant results.

**Comment by DaveTryon** [comment]
@yakkala1, we're already removed this rule from Axe.Windows in [this PR](https://github.com/microsoft/axe-windows/issues/590), but Axe.Windows hasn't yet released (we're hoping to release it in the next day or two). Once it releases, we'll pick up the changes in Accessibility Insights for Windows and you'll be able to get this behavior in our Canary release. A Production release of Accessibility Insights for Windows should occur "soonish", although we don't have a hard release date at this time. I'll update this issue as the status evolves.
