### ISSUE TITLE
[BUG] Unhandled exception upon starting AIW

### ISSUE THREAD

**Issue by dfemec** [microsoft/accessibility-insights-windows#1191]
A similar bug has already been filed but it has been marked as resolved.

**Describe the bug**
Upon starting Accessibility Insights for Windows (AIW), an unhandled exception is generated that immediately closes the splash screen (and the application).

**To Reproduce**
1. Install application
2. Go to 'Start Menu'
3. Click on 'Accessibility Insights for Windows'

**Expected behavior**
Applications starts

**Actual behavior**
Splash screen appears and then disappears

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2 (OS Build 19042.1165)
 - Accessibility Insights for Windows Version: 1.1.1689.1

**Additional context**
Priority requested - Critical
Content from Event Log:  First Entry:

Application: accessibilityinsights.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Net.WebException
   at System.Net.HttpWebRequest.EndGetResponse(System.IAsyncResult)
   at System.Net.WebClient.GetWebResponse(System.Net.WebRequest, System.IAsyncResult)
   at System.Net.WebClient.DownloadBitsResponseCallback(System.IAsyncResult)

Exception Info: System.Reflection.TargetInvocationException
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at AccessibilityInsights.SetupLibrary.REST.GitHubClient.DownloadCompleted(System.Object, System.Net.DownloadDataCompletedEventArgs)
   at System.Net.WebClient.OnDownloadDataCompleted(System.Net.DownloadDataCompletedEventArgs)
   at System.Net.WebClient.DownloadDataOperationCompleted(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

Second Entry:

Faulting application name: accessibilityinsights.exe, version: 1.1.1689.1, time stamp: 0x8b1972cf
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1151, time stamp: 0x5da51925
Exception code: 0xe0434352
Fault offset: 0x0012b512
Faulting process id: 0x5ffc
Faulting application start time: 0x01d7a5b67351aa45
Faulting application path: c:\program files (x86)\accessibilityinsights\1.1\accessibilityinsights.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 9f855728-6a87-4209-96ab-0745f8c3dea0
Faulting package full name: 
Faulting package-relative application ID:

**Comment by JGibson2019** [comment]
Using Windows 10 (version 10.0.19043) and a fresh install of Accessibility Insights for Windows (version 1.1.1689.1), this issue does not repro

**Comment by JGibson2019** [comment]
There might be an issue with updates. We'll work on addressing this. Thanks for bringing it to our attention.

**Comment by JGibson2019** [comment]
@dfemec Could you first open https://github.com/microsoft/accessibility-insights-windows/blob/Control/Channels/Production/release_info.json in the browser then try starting the app? We're trying to see if there's an auth issue that could be interfering during the update check and causing the application to crash. 

If this works, you'll at least be unblocked while we work on a fix. If not, please share what happens so we can have more information as we continue working on this. Thanks in advance!

**Comment by dfemec** [comment]
I literally just opened the link you provided, but I'm thinking I need to put the content -- release_info.json -- somewhere.  When I start the app, the same thing happens.

**Comment by JGibson2019** [comment]
Ok. Thanks for sharing this; we will continue looking into this and will update the issue when we have a fix.

**Comment by DaveTryon** [comment]
It looks like this is just a missing exception handler--should be an easy fix.

**Comment by DaveTryon** [comment]
@dfemec, we've added a change that should fix this, although it's hard to know for sure since we were never able to reproduce it on our end. Will you please do the following:

1. Uninstall AIWin via Control panel
2. Install the latest release from https://github.com/microsoft/accessibility-insights-windows/releases/tag/v1.1.1718.01
3. Run the app and see if it crashes on startup

If it solves your problem, please close this issue out and we'll figure out an appropriate time to release this fix with other changes that are in the works. Thanks!

**Comment by dfemec** [comment]
Problem resolved!  Thanks!
