### ISSUE TITLE
[BUG] The Name property must not contain only space characters when <span><a> is used.

### ISSUE THREAD

**Issue by PatrickTseng** [microsoft/accessibility-insights-windows#1193]
**Describe the bug**

**To Reproduce**
I have a HTML snippet which looks like the attached 
![image](https://user-images.githubusercontent.com/5447677/133144114-b8161dac-7dc6-49e4-bd7d-bb55ae09f63a.png)
You can quickly try out using w3schools website and  try out the snippet at the left side.  Run AIW on the right pane and you will see this error report. 

**Expected behavior**
There's no space in the HTML and I don't know AIW starts reporting this issue. 

**Actual behavior**
See repro and the output image in 'To reproduce' section. 

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1809] (Get the version by running `winver` from the command line)
 - Accessibility Insights for Windows Version: https://github.com/microsoft/accessibility-insights-windows/releases/tag/v1.1.1689.01

**Comment by ThanyaLeif** [comment]
We have an FAQ about using Accessibility Insights for Windows with Chromium or Electron apps in our site as well as this great text from the C+AI Accessibility team: “How UI gets represented through UIA can be very different for web UI and Windows desktop app UI, (and even that can be quite different depending on whether the UI is Win32, WinForms, WPF, or UWP XAML). So the AIWeb and AIWin tests have been tuned to account for where the UI’s coming from. If an AIWin FastPass is run on web UI, it may call out many failures that a web UI dev can’t do anything about.”

In general, Web apps, websites and Web based frameworks should be tested against Web rules and standards and as such we do not recommend using Accessibility Insights for Windows against these products.
