### ISSUE TITLE
[General Question]  Why this not works in Windows server 2019?

### ISSUE THREAD

**Issue by Mteheran** [Microsoft/accessibility-insights-windows#1216]
I am using Accessibility insights over a Windows Application that has a web browser embedded   

This is how Accessibility insights works in my local machine where I am using Windows 10 with default configuration: 
![Img1](https://user-images.githubusercontent.com/3578356/137029127-855418bb-3673-4361-a09d-280feb0ab248.jpg)
As you can see this is working fine and it can detect each element even those coming from a web page that is rendering in this window. 

But when I tried to do the same in Windows server 2019 (Virtual machine) I am just getting the document but I cannot get the context of each element
![image2png](https://user-images.githubusercontent.com/3578356/137032802-d0636a54-4eff-4780-b942-ce154d7151fe.png)

This is also a problem for my automation test, I am using selenium and WebDriver the test is failing because cannot find the elements. 

Is there something in the settings that I need to change or update to fix this? 
Is Windows server a problem? Do I need to use Windows 10? 

Thanks!! I hope someone here can help with this. This is my current blocker.

**Comment by Mteheran** [comment]
Yes!! Unfortunately I am not sure the technology used for this application but I think it is WPF
The version is:
Microsoft Windows Server
Version 1809 (OS build 17763.2183)
2018

**Comment by jalkire** [comment]
Thanks for checking the FrameworkId! That confirms the source of the different behavior that you're seeing.

With regard to the upgrade question, our expertise is focused on the accessibility behavior of Windows as it relates to Accessibility Insights--you're probably better off referring to the [Windows Server documentation](https://docs.microsoft.com/en-us/windows-server/) and [Microsoft Product Lifecycle information](https://docs.microsoft.com/en-us/lifecycle/products/?terms=windows%20server) to find details about Windows Server's upgrade policies and lifecycle support.
