### ISSUE TITLE
[BUG] Canary only updates to the latest prod release

### ISSUE THREAD

**Issue by jalkire** [microsoft/accessibility-insights-windows#1226]
**Describe the bug**
Our canary update mechanism attempts to update to the latest prod (not canary) release. This only impacts the autoupdater on launch--when you switch channels, ai-win updates to the correct latest version for your selected channel. 

**To Reproduce**
1. Install the latest prod version of ai-win (currently 1741.1)
2. Modify its config file (`<user dir>\AppData\Local\AccessibilityInsights\V1\Configurations\Configuration.json`) to contain `"ReleaseChannel": "Canary"`
3. Launch ai-win
4. Observe that it does not attempt to update despite the several canary releases since prod

**Expected behavior**
You should receive an update prompt on launch to update to the [latest canary release](https://github.com/microsoft/accessibility-insights-windows/releases)

**Actual behavior**
No update is prompted or occurs

**Additional context**
- From the [signed build pipeline](https://dev.azure.com/mseng/1ES/_build?definitionId=8122&_a=summary), I downloaded old releases and followed the above repro steps with them. I found that starting with 1733.1 ([build](https://dev.azure.com/mseng/1ES/_build/results?buildId=16093849&view=results)), ai-win updates to the latest prod release only, not to the latest canary
- This does not impact prod channel updates
- @DaveTryon noticed this issue due to some weirdness in our telemetry data

**Comment by DaveTryon** [comment]
Fiddler shows that the signed Canary build is always requesting the Production data. Curiously, it requests Canary data if run under the debugger. Bottom line, though, is that it shouldn't impact any production customers.

**Comment by DaveTryon** [comment]
@jalkire, this is fixed in the release at https://github.com/microsoft/accessibility-insights-windows/releases/tag/v1.1.1767.01. If you'll install it and set your ReleaseChannel to Canary, it will auto-upgrade to the next Canary build when it comes out. I just queued a build that will become 1.1.1767.02 so we'll have a target for upgrading.

**Comment by jalkire** [comment]
1.1.1767.1 successfully updated to 1.1.1767.2 👍
