### ISSUE TITLE
Creation of an universal style for GridViewColumnHeader elements in AI-Win

### ISSUE THREAD

**Issue by ThanyaLeif** [microsoft/accessibility-insights-windows#1243]
**Is your feature request related to a problem? Please describe.**

As mentioned in PR #1242, the following issues were discovered after investigations for bug #845:

- The current implementation of the GridViewColumnHeader (GVCH) does not allow customizing the background properties, which means that color changes are not reflected in the element.

- There is no consistent style for the GVCH element throughout the project, each GVCH uses a different style, despite the fact that some of the instances within the project are planned to have similar behaviors, such is the case of the "Recorded table order results "from the `TabStopControl.xaml` file (lines 79 - 82) and the "Test results" table from the `ScannerResultControl.xaml` file (lines 84 - 146) which are planned to work almost identically.
- GVCH columns can be swapped, but this is not the expected behavior.

Everything mentioned is a problem because:

- Currently the background of the GVCH element (`ScannerResultControl.xaml` lines 84 - 146) does not match the rest of the application, the default color is very bright and goes against the objectives of dark mode.

- It is not possible to resize the columns of the GridView element (`TabStopControl.xaml` file lines 79 - 82), making the user not able to see all the information related to the problem, unless the full screen is resized.

- It is possible to reorder the columns in both items mentioned above, which is not an expected behavior as it does not add value to the application and it is not an accessible action for screen reader users.

**Describe the solution you'd like**
The use of a unique GVCH style throughout the project that meets the following characteristics:

- Allow the user to resize the columns so that they can view the complete information without resizing the application window.
- Have a UI that matches the rest of the application:

    - Similar to the appearance of the GVCH element in (`TabStopControl.xaml` file lines 79 - 82).

    - That has an onMouseOver event that changes the background color, since we want the user to know that it is possible to perform an action on the element (resize the columns in this case).
- Do not allow column swapping.
- Keep the accessibility properties of the GVCH elements mentioned above (focus, visibility, etc)

**Describe alternatives you've considered**
The creation of a new style that can be used by the GVCH elements mentioned above (and any GVCH elements that will be added to the project in the future), which meets the characteristics mentioned in the previous point

**Additional context**
More information on the expected behavior and solutions given to this problem in the past can be found in bug #845  and PR #1242

**Comment by DaveTryon** [comment]
We will live with this one as is
