### ISSUE TITLE
[BUG] Color contrast needs to be detected and measured automatically

### ISSUE THREAD

**Issue by fruiti** [microsoft/accessibility-insights-windows#1244]
**Describe the bug**
When running color contrast with the application named Dell CinemaColor, some UI elements can not be detected and measured automatically.

**To Reproduce**
1. Download Dell CinemaColor from Microsoft Store: https://www.microsoft.com/en-us/p/dell-cinemacolor/9nrbz5zfdv61?rtc=1&activetab=pivot:overviewtab
2. Launch the application
3. Launch Accessibility Insight and open color contrast
4. Refer to the actual screenshots below

**Expected behavior**
All UI elements can be detected and measured automatically.

**Actual behavior**
When hovering on some elements, the tool reports 'Unable to detect colors'.

**Screenshots or .GIF**
![image](https://user-images.githubusercontent.com/555605/141435297-ce3ba8df-4e0e-4855-9f2a-fcd6728eda11.png)
![image](https://user-images.githubusercontent.com/555605/141435429-489e3461-bc67-4a1c-bfd9-aa897857ee15.png)

**Desktop:**
 - OS: Windows 11 Build 22471
 - Accessibility Insights for Windows Version: 1.1.1741.01
 - Target Application: Dell CinemaColor
 - Target Application Version: 2.3.57

**Comment by DaveTryon** [comment]
Thanks for the suggestion, @fruiti. Unfortunately, UIA provides no way for us to directly get the colors of an element, so our automatic color detection is a "best effort" based on an [algorithm](https://github.com/microsoft/axe-windows/blob/main/src/Desktop/ColorContrastAnalyzer/ColorContrastRunner.cs) that is tuned for determining color using a reasonably long string of text on a single-color background. Outside of that relatively narrow scope, it simply gives up.

For the contrast slider, the algorithm finds no text at all. For the menu button, the text is probably long enough, but the gradient fill of the background will interfere the algorithm from finding a match.

Fortunately, you can still use the contrast tool via [manual color selection](https://accessibilityinsights.io/docs/en/windows/getstarted/colorcontrast/#manually-check-contrast-ratio). I did this and was able to determine that the contrast ratio for the menu button is about 2.87:1, while the contrast ratio for the thumb of the slider is about 1.994:1. Neither of these will satisfy the contrast ratio requirements.

Please feel free to add comments in #996, which is our feature request to improve the algorithm, but for the time being, this is a known limitation of the color contrast detection algorithm. Please close this issue out at your convenience. Thanks!

**Comment by fruiti** [comment]
@DaveTryon  Well noted, thank you for the clarification.
