### ISSUE TITLE
Getting the error "an element's isOffscreen property must be false when it's clickable point is on screen" for hidden controls

### ISSUE THREAD

**Issue by AngshumanChatterjee** [microsoft/accessibility-insights-windows#1246]
**Description**
I have a WPF application, that has two states - expanded and collapsed. A few buttons are expanded in expanded state, and hidden in collapsed state. When the application is shown in collapsed state, I get the error "an element's isOffscreen property must be false when it's clickable point is on screen" for the hidden button.

**To Reproduce**
1. Open the application (refer expanded application image)
2. Put the application in collapsed state (refer collapsed application image)
3. Open Accessibility insight tool. Select "Entire app" and test
4. See errors for all the buttons (refer error image)

**Expected behavior**
There should not be any error

**Actual behavior**
Got errors for all the buttons

**Screenshots or .GIF**

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1 build 19043.1348.
 - Accessibility Insights for Windows Version: 1.1.1741.1

Collapsed:
<img width="209" alt="application collapsed" src="https://user-images.githubusercontent.com/26053642/141988520-272b7ea3-b55c-4ad4-9f4f-c4ac11b1bf6f.png">

Expanded:
<img width="365" alt="application expanded" src="https://user-images.githubusercontent.com/26053642/141988525-c6190016-bb67-438d-830b-6ca99b2dfe0f.png">

Error:
<img width="960" alt="error" src="https://user-images.githubusercontent.com/26053642/141988529-ebdb0cc8-f1f3-462a-af96-2f4f22b05284.png">

**Comment by brocktaylor7** [comment]
Hello! Thanks for reaching out. In order for us to investigate this issue we need some way to replicate it. Can you provide a sample app that shows the behavior as well as the a11ytest file if you captured it? This will allow us to investigate what may be happening in this scenario. Thanks!

**Comment by AngshumanChatterjee** [comment]
Hi, Please let me know how I can share the test file. 
Thanks!

**Comment by brocktaylor7** [comment]
Hello, you can attach a test file to the comment. If the file type is not compatible you may need to zip the file first. Here is some additional info on how to share the file: 
https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/attaching-files

There is a good chance that an example app will be very helpful in this case as well, so that we can replicate the issue and debug it properly on our end.
Thanks!
