### ISSUE TITLE
Getting the error "an element's isOffscreen property must be false when it's clickable point is on screen" for hidden controls

### ISSUE THREAD

**Issue by AngshumanChatterjee** [microsoft/accessibility-insights-windows#1272]
**Description**
I have a WPF application, that has two states - expanded and collapsed. A few buttons are expanded in expanded state, and hidden in collapsed state. When the application is shown in collapsed state, I get the error "an element's isOffscreen property must be false when it's clickable point is on screen" for the hidden button.
Please refer the test result attached: [TestResults 11-16-21.zip](https://github.com/microsoft/accessibility-insights-windows/files/7660782/TestResults.11-16-21.zip)

Collapsed state:
<img width="209" alt="141988520-272b7ea3-b55c-4ad4-9f4f-c4ac11b1bf6f" src="https://user-images.githubusercontent.com/26053642/144849788-cdd5d623-3fe2-4b37-80f5-1a82a7a554cc.png">

Expanded state:
<img width="365" alt="141988525-c6190016-bb67-438d-830b-6ca99b2dfe0f" src="https://user-images.githubusercontent.com/26053642/144849735-669098f7-695e-4213-80b0-d0370f0cd9b9.png">

Test result:
<img width="960" alt="141988529-ebdb0cc8-f1f3-462a-af96-2f4f22b05284" src="https://user-images.githubusercontent.com/26053642/144849729-048f30f6-92ed-48aa-adcd-c9c98aaeb5da.png">

**To Reproduce**
Open the application (refer expanded application image)
Put the application in collapsed state (refer collapsed application image)
Open Accessibility insight tool. Select "Entire app" and test
See errors for all the buttons (refer error image)

**Expected behavior**
There should not be any error related of isOffScreen property

**Actual behavior**
Get errors for all the buttons

**Screenshots or .GIF**
I have shared the contracted and expanded states

**Desktop:**
OS: Windows 10 21H1 build 19043.1348.
Accessibility Insights for Windows Version: 1.1.1741.1

**Comment by ThanyaLeif** [comment]
@AngshumanChatterjee 

Thanks for filling this issue.
Right now we don't have enough information to reproduce the error and came to a conclusion. 
Could you share some code or a smaller app with the same issue to take further investigation?
