### ISSUE TITLE
[Feature Request] Create a Means to Disable Auto-Update

### ISSUE THREAD

**Issue by aaronr8684** [microsoft/accessibility-insights-windows#1277]
**Describe the solution you'd like**
Similar to issue [#1182](https://github.com/microsoft/accessibility-insights-windows/issues/1182), it would be nice to have a way to disable the auto-update check at program launch. This could be via a flag during the install process or a REG key added post-install.

**Describe alternatives you've considered**
The work-around that I've found is to rename the "VersionSwitcher/AccessibilityInsights.VersionSwitcher.exe" causing the "Now" button to error out (not desired) or, more ideally, to rename the "AccessibilityInsights.Extensions.GitHubAutoUpdate.dll" file causing the prompt to fail silently and not appear. I have not discovered any side-effects introduced by the latter method, but an official method for disabling the check would be preferred. 

**Additional context**
In an enterprise environment with automated deployments, auto-update checks and user initiated installs can cause scripts to fail or vulnerabilities and bugs to be introduced into the environment by the end users.

**Comment by DaveTryon** [comment]
@asksep, we ought to discuss this scenario and decide what, if anything, we should do to support this scenario

**Comment by jalkire** [comment]
Hello @aaronr8684! Thanks for submitting this feature request. If you don't mind, we have a couple of questions to better understand the problem you're looking to solve with regard to auto updates.

- Does your concern relate to the flow of the update process itself, especially the need for UAC/admin approval? Would a more seamless update experience help?
- Does the issue relate entirely to the risks of being required to install the latest updates without having time to validate their functionality and security? If that's the case, would the ability to postpone updates for a certain amount of time, for example 2 weeks from their release, solve your issue? 
- Or is the inclusion of any kind of auto update functionality untenable for your use case? If so, would only the option to completely disable updates address your concern?

**Comment by aaronr8684** [comment]
Thanks for the follow up @jalkire 

The third option. Within our org, we consider it best practice to not have the end-users update the tools and software they use to prevent unknown software (and versions) from being installed. In the past, prompts like this have caused software breaking incompatibilities between tools and increased support workload because the software/version was never tested in our environment.

I understand that the chances of this software breaking something else in our environment is low because of the minimal coupling of this software from the other tools. However, for this software in particular, the update does break the uninstall script we use with our particular scripting suite. This isn't the only reason we don't want the auto-update feature, but just an example of the negative risks associated with auto-updates.

Like I said in the initial feature request, we found a work-around that works for us,  but an official and more graceful approach would be preferred. 

Does that help?

**Comment by jalkire** [comment]
Hi @aaronr8684, thank you for those additional details—they helped us better understand the desired behavior. Unfortunately, we don't have any current plans to add official support for disabling auto update functionality.
