### ISSUE TITLE
[BUG] Issue Filing is unable to populate process name if target app has been closed already

### ISSUE THREAD

**Issue by karanbirsingh** [microsoft/accessibility-insights-windows#1315]
**Describe the bug**

If the target application is closed when someone tries to file an issue, the resulting issue has an empty App name.

We get the process name from issue reporting [here](https://github.com/microsoft/accessibility-insights-windows/blob/7fe2f8049d8e59aad4c99896e3fb10d1ded2a18d/src/AccessibilityInsights.SharedUx/ViewModels/RuleResultViewModel.cs#L186). But it may be because we don't cache the process name at construction time like we cache UIA properties. [This code](https://github.com/microsoft/axe-windows/blob/395d97cb0136d77580d0f1ca6281fe82bfd0c092/src/Core/Bases/A11yElement.cs#L473) looks up the name the first time it is queried, and caches it afterwards. It might be possible that in this scenario the property has not been accessed yet until issue filing, after the app has closed.

**To Reproduce**
1. Scan any target app using AI-Windows
2. Set up issue filing
3. Close the target application
4. Try filing an issue to GitHub
5. Look at the app name - it is empty

**Expected behavior**
The app name should be populated.

**Actual behavior**
The app name is empty.

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2, 19044.1645
 - Accessibility Insights for Windows Version: Canary 4/15
 - Target Application: Wildlife Manager

**Comment by DaveTryon** [comment]
A related scenario:
1. User saves an a11ytest file
2. That file gets opened at some later time, possibly on a different machine
3. Another process on the machine happens to have the same processId that is stored in the a11ytest file
4. User files an issue using ADO
5. The processId from the a11ytest file is matched against the current processID and the wrong name gets used in the ADO bug.

**Comment by DaveTryon** [comment]
A full fix to this would probably involve grabbing the process name (which could be multiple processes if we're dealing with cross-process window hosting) inside axe.windows, storing that data in the a11ytest file, then using that as a reference when opening the a11ytest file. A fair amount of work for a relatively small payoff, so we want to only do this if there's some evidence of community interest.

**Comment by DaveTryon** [comment]
Unfortunately, this is out of scope given our current priorities.

Thanks for using Accessibility Insights!
