### ISSUE TITLE
[Feature Request] Navigate the siblings in the UIA tree

### ISSUE THREAD

**Issue by spudthebud** [microsoft/accessibility-insights-windows#1320]
### Problem

When using Accessibility Insights for Windows it is fully impossible to explore the UIA tree for an application.  While it is easy to navigate up an element's  ancestry of parents, we can't go to a sibling of the parent groups.  For example, when examining Word, we may be in a control type that is contained by the high-level pane "MsoDockLeft". But what if we asked: "What are the siblings to MsoDockLeft?"   We can't answer that question easily with Accessibility Insight because currently, Accessibility For Insights only allows for exploring the parental ancestors of a control type.

### Solution

When in the tree view pane for Accessibility Insights and the user has selected a control type in a application being studied, the user can use the up/down/left/right keys (or mouse) to navigate the full UIA tree, including the siblings of the parental ancestors.  This behavior was supported by Inspect.

**Comment by karanbirsingh** [comment]
Hi @spudthebud, thanks for filing the issue! Two things come to mind & I'd love your help clarifying how they relate to this request.

The tool includes some keyboard shortcuts for moving Inspect focus to various elements (parent, sibling, child) in the tree:

![keyboard shortcuts](https://user-images.githubusercontent.com/7775527/164771731-5a5f4f5d-a941-47a4-b55c-837a1ea98c02.png)

One way to get to an ancestor's sibling is by (either via mouse or keyboard shortcuts) first navigating to the parent and then its sibling. How does this compare to the behavior you have in mind? Does this address the same goal, and is the request to make this process easier? e.g. by visually showing you the parent's siblings before changing focus & allowing you move there in one action?

This feature request also reminds me of https://github.com/microsoft/accessibility-insights-windows/issues/333 - a request to expand the UIA tree fully for descendants. There is some discussion in the comments about related requests; please let me know if anything there aligns with the ask.

Please let me know if I've misinterpreted the feature request so we can make sure I'm understanding correctly. Thank you!

**Comment by spudthebud** [comment]
Navigating a tree view with triple chorded keystrokes is really awkward and requires extra cognitive load to remember the keys, so I'd like to suggest that's not really a usable option.  Arrow keys are faster and more effective. I can climb the tree but there doesn't appear anyway to explore down the tree.  This sounds like #333 

Second, a problem is that the visual interface of the tree view only shows the single ancestry branch: from selected item to the root. Inspect is better by showing all the branches from Desktop pane.

**Comment by DaveTryon** [comment]
Hi, @spudthebud! We triaged this today and feel that the overlap with #333 is large enough that we don't want to close this one out and just keep #333. In the spirit of transparency, we hope to be able to investigate options relating to #333 in the not-too-distant future, then we'll see where those options lead us.

Please take a moment to add any appropriate comments to #333, then close this. Thanks!

**Comment by spudthebud** [comment]
#333 is quite lengthy.  Here are the two tests I have for keeping this issue open.  Which ones do #333 resolve?

**Test 1.** If users can only view a single branch (desktop to focus) and not parallel siblings branches (as is possible with inspect), then there is a problem. Keep this issue open (e.g.,

If this is the only view available, then there is a problem
- Desktop
--  App 2
---- Pane 1
------ Container 2
--------- Button 1 [This is where the focus is]

If this is the view is supported, then there is not a problem. 
- Desktop
--  App 1
---- Pane 1
------ Container 1
---- Pane 2
--  App 2
---- Pane 1
------ Container 1
------ Container 2
--------- Button 1 [This is where the focus is]
---- Pane 2
--  App 3
---- Pane 1


**Test 2:** If the user can NOT navigate through the tree view using only up/down/left/right arrow keys, then there is a problem. Keep this issue open.

**Comment by RobGallo** [comment]
@spudthebud 
The arrow keys in the tree control will always remain available as they would for any accessible tree control.
It seems like you're request is a suggestion of how to resolve #333: Display the UIA tree in its entirety, no?
In that case, we're asking that you add feedback to that issue and close this one. That way, all the voices can be represented in one thread.
