### ISSUE TITLE
Suggestion: Add a rule to warn if items in a listbox have duplicated names

### ISSUE THREAD

**Issue by DaveTryon** [Microsoft/accessibility-insights-windows#133]
In its current form, AccessibiltyInsights for Windows raises no warning or error if items in a listbox all have the same name. This is a case that can make it more difficult to know the contents of the items.

Suggestion: Create a rule that runs on listboxes and checks for duplicated names between the list items. There are legitimate cases (such as pictures as the list items) that may limit this rule to generating only warnings, no errors.

**Comment by neocln** [comment]
@DaveTryon could you regress and close it?

**Comment by DaveTryon** [comment]
Confirmed fixed in daily build 1.1.814.2
