### ISSUE TITLE
[BUG] Can not check MenuItem Info

### ISSUE THREAD

**Issue by fangguoneng** [microsoft/accessibility-insights-windows#1332]
**Describe the bug**
Can not check MenuItem Info.

**To Reproduce**
1. Run accessibility tool
2. Move mouse cursor over the MenuItem

**Expected behavior**
Display info of MenuItem in [DETAILS].

**Actual behavior**
Display info of Menu in [DETAILS].

**Screenshots or .GIF**
![image](https://user-images.githubusercontent.com/40819365/167365999-5c0d77f5-9516-400e-b3e0-34433376eb6e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - Accessibility Insights for Windows Version: 1.1.1934.1
 - Target Application: Winfrom

**Comment by DaveTryon** [comment]
Hello, @fangguoneng! Based on your screenshot, you appear to be inspecting in Raw mode (selectable from the gear icon just to the right of the search bar). I tried to repro your issue on a simple test app ([WinFormsMenuDemo.zip](https://github.com/microsoft/accessibility-insights-windows/files/8655971/WinFormsMenuDemo.zip)) and inspecting menu items seems to work as expected. Here's a screenshot of what I'm seeing as I mover over the menu items--for clarity I've changed the settings to show just the highlight without the beaker or the tooltip, but it works the same if they're enabled:

![image](https://user-images.githubusercontent.com/45672944/167515378-f5e16273-8c24-4fab-994b-4102c0beed20.png)

I'm stumped about why you're seeing different results, but I'm happy to look at your sample app if you can post the source code (or even just the XAML) online. Thanks!

**Comment by fangguoneng** [comment]
@DaveTryon 
Hello! Thank you for your reply.
Please use it[WindowsFormsApp1.zip](https://github.com/microsoft/accessibility-insights-windows/files/8656354/WindowsFormsApp1.zip) to repro this issue.

**Comment by DaveTryon** [comment]
@fangguoneng, I've had the chance to dig into this a bit more, and this is a bug in .NET Framework. Your test app was built using .NET Framework, where mine was built using .NET Core. I've tweaked my demo app ([WinFormsMenuDemoInteration2.zip](https://github.com/microsoft/accessibility-insights-windows/files/8689897/WinFormsMenuDemoInteration2.zip)) so the framework can be targeted by a single line in the csproj file:

```
<!-- Pick your framework. .NET Core works, .NET Framework fails
    <TargetFramework>net48</TargetFramework>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <TargetFramework>netcoreapp3.1</TargetFramework>
-->
    <TargetFramework>net48</TargetFramework>
```

The revised app also displays the value of `Environment.Version` in the title bar, just as a runtime indication of the environment. The results are consistent--the selection tracks the menu item when using .NET Core, but the selection jumps from the menu item to its parent when using .NET Framework. I confirmed that this behavior also occurs with inspect.exe--this is most obvious when you enable Inspect.exe's highlighter.

The good new is that even with the framework bug, you can still inspect the menu items with AIWin. You can run automated checks with a timer (documented [here](https://accessibilityinsights.io/docs/windows/getstarted/automatedchecks/#running-automated-checks-with-a-timer)) to capture the state with the menu open, then click on "View results in the UI Automation tree" to inspect the UIA properties and values for the menu items). That's our recommended mechanism for transient controls, including menus.

Our team will discuss this issue in our next triage session. Realistically, though, it's highly unlikely that anything in AIWin will change to work around a framework bug, especially when the scenario is already supported as described above.

Thanks for using Accessibility Insights!

**Comment by DaveTryon** [comment]
@fangguoneng, I've opened a [ticket](https://developercommunity.visualstudio.com/t/NET-Framework-of-Windows-Forms-MenuStri/10043879) against .NET Framework 4.8, which may or may not result in a future change. At this point, it's in the hands of the owners of the .NET Framework implementation of WinForms. There's no further action that our team plans to take on this, so the bot has closed it automatically.

Thanks for using Accessibility Insights!

**Comment by fangguoneng** [comment]
@DaveTryon 
I got it. Thank you very much.
