### ISSUE TITLE
[BUG] Can not inspect inner control in textbox template.

### ISSUE THREAD

**Issue by fangguoneng** [microsoft/accessibility-insights-windows#1334]
**Describe the bug**
I have a textbox like this:
![image](https://user-images.githubusercontent.com/40819365/167620804-d4b26c78-e176-4474-b662-d44cf7380b39.png)

I can not inspect the part of title of this textbox.

**To Reproduce**
1. Run accessibility tool
2. Move mouse cursor over the title of textbox

**Expected behavior**
Inspecting the title of textbox

**Actual behavior**
Inspecting textbox

**Screenshots or .GIF**
![image](https://user-images.githubusercontent.com/40819365/167622977-949c2845-249e-401a-bd1b-8689ba8a536e.png)

Xaml:  
[MainWindow.txt](https://github.com/microsoft/accessibility-insights-windows/files/8661259/MainWindow.txt)

※ I can inspect it by [Inspect.exe].
![image](https://user-images.githubusercontent.com/40819365/167621567-c972eac4-a072-42b2-a583-01cbdc1ee805.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - Accessibility Insights for Windows Version: 1.1.1934.1
 - Target Application: WPF

**Comment by DaveTryon** [comment]
I'll take a look at this

**Comment by DaveTryon** [comment]
@fangguoneng, can you please provide a sample app do demo this? I can't identify enough information from just the screenshots. Thanks!

**Comment by DaveTryon** [comment]
Silly me! It's already there. Investigating...

**Comment by DaveTryon** [comment]
There are 2 things happening here. The first is that the inner Text control (The title) that the template adds inside the Edit control will only show up if the TreeViewMode is set to Raw (the default is Control). Changing that UI setting allows the Text control to display in the tree where it can be inspected, but it doesn't become the POI (Point of Interest) on mouse hover. Something in Axe.Windows' `MouseTracker` code is failing to track to the inner control.

**Comment by DaveTryon** [comment]
We ought to dig into this a little more deeply

**Comment by DaveTryon** [comment]
@fangguoneng, we've opened https://github.com/dotnet/wpf/issues/6655 to hopefully get this addressed in WPF. We're not planning on making any code changes on our side at this time. The workaround for now is to use raw mode then navigate to the inner controls via the UIA tree. Alternatively, you can run automated tests, then open the captured UIA tree. Please close this out at your convenience. Thanks!
