### ISSUE TITLE
Not recieving PropertyChanged event

### ISSUE THREAD

**Issue by roshkins** [microsoft/accessibility-insights-windows#1346]
I'm working on a project where I want to listen to `AutomationPropertyChanged` events where the `Name` property changes. When I check Listen to All events the only events I recieve are BoundingRectangle changes.
![image](https://user-images.githubusercontent.com/593949/169672037-ebfb638e-5ac3-48db-b885-8527daa8ca7e.png)

I saw there was an unanswered StackOverflow question with the same problem.: https://stackoverflow.com/questions/41252448/ui-automation-propertychangedevents-not-triggering-on-qt-app

Is there something I'm missing to recieve these events?

**Comment by ThanyaLeif** [comment]
Hi @roshkins,
Thanks for filling out this issue, could you provide us with a sample app and more information about how to reproduce this issue?
That will help us to go into further investigation.

**Comment by roshkins** [comment]
Hi @ThanyaLeif ! Here is a sample app that demonstrate the bug: https://github.com/roshkins/PropertyChangedEventTest/releases/tag/v0.0.1

Source code is included as well. Try inspecting both labels. The label on the top doesn't change it's bounding rectangle and it shows no events being fired when the text is rearranged. The bottom label does show the bounding rectangle being updated an no other events. Thanks for your help!

**Comment by ThanyaLeif** [comment]
Adding context to the thread:

- The `name` event is not listed by AccEvent as well.
- The framework used is WinForms.

**Comment by roshkins** [comment]
I'm glad you could reproduce it @ThanyaLeif ! Thanks for taking the time.

**Comment by DaveTryon** [comment]
I wrote a similar WPF test app, and AIWin successfully reports the PropertyChanged events when the name changes. That leads me to believe that we're property registering for the events, and that WinForms is probably just not generating them. I tried the .NET 6.0 version of WinForms--no change in behavior.

**Comment by DaveTryon** [comment]
@roshkins, we've opened https://github.com/dotnet/winforms/issues/7261 to let the WinForms team know about this problem. We don't think there's a way to fix this via a change in AIWin, so we're kicking this back to you. If you agree that there's nothing more to do, please close out this issue. Thanks!

**Comment by roshkins** [comment]
I agree there's nothing more for accessibility insights to do. I'll follow up with WinForms (I didn't know how to file the issue, so thanks for doing it).
