### ISSUE TITLE
[Feature Request] Make accessibility insights available from the new Microsoft Store

### ISSUE THREAD

**Issue by dpaulino** [microsoft/accessibility-insights-windows#1366]
**Is your feature request related to a problem? Please describe.**
I would like to make it easier and faster to install accessibility insights by having it in the microsoft store

**Describe the solution you'd like**
I propose deploying accessibility insights to the Microsoft Store using msix so it can leverage the auto-updating feature of the store and Windows. But if this is not possible, then at least deploy the msi installer to the store via the new support for traditional desktop apps. This way, users can still install the app from the store.

**Additional context**
Docs on MSIX: https://docs.microsoft.com/en-us/windows/msix/packaging-tool/create-an-msix-overview 
Docs on publishing a MSI installer to the store: https://docs.microsoft.com/en-us/windows/uwp/publish/msiexe/overview

**Comment by DaveTryon** [comment]
Thanks for the suggestion, @dpaulino! We've discussed this and are not going to act on this at this time. We're sort of stuck between 2 competing forces:
1. A small number of our users _need_ to have UIAccess support, which is only available if the product is installed to a file location that blocks write access to non-administrators. That means that we can't be a typical store app.
2. We have a corporate security requirements to be able to block usage of downstream versions of the app in the face of a major security problem. We don't have data on how upgrades would play if we were to ship a store app that is essentially a wrapper of an MSI file.

A previous [PR](https://github.com/microsoft/accessibility-insights-windows/pull/1331) was submitted to publish our app via WinGet, and we declined it for the same reasons.

Thanks for the feedback--we may be able to act on your suggestion at a future date, but it's out of scope at this time.

**Comment by dpaulino** [comment]
@DaveTryon I think there's some misunderstanding about the new store's capabilities.

>  need to have UIAccess support, which is only available if the product is installed to a file location that blocks write access to non-administrators
The new Microsoft Store provides a way to list your app on the store but with the _exact same_ MSI installer is used as the one you provide on your website. This means that the exact same app as your existing installer will be installed, and it will have the exact same abilities, and it will have UIAccess support because it will be installed in whatever directory your installer uses.

> We don't have data on how upgrades would play if we were to ship a store app that is essentially a wrapper of an MSI file.

The new support for MSI installers does not wrap around an MSI file. You provide a link to your MSI file, and the store will download it to a user's machine in the background and execute it. With this approach, you are responsible for handling your own app's update mechanism. The store and the OS will do absolutely nothing. Again, it's the _exact_ same experience as installing the app via your website. 

Does this clarify things?
