### ISSUE TITLE
[BUG] Application crashed without any ineraction

### ISSUE THREAD

**Issue by ChristoWolf** [microsoft/accessibility-insights-windows#1417]
**Describe the bug**
The application seemed to have crashed at random without actively interacting with it or inspection enabled.
I have attached the automatically created crash dump.

**To Reproduce**
It seemed to have happened at random, but here is what I know:
1. Accessibility Insights has been running for about 10-20 hours, and both the Highlighter and UI Automation Tree were off/paused.
2. Very likely not related, but the crash happened immediately after "hard-refreshing" (i.e. Ctrl+F5) in Microsoft Edge.

**Expected behavior**
No crash, Application Insights keeps running without any reaction.

**Actual behavior**
Application Insights crashed.

~~**Screenshots or .GIF**~~

**Desktop (please complete the following information):**
 - OS: Windows 10 version 20H2, OS Build 19042.1889
 - Accessibility Insights for Windows Version: [v1.1.1997.01](https://github.com/microsoft/accessibility-insights-windows/releases/tag/v1.1.1997.01)
 - ~~Target Application:~~
 - ~~Target Application Version:~~

**Additional context**
[Dump file (AccessibilityInsights.exe.7392.dmp.zip)](https://github.com/microsoft/accessibility-insights-windows/files/9400104/AccessibilityInsights.exe.7392.dmp.zip)

**Comment by pownkel** [comment]
Hi @ChristoWolf, sorry to hear you're experiencing unexpected crashes! For security reasons, we can't download unknown file attachments, so I'm afraid if we can't reproduce this bug there isn't much that our team can do. Are there any concrete repro steps you can give us to help us investigate this?

**Comment by ChristoWolf** [comment]
Hi @pownkel,
unfortunately, I have no idea how it happened.
Is there any other way how I could share the dump with you?

**Comment by pownkel** [comment]
@ChristoWolf We may be able to open it in a sandboxed VM environment, but there isn't a high chance that we'll be able to find the root cause. Let us take a look over the next day or so and get back to you.

**Comment by pownkel** [comment]
@ChristoWolf our team has investigated the dump file, but unfortunately didn't find anything to help us pin down the cause of the crash. Without knowing anything else, there isn't anything concrete we can do about this bug, so we will not be investigating further. Marking this issue as resolved.
