### ISSUE TITLE
[BUG] Highlighter and UI Automation Tree buttons' tooltips freeze eventually

### ISSUE THREAD

**Issue by ChristoWolf** [microsoft/accessibility-insights-windows#1418]
**Describe the bug**
Sometimes after the application has been running for some time, the Highlighter and UI Automation Tree buttons' tooltips freeze eventually when clicking the buttons, see attached screenshot.
Unfortunately, I am not sure how to reproduce this behavior.
The last time I have observed this though was after restarting Accessibility Insights after the crash in #1417. 

~~**To Reproduce**~~

**Expected behavior**
The tooltips vanish after a short time when moving away from any of the buttons.

**Actual behavior**
They stay rendered and only vanish after some time.
The issue persists even after restarting Accessibility Insights multiple times and only returns to normal when rebooting the machine.

**Screenshots or .GIF**
![frozen-tooltips](https://user-images.githubusercontent.com/52244643/186099869-990ce076-722b-4887-8a6a-33b66c2355d8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 version 20H2, OS Build 19042.1889
 - Accessibility Insights for Windows Version: [v1.1.1997.01](https://github.com/microsoft/accessibility-insights-windows/releases/tag/v1.1.1997.01)
 - ~~Target Application:~~
 - ~~Target Application Version:~~

~~**Additional context**~~

**Comment by pownkel** [comment]
Hi @ChristoWolf, does this bug only happen after a crash like the one in #1417? If not, how long does the app usually run before it appears?

**Comment by ChristoWolf** [comment]
Hi @pownkel,
no, I have observed this on multiple occasions, but I fail to see a pattern or any hints on what could cause this.
It was just that the last time I observed this was right after #1417.
Sorry that I cannot provide more helpful information.

**Comment by pownkel** [comment]
@ChristoWolf As with #1417, there isn't really anything we can investigate without repro steps or more information. Marking this resolved as well.
