### ISSUE TITLE
Migrate documentation from docs.microsoft.com to accessibilityinsights.io

### ISSUE THREAD

**Issue by risanaka** [microsoft/accessibility-insights-windows#143]
**Is your feature request related to a problem? Please describe.**
Today, doc.microsoft.com hosts the How to Fix guidance, but the content is specifically customized for the purposes of Accessibility Insights users; updates and feedback will most likely come from Accessibility Insights users.

**Describe the solution you'd like**
Accessibility Insights should own the "View Code Sample" content in a documentation repository.

**Describe alternatives you've considered**

**Additional context**

**Comment by risanaka** [comment]
This feature needs investigation, specifically around ownership of this documentation--while it's exclusively used by Accessibility Insights, philosophically, the content could be owned by the UI framework owners (since it describes best practices around accessibility).

Someone on the team needs to drive this conversation and clarify ownership.

**Comment by DaveTryon** [comment]
Per our discussion, you and @adrianaandreeva need to figure out what to do on this. For context, the links to docs.microsoft.com are in the links.json file that we install in the same folder as AIWin
