### ISSUE TITLE
[BUG] items in events data grid have UIA name "Axe.Windows.Desktop.UIAutomation.EventHandlers.EventMessage"

### ISSUE THREAD

**Issue by codeofdusk** [microsoft/accessibility-insights-windows#1438]
**Describe the bug**
Data items representing individual events captured by Accessibility Insights have the name `Axe.Windows.Desktop.UIAutomation.EventHandlers.EventMessage` in the UIA tree. This is read by screen readers as you navigate, making the event grid very hard to use.

**To Reproduce**
1. Start NVDA and Accessibility Insights.
2. Record events with the tool.
3. Navigate to the grid of recorded events.
4. Press down arrow.

**Expected behaviour**
NVDA reads a sane event description.

**Actual behaviour**
NVDA says "Axe.Windows.Desktop.UIAutomation.EventHandlers.EventMessage data item", followed by information about the event as children gain focus.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1809] (Get the version by running `winver` from the command line) Windows 11 SV2 (22622.598)
 - Accessibility Insights for Windows Version: 06abd42
 - Target Application: [e.g. Chrome, Wildlife Manager] Windows Console (`conhost.exe`)
 - Target Application Version: [e.g. 22] inbox

**Comment by DaveTryon** [comment]
Set name on element to "{Event Type} from {Event Source} at {Event Time}"

**Comment by codeofdusk** [comment]
Yes, this seems like a reasonable reading order.
