### ISSUE TITLE
Automatic color contrast detection is odd in high contrast (white)

### ISSUE THREAD

**Issue by risanaka** [Microsoft/accessibility-insights-windows#144]
**Describe the bug**
When Windows is in high-contrast (white) mode, the colors auto-detected by the color contrast analyzers aren't correct.

**To Reproduce**
1. Configure system for HC-White
1. Start AIWin
1. Go to color contrast mode
1. Scan some controls
1. Compare  auto-detected colors against actual colors

**Expected behavior**
auto-detected colors should closely match actual colors

**Actual behavior**
auto-detected colors are very different (see picture below). Confidence and color accuracy seem to have no correlation.

**Screenshots or .GIF**
![image](https://user-images.githubusercontent.com/144273/53616163-30b7dd00-3b96-11e9-9899-0ace4847f98a.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1809] (Get the version by running `winver` from the command line)
 - Accessibility Insights for Windows Version: 1.1.786.1
 - Target Application: Paint, OneNote
 - Target Application Version: [e.g. 22]

**Additional context**
Priority requested -

**Comment by neocln** [comment]
@babylonbee could you follow the instruction from Chris and add more info for Chris?
