### ISSUE TITLE
[Feature Request] Make scan sound unique

### ISSUE THREAD

**Issue by codeofdusk** [microsoft/accessibility-insights-windows#1444]
**Is your feature request related to a problem? Please describe.**
When the corresponding option is enabled, Accessibility Insights plays the sound at `%systemroot%\media\Windows Proximity Connection.wav` (Windows NFC connection sound) when scanning.

**Describe the solution you'd like**
Use a unique sound not included with Windows.

**Describe alternatives you've considered**
Keep sound as-is.

**Comment by DaveTryon** [comment]
@asksep, we think this is worth doing, but we need an appropriate sound. Assigning to you for follow-up
