### ISSUE TITLE
Inconsistent results between web and windows

### ISSUE THREAD

**Issue by secret-agent-B** [microsoft/accessibility-insights-windows#1453]
We have a ReactJS app that can be viewed on the web or within a Win32 app. Why do we get inconsistent accessibility issues between the Web and Windows versions of Accessibility Insights? Are they using 2 different logic/services to find issues?

**Comment by waabid** [comment]
Sorry for the delay in our reply!

With regards to web-based apps, we do suggest using Accessibility Insights for Web as it will provide the best/most actionable results. The Windows app will try its best based on the available UIA data but it is not always as complete. It is also possible some of the issues in Accessibility Insights for Windows may fall into the "uncertain results" category. This can be seen under the "Test > Results in UIA Tree" view in the gear menu.
