### ISSUE TITLE
Have LegacyIAccessiblePattern.Role report enum name instead of just the number

### ISSUE THREAD

**Issue by sivakusayan** [microsoft/accessibility-insights-windows#1454]
**Is your feature request related to a problem? Please describe.**
When I look at the MSAA role, AIWin only reports a number. For example, using AIWin with [this codepen](https://codepen.io/sivakusayan/pen/zYjgvaM) reports that all of the buttons have `LegacyIAccessiblePattern.Role=57`.

**Describe the solution you'd like**
It would be nice if AIWin instead said something like `LegacyIAccessiblePattern.Role=ROLE_SYSTEM_BUTTONMENU [57]` or something similar.

**Describe alternatives you've considered**
I get that MSAA is deprecated and all, but there are still applications using MSAA/IAccessible2 (such as Chrome and Firefox). I'm not sure if checking the UIAutomation `ControlType` property is enough, since the translation isn't always perfect (it seems the bridge tries to map `ROLE_SYSTEM_BUTTONMENU` to UIAutomation `MenuItems`, for example).

**Comment by ferBonnin** [comment]
thanks for the feature @sivakusayan, we'll add this to our backlog!

**Comment by DaveTryon** [comment]
@sivakusayan, this is now live in our Canary release--here's a screenshot showing the enum name with the value:

<img width="1423" alt="image" src="https://user-images.githubusercontent.com/45672944/203575292-6b17aed9-1ec7-48e5-9556-fb434dcd667c.png">

Our next Production release will probably be in January 2023. You can switch to the Canary release through the settings tab, or you can install the bits directly from https://github.com/microsoft/accessibility-insights-windows/releases/tag/v1.1.2151.01

I'm assigning this issue back to you for closing. Thanks!

**Comment by sivakusayan** [comment]
Thank you so much for implementing this, it looks great! Closing 😀
