### ISSUE TITLE
Instruction text for Live Inspect's Events pane is not clear.

### ISSUE THREAD

**Issue by risanaka** [Microsoft/accessibility-insights-windows#146]
**Describe the bug**
The current instruction test for Live Inspect's Events pane is not clear.

**To Reproduce**
1. Open an app to test.
1. Open Accessibility Insights for Windows.
1. Open Live Inspect.
1. Set focus on an element and select `Shift + F7`. You can also use the context menu > Listen to events.

**Expected behavior**
In the Events pane, there's instruction text: "Select the events to listen to in the **Configuration** tab, and select Record [record button] to start recording. You can also press Shift + F7."

**Actual behavior**
"Select the Events you want to listen to in the Configure Events tab and press record to start recording."

**Screenshots or .GIF**
![image](https://user-images.githubusercontent.com/144273/53620781-0a4f6d00-3ba9-11e9-805c-9693a608a3fb.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1809] (Get the version by running `winver` from the command line)
 - Accessibility Insights for Windows Version: 1.1.786.2
 - Target Application: Enterprise Database (Developer Sample)
 - Target Application Version: [e.g. 22]

**Additional context**
Priority requested -
- Larger UX discussion on the Configuration tab name should be considered before fixing this issue.

**Comment by neocln** [comment]
@risanaka IMO the part of Ux change(tab name) which requires a bigger design discussion should be a separate issue to track since we don't want to have a bug stalled long while. 
@babylonbee could you file an issue to @risanaka to follow up the tab name issue separately and fix this text issue?

**Comment by risanaka** [comment]
@babylonbee let's fix this issue with the current proposed UI text; please update the [record button] with the appropriate Fabric icon. thanks!
