### ISSUE TITLE
Tab stops test does not draw the first tab stop indicator.

### ISSUE THREAD

**Issue by risanaka** [microsoft/accessibility-insights-windows#151]
**Describe the bug**
When running the tab stops test, the number (1) isn't shown on an element if it already has focus when you turn on the tab stops test. 

**To Reproduce**
1. Open the [Enterprise app](https://www.microsoft.com/en-us/p/enterprise-database-developer-sample/9pf1wcv13501).
1. In Customers, select + New.
1. In New customer, set focus in the First name field.
1. Turn on Record tab stops.
1. Press the Tab key once.

**Expected behavior**
The number (1) appears on the First name field.

**Actual behavior**
The number (1) appears on the Last name field.

**Screenshots or .GIF**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1809] (Get the version by running `winver` from the command line)
 - Accessibility Insights for Windows Version:
 - Target Application: [e.g. chrome, safari]
 - Target Application Version: [e.g. 22]

**Additional context**
Priority requested -

**Comment by neocln** [comment]
Since it is a feature request, I remove [BUG] from the title.

**Comment by risanaka** [comment]
@ferBonnin - this issue has a consistency problem between Web and Windows on how Tab stops is displayed. Can you drive the conversation?

**Comment by ferBonnin** [comment]
@risanaka for sure :)

**Comment by Sirisha-Kommushetty** [comment]
@ferBonnin - Can we connect on this. Seems like a bug that can be fixed for both Windows and Web.

**Comment by ferBonnin** [comment]
@Sirisha-Kommushetty lets connect. The problem here is that Web and Windows behave differently. (Windows doesnt draw the first tab stop indicator)

**Comment by jalkire** [comment]
@Sirisha-Kommushetty @ferBonnin For context, there is no good/intentional reason why Windows doesn't draw the first tab stop. It just happened to be that way. I hope we decide to make the change 👍

**Comment by ferBonnin** [comment]
@jalkire thanks for the context! :) I agree

**Comment by ferBonnin** [comment]
from conversation with Peter, size of this is probably bug, changing tags and marking ready for work

**Comment by Sirisha-Kommushetty** [comment]
@risanaka - Could you validate this in the latest canary builds and close it? Thank you!

**Comment by risanaka** [comment]
@Sirisha-Kommushetty validated and closing. Thanks for the fix :)
