### ISSUE TITLE
[BUG] Hierarchy settings menu does not honor dark mode

### ISSUE THREAD

**Issue by sfoslund** [microsoft/accessibility-insights-windows#1528]
**Describe the bug**
Hierarchy settings menu does not honor dark mode

**To Reproduce**
1. Open AIWin in dark mode
2. Live inspect any app
3. Click Settings icon at top right of left panel
4. See hierarchy settings menu is in light mode

**Expected behavior**
Entire app adheres to dark mode setting

**Actual behavior**
Hierarchy settings menu remains in light mode

**Screenshots or .GIF**

[Description: Screenshot of AI win in dark mode, with hierarchy settings menu open and still in light mode]
<img width="667" alt="AIWinDarkModeSettings" src="https://user-images.githubusercontent.com/16010855/212184028-e6a26171-2989-44c2-b76f-d6c4cff1de5e.png">

**Desktop (please complete the following information):**
 - OS: Windows 11 22621
 - Accessibility Insights for Windows Version: Current prod (1.1.2089.1)
 - Target Application: Wildlife Manager
 - Target Application Version: 2.0

**Comment by jlperkins** [comment]
Repro'd, thanks for finding this Sarah!

**Comment by sfoslund** [comment]
It looks like we have the same issue with the event settings menu as well:

[Image description: screenshot of AI win event settings menu open in dark mode, menu is still light grey]
<img width="831" alt="EventSettingsNotDarkMode" src="https://user-images.githubusercontent.com/16010855/213752075-c6ba760c-7297-45fb-aa7e-5f8f8b101382.png">

**Comment by DaveTryon** [comment]
This has been fixed in Canary since release 1.1.2249.01. Closing the issue as fixed.
