### ISSUE TITLE
[Feature Request] Improve patterns UX

### ISSUE THREAD

**Issue by risanaka** [microsoft/accessibility-insights-windows#153]
**Is your feature request related to a problem? Please describe.**
Today, we receive anecdotal feedback that the patterns UX is not intuitive.

**Describe the solution you'd like**
We want to improve the overall patterns UX so that it's easy to use even for complicated patterns such as Text Pattern.

**Describe alternatives you've considered**
We can write extensive documentation, but this is just the first step.

**Additional context**

**Comment by risanaka** [comment]
@risanaka to review usability studies and telemetry data to gather information on usage of the patterns UX

**Comment by DaveTryon** [comment]
Needs to be assigned to Siri

**Comment by Sirisha-Kommushetty** [comment]
@DaveTryon - Can we get click stream telemetry on the various patterns supported. This will help us inform the next steps.

**Comment by Sirisha-Kommushetty** [comment]
Its a good idea, but at this point in time, our roadmap does not include modifying these dialogs.
