### ISSUE TITLE
[BUG] Non-breaking spaces make ADO bugs harder to read

### ISSUE THREAD

**Issue by DaveTryon** [microsoft/accessibility-insights-windows#1545]
**Describe the bug**
The Axe.Windows rules include 83 instances of non-breaking space (`\u00a0`) characters in their "How to fix" instructions. When filing a bug to ADO, these non-breaking spaces get replaced with question marks, which makes the bug less readable.

**To Reproduce**
1. Configure to file bugs to ADO
2. Start WildlifeManager
3. Scan the entire app
4. File a bug for the datagrid, rule "The Name must not include the same text as the LocalizedControlType"
5. Compare the description in the bug to the description in the UI

**Expected behavior**
The non-breaking spaces should not clutter the bug.

**Actual behavior**
The non-breaking spaces clutter the bug because they get replaced with `?`. As a point of reference, GitHub issue filing matches the App UI--only ADO is impacted here

Context | Simulated output
--- | ---
App | Provide a UI Automation Name property for the element that:<br> · Concisely identifies the element, AND<br> · Does not include the same text as the element's LocalizedControType property
ADO | Provide a UI Automation Name property for the element that: -?Concisely identifies the element, AND -?Does not include the same text as the eleme...
Github | Provide a UI Automation Name property for the element that:<br> · Concisely identifies the element, AND<br> · Does not include the same text as the element's LocalizedControType property

_If_ we choose to fix this, the simplest fix is to leave the rules unchanged, and to modify [`AzureDevOpsIntegration.EscapeForUrl`](https://github.com/microsoft/accessibility-insights-windows/blob/main/src/AccessibilityInsights.Extensions.AzureDevOps/AzureDevOpsIntegration.cs#L491-L514) to special case the non-breaking space--the output could use a regular space or just skip the character. Here are simulations of each option:

Option | Simulated output
--- | ---
Regular space | Provide a UI Automation Name property for the element that: - Concisely identifies the element, AND - Does not include the same text as the eleme...
Omitted space | Provide a UI Automation Name property for the element that: -Concisely identifies the element, AND -Does not include the same text as the eleme...

 - OS: Windows 11 (not OS-dependent)
 - Accessibility Insights for Windows Version: 1.1.2089.01

**Additional context**
This problem has been around for a long time and is not a recent regression.

**Comment by codeofdusk** [comment]
Closed via #1546.
