### ISSUE TITLE
[BUG] Win11 tray icon middle click does not worked

### ISSUE THREAD

**Issue by henrypp** [microsoft/accessibility-insights-windows#1596]
I do not know how to report about bug to microsoft, so i created this issue.

**Describe the bug**
Your latest windows 11 22h2 (22621.1555) has tray icon bug, it does not retrieve double click message into tray icon message.

**To Reproduce**
Any app with tray icon, or run attached application. [win11_tray_bug.zip](https://github.com/microsoft/accessibility-insights-windows/files/11253020/win11_tray_bug.zip)

**Expected behavior**
On win10 worked as expected, only on win11.

**Comment by henrypp** [comment]
I understand, but:

> I do not know how to report about bug to microsoft, so i created this issue.

So how? Email or something? `Win` + `F` does not worked for me at all.

**Comment by dot-clear** [comment]
You could try over there : 

- https://support.microsoft.com/en-us/topic/troubleshoot-repair-ceaa4aee-fa3b-4ca4-9ddb-bde4dc310dc9#WindowsVersion=Windows_11

- https://support.microsoft.com/contactus#!
