### ISSUE TITLE
[BUG] Dark mode menu overtheming in TextPattern Explorer

### ISSUE THREAD

**Issue by DaveTryon** [microsoft/accessibility-insights-windows#1609]
**Describe the bug**
The TextPattern explorer doesn't respond to dark mode theming, but the context menus are themed. In Prod, only the settings menus are themed; In Canary, the "..." context menu is also themed (this last change was caused by #1529).

**To Reproduce**
1. Set your system to dark mode
2. Run AIWin
3. Open the Text Explorer dialog
4. Click on the ... button or either of the gear buttons

**Expected behavior**
Context menus in unthemed dialogs should probably also be unthemed--they look a bit odd when they're mixed.

**Actual behavior**
The ideal (but unlikely) fix would be to theme the dialogs that are currently unthemed. Probably the more realistic fix would be to have an unstyled theme for context menus and use that from all unstyled dialogs.

**Screenshots or .GIF**

Menu | Image
--- | ---
Range Settings | ![image](https://user-images.githubusercontent.com/45672944/236584311-c6561233-7d68-4558-bb21-3e568f459f0d.png)
Attribute Settings | ![image](https://user-images.githubusercontent.com/45672944/236582778-033f59f2-4379-45d1-b10c-813ae12022ce.png)
Text Settings | ![image](https://user-images.githubusercontent.com/45672944/236582896-023dc755-285d-4300-b6de-74040ef2edbd.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - Accessibility Insights for Windows Version: 1.1.2312.1

**Additional context**
Priority requested -

**Comment by dbjorge** [comment]
Note: we'd like to attempt the harder version of the fix (make the dialog(s) dark-mode compatible), but try to do it within a time box

**Comment by DaveTryon** [comment]
Upon further investigation, this is significantly more work than we are prepared to invest at this time. WPF does not provide a good way to theme the dialog caption bar, and carrying the full theming through all of the actions and properties dialogs is something that does not fit into our current prioritized backlog. We're going to close this and leave it as is.
