### ISSUE TITLE
[BUG] AI-Win does not save event details in event file

### ISSUE THREAD

**Issue by karanbirsingh** [Microsoft/accessibility-insights-windows#161]
**Describe the bug**
AI-Win does not save event details in serialized event files. When loading such a file, the event details are blank.

**To Reproduce**
- Steps to reproduce the behavior:
- open Wildlife Manager or any app & ai-win
- Hover over window
- Listen to events
- Select any event configuration
- Record some events
- Make sure some of the events have "event details" in the bottom right of ai-win
- Save the event file
- Load the event file
- Notice the event details are empty

**Actual behavior**
- the event details should not be empty

**Screenshots or .GIF**
<img width="668" alt="screenshot of events" src="https://user-images.githubusercontent.com/7775527/53918170-23c63e00-401b-11e9-8d83-29c9791f02a1.PNG">

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1809] (Get the version by running `winver` from the command line)
 - Accessibility Insights for Windows Version: Windows 10 1809
 - Target Application: [e.g. chrome, safari] Wildlife manager

This issue should be fixed post-CSUN

**Comment by neocln** [comment]
@babylonbee could you take a look at this?

**Comment by neocln** [comment]
@karanbirsingh could you regress and close?

**Comment by karanbirsingh** [comment]
looks good
