### ISSUE TITLE
[Feature Request] Upgrade WiX to v4

### ISSUE THREAD

**Issue by BMurri** [microsoft/accessibility-insights-windows#1641]
**Is your feature request related to a problem? Please describe.**
WiX v3 has now been deprecated with the release of v4. Barring barriers to upgrade you should be moving to v4, which better supports modern CI/CD, modern SDK integrations, and all current windows platforms.

**Describe the solution you'd like**
Currently maintained projects should be keeping up with the tooling they depend on.

**Describe alternatives you've considered**
Staying with WiX v3 is untenable because it's likely to never receive any updates, security or otherwise, especially as time passes.

**Additional context**
If you'd prefer, assign this issue to me and I'll provide you with a PR.

**Comment by DaveTryon** [comment]
@BMurri, we'd welcome a PR to handle this. Please be aware that our current solution uses custom actions, which may complicate the task.

If you feel up to it, we'd also welcome a PR to upgrade our WiX usage in the https://github.com/microsoft/axe-windows repo 😄

**Comment by BMurri** [comment]
I looked at the custom action, upgrading it to v4 is straightforward, but as a setup/deployment expert, I have questions about the advisability of keeping it.

I can also upgrade the other repo if you wouldn't mind opening an issue there and assigning it to me.

**Comment by DaveTryon** [comment]
@BMurri, the behavior of the custom actions are intentional and desired. Please retain the behavior as it is. Thanks!
