### ISSUE TITLE
Can the option to defer a software update be added as currently the tool closes if you don't update or have an active internet connection. Many firms also have software release processes that cannot work as quickly as the updates come through. The ability to postpone would be welcomed.

### ISSUE THREAD

**Issue by ChrisHollowayAccessibility** [microsoft/accessibility-insights-windows#1644]

**Comment by DaveTryon** [comment]
Triage notes: This is the same basic issue as #1186. It works this way because of the SDL requirement to be able to force a security update. In this specific case, AIWin had 2 production releases a couple of weeks apart, which is an atypical release cadence.

**Comment by DaveTryon** [comment]
@ChrisHollowayAccessibility, our security requirements don't allow us to make this change. I provided a per-machine workaround in your associated StackOverflow post. Thanks for using Accessibility Insights!

**Comment by ChrisHollowayAccessibility** [comment]
I was happy with the work around provided so happy for this to be closed and the fix documented.
