### ISSUE TITLE
[BUG] Accessibilityinsight  v1.1.2360.01 reports chromium components issues

### ISSUE THREAD

**Issue by alanPage2** [microsoft/accessibility-insights-windows#1651]
when testing a windows application with accessibility insights v1.1.2360.01
it says  chromium components should be scanned with a web-based scanner and many errors reported

please check if there is a way to handle this? I am testing this windows application that has many web components, its not possible to test this with a web version of accessibility insights

thanks guys!

**Comment by alanPage2** [comment]
thanks Madalyn! your answer is much appreciated!
how about the 3rd option here to use an older version of accessibilityinsights like v1.1.2213.01, does that help with my windows app or no that we may miss more important issues if we keep using older version?

**Comment by madalynrose** [comment]
Hi, @alanPage2!

We don't recommend using an older version and don't make older versions of Accessibility Insights for Windows available for download. 

We do have an issue related to the scanning Chromium-based UIs in the axe-windows repository so keep an eye there for updates: https://github.com/microsoft/axe-windows/issues/836. 

Closing this issue in favor of the issue in axe-windows.
