### ISSUE TITLE
[BUG] Consider replacing UIA with UI Automation

### ISSUE THREAD

**Issue by risanaka** [Microsoft/accessibility-insights-windows#167]
**Describe the bug**
Currently, the app refers to UI Automation as UIA; looking at the [UI Automation reference docs](https://docs.microsoft.com/en-us/windows/desktop/winauto/entry-uiauto-win32), UIA is not the correct acronym for the tech.

**To Reproduce**
1. Clone the repository.
1. Search for "UIA " in the code base.

**Expected behavior**
UIA is not used when referring to UI Automation.

**Actual behavior**
UIA is used when referring to UI Automation.

**Screenshots or .GIF**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1809] (Get the version by running `winver` from the command line)
 - Accessibility Insights for Windows Version:
 - Target Application: [e.g. Chrome, Wildlife Manager]
 - Target Application Version: [e.g. 22]

**Additional context**
Add any other context about the problem here:

**Comment by neocln** [comment]
> @risanaka, we might want to consider this in terms of cross-platform support. UIAutomation is specifically a Windows technology, and the code in AccessibilityInsights.Core (where most of these values are named) is intended to be platform-agnostic (although it really isn't agnostic at the moment). Let's talk about this.

@risanaka @DaveTryon Dave's point is valid. but the code of work is for AI-Win for now. let's take this overall design conversation to offline.

**Comment by neocln** [comment]
@risanaka fix is merged to master. please pick up daily to regress.

**Comment by risanaka** [comment]
Verified in 1.1.810.1 - closing the issue. Thanks for fixing it, folks :)
