### ISSUE TITLE
Standalone application

### ISSUE THREAD

**Issue by rbdavison** [microsoft/accessibility-insights-windows#1675]
Can you please create a standalone application that can be run from an USB drive.

## Problem space:

I have a computer with software installed that I can't install anything on to the computer without voiding the certification/qualifications of the computer/software. I can however copy data files off and onto the computer.
I would like to write UIAutomation against the software on this computer to automate the use of this software in our test system.

## Proposed Solution:

Create a standalone version of Accessibility Insights for Windows that is a standalone application that can be downloaded as a ZIP file. Extracted to a directory, and then run from that directory on any windows computer without the need to install anything on that computer.

## Test scenario:

* Users can download a ZIP file of Accessibility Insights that is standalone.
* The ZIP file can be extracted to external media (USB stick)
* Accessibility Insights can be run from the extracted location on a computer without requiring any software installations. i.e. dotnet runtimes.

**Comment by JGibson2019** [comment]
@rbdavison there is a zip file of the application source code available for download of AIWin tied to each release. [Here is a link to our most recent release](https://github.com/microsoft/accessibility-insights-windows/releases/tag/v1.1.2406.01) as an example. This should fit your proposed solution! Feel free to re-open the issue if this does not solve your problem.

**Comment by rbdavison** [comment]
Yes I did see that the source code was available. However this is not the same thing as a tested running standalone application.
While I'm a software developer, many in my team that would like to use Accessibility Insights in the standalone environment are not.
If you'd prefer that I build and distribute the application built to our needs that's fine. It can be done that way. But I'd prefer not to do this when a new build / publish profile could be added to the existing build process to produce the same outcome.
Would you prefer I make changes to the code base and submit a pull request?

**Comment by DaveTryon** [comment]
@rbdavison, we have no plans to produce a ZIP installer at this time. Thanks for the suggestion.
