### ISSUE TITLE
Question About the software tool. [Priority/Important] 

### ISSUE THREAD

**Issue by dannyguzman508** [microsoft/accessibility-insights-windows#1676]
**We encourage tool related questions to be asked on stackoverflow.com and tagged with `accessibility-insights`.**

**Hi there - I am government employee at FDIC and we want to download the tool to use in the 508 team. Could you guys provide guidance in answering the question below for a self attestation. 

"An acceptable self-attestation must include the following minimum requirements: i. The software producer's name; 3 ii. A description of which product or products the statement refers to (preferably focused at the company or product line level and inclusive of all unclassified products sold to Federal agencies); iii. A statement attesting that the software producer follows secure development practices and tasks that are itemized in the standard self-attestation form"
**
All the help is very appreciate it.

Thanks,

Danny Guzman

**Comment by JGibson2019** [comment]
@dannyguzman508 our team is unfamiliar with the "self-attestation" outlined above, and our recommendation is that you ask within the FDIC for assistance.
