### ISSUE TITLE
[BUG] Screen scaling problem

### ISSUE THREAD

**Issue by Descolada** [microsoft/accessibility-insights-windows#1688]
**Describe the bug**
On a multi-monitor setup where DPIs of the monitors differ, Accessibility Insights detects and highlights elements at wrong coordinates in Chromium windows (Chrome, Spotify, Discord etc). 

**To Reproduce**
Open Chrome on a secondary screen which DPI differs from the primary screen and try to inspect elements

**Screenshots or .GIF**
<img width="600" alt="Chrome_AccessibilityInsights" src="https://github.com/microsoft/accessibility-insights-windows/assets/16986957/08e2671d-6d48-4936-9d98-58f68ed1886c">

**Desktop (please complete the following information):**
Primary monitor: 14' screen @ 1920x1080 resolution, DPI 144 (150%)
Secondary monitor: 34' screen @ 3440x1440 resolution, DPI 96 (100%)
 - OS: Windows 10 ver 22H2 (build 19045.3324)
 - Accessibility Insights for Windows Version: latest (v 1.1.2406.1)
 - Target Application: Chrome, Spotify, Discord displayed on the secondary monitor
 - Target Application Version: Chrome v 116.0.5845.141

This might very well be instead a Chromium or UIAutomation issue, but I don't know how to figure out which.

**Comment by DaveTryon** [comment]
Hi, @Descolada! We've looked into this and there appears to be a problem in the interaction between Chromium and Windows. Here's another way to see the same sort of problem without using Accessibility Insights:

- Start Magnifier on one one display and resize it to fill the top half of the display
- Go to its settings (click the gear button)
- Set the view to "Docked"
- Uncheck "Mouse pointer"
- Run a Chromium app (like opening this web page) on the other display
- Use the tab key to navigate around the Chromium app, and watch how Magnifier responds.
 
When things are working correctly, the cursor will remain centered in the Magnifier window. When I do this in an app using WPF or Windows forms, it works very well. When I do this in Chrome, the results are mixed. Some elements (like edit controls or images) usually do a good job of staying centered. Other elements (like links or buttons) often don't fare as well. The effect can be exaggerated by resizing the browser window to occupy just the center 50% of the screen horizontally and vertically. Magnifier will often show parts of the screen that aren't even inside the Chrome window.

Trying to get this fixed may be difficult. Chromium supports an accessibility technology called `IAccessible2`, which is not directly supported by Windows. Recent versions of Windows provide a mapping layer that converts `IAccessible2` to `UIA`, and an error in either layer could cause the element's `BoundingRectangle` property to report incorrectly scaled coordinates. I hope this helps explain what's going on--Accessibility Insights is just using the bad data that it's receiving from UIA.

Thanks for helping us improve Accessibility Insights!
