### ISSUE TITLE
[BUG] Windows Release Pipelines use inline script to upload manifest to Azure Blob Storage

### ISSUE THREAD

**Issue by madalynrose** [microsoft/accessibility-insights-windows#1795]
**Describe the bug**
Now that the service connections used in our release pipelines use federated credentials, the Azure File Copy task needed to be replaced as it [does not support workload identity](https://github.com/Azure/azure-storage-azcopy/issues/2545). The current solution is to use the Azure CLI task with the `az storage blob upload` command. We have tested the task with an inline script to confirm that it succeeds, but the ideal solution would use a script inside `/tools/scripts/pipeline` that is tracked via source control.

**To Reproduce**
1. Go to the "AIWin: Automated Canary Release" pipeline
2. Click "Edit" and "Pipeline"
3. Go to "Tasks"
4. Click on the "Azure CLI" task

**Expected behavior**
The Azure CLI task references a script from release artifacts in the deploy_scripts directory, like the "Set Variables" PowerShell task does.

**Actual behavior**
The Azure CLI task uses an inline script.

**Additional context**
Creating this issue so this work is tracked.
This work will need to be done for three places:
* AIWin: Automated Canary Release
* AIWin: Release Promotion
  * Insider
  * Production

**Comment by DaveTryon** [comment]
Since this is just a 1 line script and we'd still need to customize the pipeline, we'll just keep the script in the pipeline and not add it to the repo.
