### ISSUE TITLE
Disable telemetry condition for our organisation

### ISSUE THREAD

**Issue by olgatolk71** [microsoft/accessibility-insights-windows#1844]
I work for the IT Accessibility office at Employment and Social Development Canada (ESDC). We need the 'Accessibility Insights for Windows' tool for our accessibility assessments of software.

To get approval for installation, our Security team has requested that Telemetry Data be disabled as a condition for download. I suggested the steps provided on your website, but the testing team informed me that they need a command line to disable the telemetry pre-installation, which will be incorporated into the package script.

They asked me to contact the vendor to inquire about a command line that will disable telemetry during installation.

Could you please advise on this? Thank you very much in advance.

Olga Maximova (Tolkachev)

Technical advisor IT Business line support services, IT Accessibility office - ICT Accessibility Audit and Strategy (ICTAAS)
Employment and Social Development Canada / Government of Canada
email: [olga.maximova@hrsdc-rhdcc.gc.ca](mailto:olga.maximova@hrsdc-rhdcc.gc.ca) / Tel: 873-396-1721

**Comment by v-viyada** [comment]
@olgatolk71 Please refer https://github.com/microsoft/accessibility-insights-windows/blob/main/docs/TelemetryOverview.md#control-of-telemery for guidance on how domain admins can completely disable telemetry within an organization. Please let me know if any more details are required. Thanks
