### ISSUE TITLE
Design discussion for instruction text for Live Inspect's Events pane

### ISSUE THREAD

**Issue by babylonbee** [microsoft/accessibility-insights-windows#196]
**Describe the bug**
The name of Configuration tab and other things in Event Pane design should be revisited. 
this is based on #146 issue.  

**To Reproduce**
Please find out more detail information on #146

**Comment by neocln** [comment]
@risanaka @cheade could we have a short chat on this matter next week?

**Comment by risanaka** [comment]
@cheade please schedule time with @neocln on this issue.

**Comment by neocln** [comment]
Chelsea and I talked about it and we need input from PM(s) on the below approach. 
1. List up the possible User scenarios and create the instruction docs for each user scenarios. 
2. use the user scenarios with current instruction, Chelsea will investigate further on the improvement of Ux.

**Comment by neocln** [comment]
@adrianaandreeva let's turn this as a feature. please let me know if you need more context on it.

**Comment by Sirisha-Kommushetty** [comment]
@cheade - Can we connect and talk about this. Should we think of a usability study/signal interviews at some point?
