### ISSUE TITLE
[BUG] The maximize button on AI-Win doesn't change in maximized mode

### ISSUE THREAD

**Issue by risanaka** [Microsoft/accessibility-insights-windows#199]
**Describe the bug**

**To Reproduce**
Using build 1.1.0794.01:

1. Start AI-Win;
1. Hit "Get Started";
1. Click the maximize button on the top right

Expected result:
The maximize button should change to a restore button.

**Expected behavior**
The maximize button stays as the maximize button.

**Actual behavior**
What actually happened.

**Screenshots or .GIF**
In the screenshot below, the maximize button on the top right is still the maximize button:
![A maximized Accessibility Insights for Windows still has the maximize button in the top menu bar](https://user-images.githubusercontent.com/144273/54722845-df5e9600-4b22-11e9-9800-8e45a9f6793c.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1809] (Get the version by running `winver` from the command line)
 - Accessibility Insights for Windows Version:
 - Target Application: [e.g. Chrome, Wildlife Manager]
 - Target Application Version: [e.g. 22]

**Additional context**
Priority requested -

**Comment by babylonbee** [comment]
fix has been provided and merged to master
