### ISSUE TITLE
[BUG] Need to improve the startup sequence.

### ISSUE THREAD

**Issue by risanaka** [Microsoft/accessibility-insights-windows#202]
**Describe the bug**
The current startup sequence can take up to 2 - 3 seconds while it checks for new updates before showing the Welcome page or launching Inspect mode.

Users feel that the app is not responding during those few seconds, and we need to improve this experience.

**To Reproduce**
1. Launch Accessibility Insights for Windows in a location with poor WiFi.

**Expected behavior**
Users see a visual indicator that the app is launching.

**Actual behavior**
Nothing is displayed on the screen until Accessibility Insights for Windows finishes checking for updates.

**Screenshots or .GIF**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1809] (Get the version by running `winver` from the command line)
 - Accessibility Insights for Windows Version:
 - Target Application: [e.g. Chrome, Wildlife Manager]
 - Target Application Version: [e.g. 22]

**Additional context**
Recommendation from Min: use the [WPF splash experience](https://docs.microsoft.com/en-us/dotnet/api/system.windows.splashscreen?view=netframework-4.7.2).
![WPF splash experience](https://user-images.githubusercontent.com/144273/54726336-f48df180-4b2f-11e9-9e67-26d2d1d95c72.gif)

**Comment by risanaka** [comment]
@cheade recommendation from @neocln is to use WPF's splash experience (see the GIF in the bug description); this is a static picture, are you okay with that?

**Comment by cheade** [comment]
A static splash screen is not totally ideal, as users can get antsy if they don't see any movement, even if it's just a looping animation of dots or a loading circle, but it is definitely better than not having anything at all. I can make a splash screen mockup for this purpose. 

Are there static dimensions for this splash screen or is it flexible?

**Comment by karanbirsingh** [comment]
@cheade The splash screen can be any image, so AFAIK we can pick any size. Extra notes:

> If the image is a PNG file and it includes an alpha channel, the image is rendered using the transparency defined in the alpha channel. You cannot include placeholder text in the splash screen that is later added by your code. If you want to include text in the splash screen, you must add it to the image file.

**Comment by cheade** [comment]
Just to keep this on my radar I've got a [design task](https://dev.azure.com/mseng/Azure%20DevOps%20Design/_workitems/edit/1493091) and [Figma file](https://www.figma.com/file/MxXdGGjWOjE7KaL3rfJNed5C/Accessibility-Insights-for-Desktop?node-id=2227%3A21168) created for this:

**Comment by neocln** [comment]
@cheade do you have ETA for your design? I would like to have this change in next release(week of 4/12).

**Comment by cheade** [comment]
I was hoping to go over the options I have on Tuesday in our design meeting but we can definitely go over it in our meeting on Monday if you'd like to discuss sooner!

**Comment by neocln** [comment]
We are waiting for the next design meeting for selecting a flash window screen.

**Comment by karanbirsingh** [comment]
using this png from @cheade - 
![splash-screen](https://user-images.githubusercontent.com/7775527/56163713-df1bb400-5f83-11e9-9b9f-ab720758fe95.png)

**Comment by DaveTryon** [comment]
Closing on Risa's behalf
