### ISSUE TITLE
[BUG] Test reports null BoundingRectangle on ScrollBar button

### ISSUE THREAD

**Issue by chlowell** [Microsoft/accessibility-insights-windows#205]
**Describe the bug**
Automated tests identify one of the button children of a vertical scrollbar in the top or bottom position as having null `BoundingRectangle`. However, debugging the visual tree in Visual Studio, I find `BoundingRectangle` set for each of these buttons.

(If the scroll bar is in an intermediate position between top and bottom, the test passes.)

**To Reproduce**
1. Debug the [repro app](https://github.com/chlowell/scrollbar-uia-name) in Visual Studio
1. Scroll the vertical scrollbar to the top or bottom
1. Test the groupbox in Accessibility Insights for Windows

**Expected behavior**
The test should pass. Visual Studio's Live Visual Tree shows `BoundingRectangle` values on the `ScrollBar`'s button children:
![image](https://user-images.githubusercontent.com/10964656/54771052-ba6d3000-4bc1-11e9-997b-b61a570e20be.png)

**Actual behavior**
One of the child buttons of the scroll bar is identified as having a null `BoundingRectangle`:
![image](https://user-images.githubusercontent.com/10964656/54769876-5e091100-4bbf-11e9-8087-d4c8635e31b1.png).

**Desktop:**
 - OS: Windows 10 1809
 - Accessibility Insights for Windows Version: 1.1.794.1
 - Target Application: WPF ScrollViewer [repro app](https://github.com/chlowell/scrollbar-uia-name)

**Comment by risanaka** [comment]
Thanks for reporting, @chlowell; we are investigating the issue.

**Comment by DaveTryon** [comment]
Here's what's happening here:
1- WPF creates 5 buttons within a scroll bar--they are Line up, Page up, Thumb, Page down, and Line down
2- When the thumb is in the extreme up position, the Page up button still exists in the element tree but has no bounding rectangle. The Page down button does the same thing if the thumb is in the extreme down position. As a reference, the system scroll bar removes the unusable buttons from the element tree, but WPF doesn't change the tree.

I discussed this with @RobGallo, and his suggestion is to soften the rule to exclude this check on the Page up and Page down buttons within a WPF scroll bar. Assigning the bug to him for now, priority undetermined.

**Comment by neocln** [comment]
@chlowell we will have a new build published in 2 weeks. please let us know if you need the fix earlier than that.

**Comment by neocln** [comment]
@chlowell could you regress this issue and close it? We released a new build yesterday(4/24). It should have a fix for this issue.

**Comment by chlowell** [comment]
Thanks, this doesn't repro for me in 1.1.850.1
