### ISSUE TITLE
[BUG] Color contrast foreground and background colors inverted.

### ISSUE THREAD

**Issue by flyingUnderTheRadar** [Microsoft/accessibility-insights-windows#210]
**Describe the bug**
Color contrast tests do not have the correct foreground and background colors selected in the automated mode.

**To Reproduce**
1. Go to color contrast test
2. Click on any target application element
3. Look at the colors set as foreground and background in the color contrast test page

**Expected behavior**
Foreground and background colors are correctly set

**Actual behavior**
They are inverted.

**Screenshots or .GIF**
![image](https://user-images.githubusercontent.com/45673569/54841897-a4c53c80-4c8d-11e9-9a85-8c1be62b0c9d.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1809] (Get the version by running `winver` from the command line)
 - Accessibility Insights for Windows Version:
 - Target Application: [e.g. Chrome, Wildlife Manager]
 - Target Application Version: [e.g. 22]

**Additional context**
Min's suggestion was to change the text of Background and Foreground color to color 1 and color 2 (we had this before but changed it since then) since this is not something that really matters.

**Comment by neocln** [comment]
@risanaka @cheade the names(Foreground color and Background color) should be Color 1 and Color 2 since contrast is based on two colors not, foreground and background. 
so my suggestion is to change labels to Color 1 and Color 2. any concern?

**Comment by cheade** [comment]
@neocln @risanaka When is color contrast necessary and not against a foreground and background? All the color color contrast analyzers I've used treat them as foreground and background. 

Is there a problem in the auto detect in which the system may not know if it's a background or foreground and thus switching the two?

**Comment by risanaka** [comment]
> @neocln @risanaka When is color contrast necessary and not against a foreground and background? All the color color contrast analyzers I've used treat them as foreground and background.

@cheade as far as I know, contrast ratio requirements are against texts and images of texts, and it's against the text color and the background.
 
> Is there a problem in the auto detect in which the system may not know if it's a background or foreground and thus switching the two?

as far as I can tell from the repro steps, yes, it appears that we're not able to distinguish which is which.

Some things to consider: the auto detect may not know which is background or foreground, but when a user manually selects, they do know which is foreground/backgound, and the preview currently assumes that the first color is the foreground, and the second color is the background. If we switch to color 1/2, does it make sense to show a preview for each scenario (where first color is foreground vs second color is background)?

**Comment by neocln** [comment]
> > @neocln @risanaka When is color contrast necessary and not against a foreground and background? All the color color contrast analyzers I've used treat them as foreground and background.
> 
> @cheade as far as I know, contrast ratio requirements are against texts and images of texts, and it's against the text color and the background.
> 
> > Is there a problem in the auto detect in which the system may not know if it's a background or foreground and thus switching the two?
> 
> as far as I can tell from the repro steps, yes, it appears that we're not able to distinguish which is which.
> 
> Some things to consider: the auto detect may not know which is background or foreground, but when a user manually selects, they do know which is foreground/backgound, and the preview currently assumes that the first color is the foreground, and the second color is the background. If we switch to color 1/2, does it make sense to show a preview for each scenario (where first color is foreground vs second color is background)?

Contrast is based on two colors. This tool can be used to compare two colors which may not be foreground or background. 
whether it is auto or manual, still saying "Color 1/Color 2" is more accurate than foreground and background. 
even our instruction is talking about two colors, not foreground or background. 
![image](https://user-images.githubusercontent.com/8387801/54851560-a13eaf00-4ca7-11e9-9da7-e5a93b64719f.png)

**Comment by cheade** [comment]
I guess my question is more of, why would a user be testing two different colors on the page for contrast between each other when they are not foreground/background? I can't recall an instance where a user would need to check for contrast of items that are not sitting on top of one or the other. 

From the repro steps, @flyingUnderTheRadar, is it every time that they are switched or is it only sometimes?

**Comment by risanaka** [comment]
As far as I know, there’s no other scenarios where we’d be looking at contrast ratio.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by neocln** [comment]
> I guess my question is more of, why would a user be testing two different colors on the page for contrast between each other when they are not foreground/background? I can't recall an instance where a user would need to check for contrast of items that are not sitting on top of one or the other.
> 
> From the repro steps, @flyingUnderTheRadar, is it every time that they are switched or is it only sometimes?

@cheade it happens sometimes AFAIK.

**Comment by flyingUnderTheRadar** [comment]
Yes it happens sometimes. I have tried it 8 - 10 times. If I was to hazard a guess it seems that the darker color is set as the foreground color. So if you run windows in dark mode black would show up as the foreground color even though its actually white.

**Comment by cheade** [comment]
![image](https://user-images.githubusercontent.com/40274682/54856716-1e265480-4cb9-11e9-9497-37401a6ade70.png)

Web seems to refer to the foreground and background when noting the colors. Do we know if they have any issues with them being reversed?

**Comment by karanbirsingh** [comment]
> Web seems to refer to the foreground and background when noting the colors. Do we know if they have any issues with them being reversed?

@cheade one difference to keep in mind is that the web tool can rely on HTML property values like `color`, whereas our tool does not have access to the XAML used to generate the UI. Since our tool needs to analyze a screenshot, the heuristic can have a tough time deciphering which is which.

**Comment by neocln** [comment]
@cheade @risanaka Any other thought?

**Comment by neocln** [comment]
@risanaka based on our offline conversation, could you add a new figma (or at least mockup) of the UI to show both cases?

**Comment by risanaka** [comment]
@neocln, @cheade is working on a Figma mockup right now; @cheade, once the Figma is ready, please respond with both a screenshot and a Figma link to this issue, and remove the "needs design input" label.
Thanks!

**Comment by cheade** [comment]
![Color contrast](https://user-images.githubusercontent.com/40274682/54944395-a17dbb00-4ef0-11e9-874a-58f3acaf99f3.png)

[Updated Color contrast UI Figma mock](https://www.figma.com/file/MxXdGGjWOjE7KaL3rfJNed5C/Accessibility-Insights-for-Desktop?node-id=2192%3A21117)

Please let me know if you have any questions!

**Comment by neocln** [comment]
@flyingUnderTheRadar please regress it with the daily build of 3/26 and close.

**Comment by flyingUnderTheRadar** [comment]
Regressed via 1.1.814.1 (Daily build). Looks good.

![image](https://user-images.githubusercontent.com/45673569/55018565-5aef9580-4fb0-11e9-87ba-895f16df41ec.png)
