### ISSUE TITLE
[BUG] Improve instruction text in Color Contrast Analyzer

### ISSUE THREAD

**Issue by risanaka** [Microsoft/accessibility-insights-windows#216]
**Describe the bug**
With the improvements made in #210, the color contrast analyzer has more things in its UI. We want to re-visit the instruction text, especially as it already links to a tutorial via the info icon.

**To Reproduce**
1. Launch Accessibility Insights for Windows.
1. Go to Color Contrast.

**Expected behavior**
Users know how to get started right away with the Color Contrast Analyzer and isn't overwhelmed by the amount of introductory content.

**Actual behavior**
The intro text can introduce scrollbars under certain sizes:

Intro text: To auto detect an element's contrast ratio, hover over the element within a target application or set keyboard focus on the element. The analyzer will update with the auto detected colors, the contrast ratio, and the confidence level.

To manually select two colors to test the contrast ratio, select each color using the Eyedropper. You can also select a color using the Color Picker box or enter its hex code.

![Due to the intro text being long, the color contrast analyzer itself is hard to see without scrolling](https://user-images.githubusercontent.com/144273/54951338-9af73f80-4f00-11e9-88bb-739d6dbf42cd.png)

**Screenshots or .GIF**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1809] (Get the version by running `winver` from the command line)
 - Accessibility Insights for Windows Version:
 - Target Application: [e.g. Chrome, Wildlife Manager]
 - Target Application Version: [e.g. 22]

**Additional context**
Priority requested -

**Comment by risanaka** [comment]
@cheade can you take a look at the UI string update and review it with Rob?

**Comment by cheade** [comment]
[Figma File](https://www.figma.com/file/MxXdGGjWOjE7KaL3rfJNed5C/Accessibility-Insights-for-Desktop?node-id=394%3A19735)

**Comment by neocln** [comment]
@karanbirsingh could you take care of this bug?

**Comment by karanbirsingh** [comment]
Closing on Risa's behalf
