### ISSUE TITLE
Update UI text for Issue Filing feature

### ISSUE THREAD

**Issue by risanaka** [Microsoft/accessibility-insights-windows#220]
Repro steps:
1. Clone the jalkire/github-feature branch.
1. Enable the bug filing extensions ([Instructions to debug extensions](https://github.com/Microsoft/accessibility-insights-windows/blob/master/docs/DebuggingExtensions.md).

## Dialog when user hasn't signed in yet
Repro steps:
1. Run Accessibility Insights for Windows.
1. Run FastPass against the Wildlife Manager app.
1. Select File issue.

Expected behavior:
To file issues, select where you want to file issues.

Actual behavior:
To file issues, select an issue tracker and specify the desired location..

Screenshot:
![image](https://user-images.githubusercontent.com/144273/55036713-ae75d980-4fd8-11e9-819c-fd4169ab2390.png)

## Connection tab UI text
Repro steps:
1. Run Accessibility Insights for Windows.
1. Run FastPass against the Wildlife Manager app.
1. Select File issue.
1. Select OK in pop-up dialog.

Expected behavior:
Under Issue Filing, it reads: "To start filing issues, select where you want to file your issues. Learn more about issue filing."

Actual behavior:
Lorem ipsum.

**Comment by flyingUnderTheRadar** [comment]
@risanaka - The figma  has the text that we see in the screenshot. Is this the latest iteration of it?

**Comment by risanaka** [comment]
@flyingUnderTheRadar thanks for catching that, updated the Figma

**Comment by AhmedAbdoOrtiga** [comment]
@risanaka  for "Learn more about issue filing." what would be the link?

**Comment by AhmedAbdoOrtiga** [comment]
This one was resolved in the [Support GitHub Issue Filing](https://github.com/Microsoft/accessibility-insights-windows/pull/230), so closing
