### ISSUE TITLE
[BUG] Checkboxes in automated checks do not affect screenshot highlighting on first load

### ISSUE THREAD

**Issue by karanbirsingh** [Microsoft/accessibility-insights-windows#227]
**Describe the bug**
The first time tests are run against an application, the checkboxes in automated checks do not change the visibility of the image highlighter. However, if you view the hierarchy tree and return to the automated checks screen, the checkboxes work properly.

**To Reproduce**
1. Run tests against Wildlife Manager or any app
2. Toggle any of the checkboxes in the automated checks screen
3. Notice that the red rectangles on the screenshot do not change visibility
4. Click on 'view results in UIA tree'
5. Return to 'Tests'
6. Notice that now the screenshot rectangle visibility does react to any checkbox on the automated check screen

**Expected behavior**
In step 3 above, the red rectangles should change visibility when the checkbox is toggled in the automated checks view

**Actual behavior**
The rectangles stayed visible

**Screenshots or .GIF**
![animated gif of issue](https://user-images.githubusercontent.com/7775527/55116228-e007a700-50a3-11e9-9221-fd5df34dc112.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10 1809
 - Accessibility Insights for Windows Version: 1.1.791.4
 - Target Application: Wildlife Manager

**Additional context**
FYI, highlighter actions may be moving to SharedUX soon but functionality should be intact

**Comment by neocln** [comment]
it is because items under groups are not populated yet. 
![image](https://user-images.githubusercontent.com/8387801/55262361-d78da880-522a-11e9-9ba1-6b5ddb4f937c.png)

**Comment by neocln** [comment]
it turns out that the problem is more on the counting of a highlighter than the visibility of list item. 
@jalkire please continue the investigation.

**Comment by neocln** [comment]
@karanbirsingh could you regress it and close?

**Comment by karanbirsingh** [comment]
Looks fixed in latest signed build from master (1.1.0821.01)
