### ISSUE TITLE
[BUG] ContentViewSpinnerStructure should allow ListItem

### ISSUE THREAD

**Issue by LiLoDavis** [Microsoft/accessibility-insights-windows#268]
**Current rule**
The given element is expected to have the following structure: Spinner and NoChild(IsContentElement).

**Proposed rule**
The rule should allow ListItems.
See the documentation: https://docs.microsoft.com/en-us/windows/desktop/winauto/uiauto-supportspinnercontroltype#typical-tree-structure

**Comment by neocln** [comment]
@RobGallo could you take a look?
