### ISSUE TITLE
[BUG] ContentViewSplitButtonStructure should allow MenuItem

### ISSUE THREAD

**Issue by LiLoDavis** [Microsoft/accessibility-insights-windows#269]
**Current rule**
The given element is expected to have the following structure: SplitButton and ( == 1 or == 2) and AllChildren(not(IsContentElement) or Button).

**Proposed rule**
The rule should allow MenuItem.
See the documentation: https://docs.microsoft.com/en-us/windows/desktop/winauto/uiauto-supportsplitbuttoncontroltype#typical-tree-structure

**Comment by RobGallo** [comment]
This rule actually does check for menu items. It just isn't apparent from the malformed description. Once the description is fixed (in PR now), it will read.

The given element is expected to have the following structure: SplitButton and (CountChildren(Button and AnyChild(IsContentElement) and AllChildren(not(IsContentElement)
or MenuItem)) == 1 or CountChildren(Button and AnyChild(IsContentElement) and AllChildren(not(IsContentElement) or MenuItem)) == 2) and AllChildren(not(IsContentElement)
or Button).
