### ISSUE TITLE
[BUG] ControlViewSplitButtonStructure should allow Menu and MenuItem

### ISSUE THREAD

**Issue by LiLoDavis** [Microsoft/accessibility-insights-windows#273]
**Current rule**
The given element is expected to have the following structure: SplitButton and ( == 1 or == 2) and <= 1 and <= 1 and AllChildren(not(IsControlElement) or (Button or Image or Text)).

**Proposed rule**
The rule should allow Menu and MenuItem.
See the documentation: https://docs.microsoft.com/en-us/windows/desktop/winauto/uiauto-supportsplitbuttoncontroltype#typical-tree-structure

**Comment by RobGallo** [comment]
This rule actually already does support menu items. It's just that it isn't visible from looking at the description. The description generation code was updated as part of another change. It now reads:

The given element is expected to have the following structure: SplitButton and (CountChildren(Button and NoChild(IsControlElement) or CountChildren(MenuItem)
== 1 and AllChildren(not(IsControlElement) or MenuItem)) == 1 or CountChildren(Button and NoChild(IsControlElement) or CountChildren(MenuItem) == 1 and
AllChildren(not(IsControlElement) or MenuItem)) == 2) and CountChildren(Image) <= 1 and CountChildren(Text) <= 1 and AllChildren(not(IsControlElement)
or (Button or Image or Text)).
