### ISSUE TITLE
[BUG] ControlViewTabStructure should allow Button

### ISSUE THREAD

**Issue by LiLoDavis** [Microsoft/accessibility-insights-windows#274]
**Current rule**
The given element is expected to have the following structure: Tab and AnyChild(IsControlElement) and AllChildren(not(IsControlElement) or (Group or ScrollBar or TabItem)).

**Proposed rule**
Rule should allow Button.
See the documentation: https://docs.microsoft.com/en-us/windows/desktop/winauto/uiauto-supporttabcontroltype#typical-tree-structure

**Comment by karanbirsingh** [comment]
We have added a new rule that validates ScrollBar structure. That rule ensures that a ScrollBar has either a button or a thumb as its child - this should indirectly resolve this issue. The next canary [release](https://github.com/Microsoft/accessibility-insights-windows/releases) (4/11) should include this fix.

**Comment by ferBonnin** [comment]
Hi @LiLoDavis this issue has been resolved. Could you verify?
Thanks!

**Comment by LiLoDavis** [comment]
Solution makes sense to me.

**Comment by ferBonnin** [comment]
Closing issue then :)
