### ISSUE TITLE
[BUG] Structure rules should include IsContentElement/IsControlElement/pattern checks and increased unit test coverage

### ISSUE THREAD

**Issue by karanbirsingh** [microsoft/accessibility-insights-windows#282]
The [structure rules](https://github.com/Microsoft/accessibility-insights-windows/tree/master/src/AccessibilityInsights.Rules/Library/Structure) have the following gaps:
- they run on elements regardless of whether `IsControlElement` or `IsContentElement` is true. 
- unit test coverage is light on these rules
- in some cases, additional pattern guidance has been added in Microsoft documentation (example [here](https://docs.microsoft.com/en-us/windows/desktop/winauto/uiauto-supportspinnercontroltype)). Our rules do not use the pattern when selecting elements to test

Because these are best-practice rules (evaluated as either `Pass` or `Note`), the user impact is not too high if the rules are unnecessarily run or scoped too loosely. However, we should be as close to the docs as possible.

We should consider making a full pass through the [documentation](https://docs.microsoft.com/en-us/windows/desktop/winauto/uiauto-supportinguiautocontroltypes) to:
- ensure [content rules](https://github.com/Microsoft/accessibility-insights-windows/tree/master/src/AccessibilityInsights.Rules/Library/Structure/ContentView) and [control  rules](https://github.com/Microsoft/accessibility-insights-windows/tree/master/src/AccessibilityInsights.Rules/Library/Structure/ControlView) only test elements if `IsControlElement` or `IsContentElement` is true
- add unit tests for each class
- where appropriate, ensure rules only test elements if the appropriate pattern exists

**Comment by neocln** [comment]
We may need to turn this as a feature based on the rough estimation of this work.

**Comment by neocln** [comment]
@adrianaandreeva please consider it for a new feature.

**Comment by karanbirsingh** [comment]
Moving to axe-windows repository: https://github.com/microsoft/axe-windows/issues/28
