### ISSUE TITLE
Insights can't gather all autosuggest items in Chrome or Teams

### ISSUE THREAD

**Issue by DanUyematsu** [Microsoft/accessibility-insights-windows#285]
**Repro Steps:**

1. Launch Insights
2. Launch Chrome
3. Type "T" in the URL for Chrome
4. Press down arrow and navigate through all the suggestions (you can also use the mouse)
5. Verify that each item shows up in Insights

Note, you can see the same behavior in the Teams Desktop version in the Search box (Ctrl + E).

**Results**
When using the keyboard, Insights is not populating data for each suggestion item.  For the mouse most of the suggestion items do not show up in Insights.

**Expected**
Insights should be showing data for every items in the suggestion drop down.

**Comment by neocln** [comment]
@DanUyematsu could you tell us which build of Windows you are using?

**Comment by DanUyematsu** [comment]
I'm using Windows 10 Version 1903 (OS Build 18362.53)

**Comment by neocln** [comment]
@AhmedAbdoOrtiga could you repro it and investigate it?

**Comment by AhmedAbdoOrtiga** [comment]
After investigation, I'll contact Windows Team (IA2-UIA Feature Crew) to investigate the issue from their side for the following reasons:
- The function we use `UIAutomation.ElementFromPoint` to detect the current element doesn't see the autocomplete list which maybe something wasn't handled or mapped correctly in the IA2 proxy.
- I tried to use a different API to get the element `AutomationElement.FromPoint`, still the autocomplete list is somehow invisible.
- The Inspect.exe tool still read the same result like AI-Win (doesn't read the autocomplete list, read what's behind).
- Narrator can't read the Chrome autocomplete list, but it reads Team's, while Jaws read both.

**Comment by AhmedAbdoOrtiga** [comment]
Closing, after investigation, this isn't a bug in AI-Win. A bug with this information was sent to the Windows Team to investigate the UIA APIs.
