### ISSUE TITLE
[BUG] EditSupportsOnlyValuePattern should return an error

### ISSUE THREAD

**Issue by LiLoDavis** [microsoft/accessibility-insights-windows#287]
The UIA spec (https://docs.microsoft.com/en-us/windows/desktop/winauto/uiauto-supporteditcontroltype) requires every edit control to support at least the Text control pattern. The Value pattern is supplemental. This rule should return an error.

**Comment by neocln** [comment]
@karanbirsingh it is the same issue which we discussed this morning right?

**Comment by karanbirsingh** [comment]
@neocln no - we discussed #270

**Comment by karanbirsingh** [comment]
From the docs link, it says:

Control Pattern/Pattern Property | Support/Value | Notes
-- | -- | --
IValueProvider | Depends | All edit controls that take a string must expose the Value control pattern.

If I am reading it correctly, it seems like the rule matches the docs (not an error). Please let me know if I am missing something.

**Comment by LiLoDavis** [comment]
@karanbirsingh As I understand it, the rule fires when an edit control supports the value pattern but does not support the text pattern. The documentation says **ITextProvider** is required,** while **IValueProvider** depends. The only thing wrong with the rule is how the outcome is reported. I believe  failure instances should be shown as errors instead of uncertain.

**Comment by karanbirsingh** [comment]
@LiLoDavis makes perfect sense, thanks. I'll follow up with @RobGallo / @neocln with this in case there is any other context I should be aware of about this rule before making the change

**Comment by karanbirsingh** [comment]
We will make this change after the axe-windows transition has settled

**Comment by karanbirsingh** [comment]
Issue moved to axe-windows repo, closing this
