### ISSUE TITLE
[BUG] ControlShouldNotSupportWindowPattern should return an Error

### ISSUE THREAD

**Issue by LiLoDavis** [Microsoft/accessibility-insights-windows#288]
The UIA spec (https://docs.microsoft.com/en-us/windows/desktop/winauto/uiauto-supportpanecontroltype#required-control-patterns) says a pane control should NEVER support the Window pattern. 
This rule should return an error.

**Comment by neocln** [comment]
@LiLoDavis your point is valid. However, with the existing frameworks, there are some cases that this is not 100% honored, though the user impact is low. so we adjusted the rule to return a warning.

**Comment by LiLoDavis** [comment]
@neocln Ok, then in my documentation, I'll mark this as a Framework bug rule.
