### ISSUE TITLE
[Feature Request] What's new content hasn't been updated since initial release

### ISSUE THREAD

**Issue by DaveTryon** [microsoft/accessibility-insights-windows#299]
**Describe the bug**
The content of the What's new dialog needs to be updated to reflect features added since the initial release

**To Reproduce**
1. Go to the What's new dialog
2. Look at the content

**Expected behavior**
The content should have reference to GitHub issue filing and release channels

**Actual behavior**
The content is unchanged from the initial release

**Screenshots or .GIF**
![image](https://user-images.githubusercontent.com/45672944/56150059-cfd83e80-5f62-11e9-906a-d533183e7d6f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1903
 - Accessibility Insights for Windows Version: 1.1.0834.01

**Comment by neocln** [comment]
@adrianaandreeva we need a way to display some contents of the "What's new" page. 
could you assign a PM on this and define a Ux on it? once that's done, we need a feature to implement it.

**Comment by Sirisha-Kommushetty** [comment]
@cheade - We have some thoughts on how this page can be revamped. Would be great to chat next week and close on the next steps.

**Comment by Sirisha-Kommushetty** [comment]
Had a discussion with @cheade and @DaveTryon on the next steps here.

**Comment by Sirisha-Kommushetty** [comment]
@cheade - Any updates on this?

**Comment by cheade** [comment]
Last we all talked we had decided that we will be getting rid of the "What's new" tab. Here is the [Figma mock](https://www.figma.com/file/MxXdGGjWOjE7KaL3rfJNed5C/Accessibility-Insights-for-Desktop?node-id=2325%3A23545), but I don't believe we have any major changes.

**Comment by DaveTryon** [comment]
Welcome screen is finally updated in the current canary build (see https://github.com/microsoft/accessibility-insights-windows/releases/tag/v1.1.1230.01). Closing this out.
