### ISSUE TITLE
[BUG] Typo in ScannerResultControl_btnFileBug_Click_File_Issue_Configure

### ISSUE THREAD

**Issue by DaveTryon** [Microsoft/accessibility-insights-windows#306]
**Describe the bug**
The string resource identified as ScannerResultControl_btnFileBug_Click_File_Issue_Configure has a typo, leading to a confusing message.

**To Reproduce**
1. Start AIWin without any issue filing configuration
2. Scan an app with problems (WildlifeManager works fine)
3. Attempt to file a bug from the app
4. The following dialog is displayed:

![image](https://user-images.githubusercontent.com/45672944/56241271-53b92600-604a-11e9-83f9-e3e23912ff4d.png)

**Expected behavior**
The error message should say **To file issues, select where you want to file issues.**, but it's confusing since it's missing the first letter.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1809
 - Accessibility Insights for Windows Version: 1.1.835.1
 - Target Application: Wildlife Manager

**Additional context**
Priority requested -

**Comment by karanbirsingh** [comment]
@DaveTryon just an fyi, merging the PR closed this out
