### ISSUE TITLE
[BUG] AI-Win telemetry reports wrong OS versions

### ISSUE THREAD

**Issue by DaveTryon** [Microsoft/accessibility-insights-windows#326]
**Describe the bug**
The AI-Win telemetry reports only 2 values for the OS. It's either **Microsoft Windows NT 6.1.7601 Service Pack 1** for Windows 7 SP1 (our lowest supported platform) or **Microsoft Windows NT 6.2.9200.0** for everything else, meaning that we have no meaningful OS version data in our telemetry.

**The fix**
The fix is to uncomment the boilerplate **supportedOS** sections in the manifest files. That will cause the OS to report the correct OS info without any code change.

**The risk**
By uncommenting the **supportedOS** pieces in the manifest files, we also change some of our high DPI behavior. There's a good overview of this at https://walbourn.github.io/manifest-madness/. We had a ***lot*** of trouble getting high DPI support right, so if we enable this, we'll need to plan on testing (and maybe fixing high DPI issues) in at least the following areas:
- Highlighter overlay (live and in snapshot)
- Tabstop overlay
- Position and rendering of the snapshot button
- Proper activation of a scan by clicking the snapshot button

It's fine if we choose not to fix this, as long as we're also willing to live with the lack of usable OS info in the telemetry.

**Comment by neocln** [comment]
@DaveTryon as we discussed, please investigate it.
