### ISSUE TITLE
[Bug] Users installing Canary or Insider builds are in Production Channel

### ISSUE THREAD

**Issue by DaveTryon** [Microsoft/accessibility-insights-windows#335]
**Problem**
Users are in the Production channel by default, even if they're on a build that is still being treated as Canary or Insider. This is a potential for confusion, as the UI shows no prompt to let the user know that they're on a pre-production build. It also reduces the build validation benefit we get from having users choose to stay current with pre-production Channels.

**Proposed solution**
At startup, we should check to see if the currently version is newer than the version assigned to the user's selected Channel. If it is, we should check that version to determine the Channel currently assigned to that version, and ask the user if they'd like to change to that Channel (we should tell the user what channel they're on (typically Production), what channel is being proposed (Insider or Canary), and maybe include the existing descriptions of how the Channels compare. The user should have choices similar to 
- Change to the XYZ channel now (where XYZ is the proposed Channel--the change will only change the ReleaseChannel setting, and will not trigger a version switch in the middle of the user's session)
- Ask the next time I start the app
- Ask the next time I change versions (For most users, this is the same as "don't ask me again"--only users who manually install new versions will get prompted more than once, and we want to try to remind these users who are manually managing their builds that we can do it for them)

Since this touches the UX, we need to get design input on the user interaction.

**Considered/Rejected Solution**
At one point, we released different sets of bits for different target audiences. We've intentionally moved to a model where we release only one set of bits per version. That's more consistent with typical OSS practices, and we don't want to go back to the old way.

**Comment by cheade** [comment]
@DaveTryon is this occurring just for users who have downloaded insider or canary builds prior to the channel switcher being implemented? 

If this is not the case, shouldn't we put the users in the channel of their selected download? 
E.g.; if the user chooses to download for the first time a version from the canary list, installing that version should automatically put them in the canary channel.

**Comment by cheade** [comment]
If putting the users in the channel of their selected download is not possible and/or the issue is referring to our users who are on a canary/insider build pre-channel switcher feature implementation, is this close to what you were referring to needing in the product?

![Frame](https://user-images.githubusercontent.com/40274682/56775672-f83f1480-677c-11e9-9a6f-481e355a92d9.png)

**Comment by DaveTryon** [comment]
@cheade All channels currently support the version switcher, so we can disregard scenarios involving very old builds. Auto-assigning a channel when no channel is configured (i.e., a first install) sounds reasonable to me, as does displaying a dialog when the installed version is newer than the newest build in the configured channel. 

In the proposed dialog, I'm not sure what should happen after the user clicks "Stay in Production". Should it trigger a version switch back to a Production-supported build, or should it serve as a temporary override and continue running the Canary version without changing anything? If it's a temporary override, is it just for that app session?

**Comment by cheade** [comment]
@DaveTryon I guess a better question is, what is the scenario in which a user has an installed version that is newer than the newest build in the configured channel?

For the dialog that I mocked up - I was under the assumption that a user couldn't be using the product without having a configured channel, and that the default channel was Production.

**Comment by DaveTryon** [comment]
After a couple of iterations, we're closing this issue and have opened #347 to track it
