### ISSUE TITLE
[BUG] Update/switch channel UAC dialog appears behind app

### ISSUE THREAD

**Issue by jalkire** [Microsoft/accessibility-insights-windows#336]
**Describe the bug**
If AI-Win attempts to install a new version of itself, whether from auto-update or from channel change, the UAC dialog is obscurred.

**To Reproduce**
1. Open AI-Win to the center of your default monitor 
2. Go to settings
3. Ensure AI-Win is always on top before proceeding
4. Change channel
5. Save and close

**Expected behavior**
The UAC prompt should be on top of AI-Win

**Actual behavior**
The UAC prompt is behind AI-Win

**Screenshots or .GIF**
Updating:
![image](https://user-images.githubusercontent.com/4615491/56621914-21c43880-65e3-11e9-8413-c7864bca3137.png)

Changing channel:
![image](https://user-images.githubusercontent.com/4615491/56621978-47e9d880-65e3-11e9-9ed4-9c31f90af28f.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10 1809

**Comment by neocln** [comment]
@jalkire could you take care of this? we may need to set the main windows not to be TopMost when we get into update mode.
