### ISSUE TITLE
FastPass dont report error

### ISSUE THREAD

**Issue by armanio123** [Microsoft/accessibility-insights-windows#349]
**Description**
FastPass is reporting a BoundingRectangle issue in one computer but it doesn't on another.

**To Reproduce**
1. Install Visual Studio with Node.js Tools workload.
2. Create a new Blank Node.js Console App.
3. Right click on the project node > properties.
4. Run fast pass on the separator line.
5. One computer reports error another doesn't.

**Expected behavior**
The error is either reported all the time or not reported. 

**Actual behavior**
Error appears to be inconsistent.

**Screenshots or .GIF**
Error shown:
![Regressed_819149_issue is  not fixed](https://user-images.githubusercontent.com/13305542/57159662-52eaf880-6d9b-11e9-9fc9-ffb5df499c38.png)
Error not shown:
![NoRepro](https://user-images.githubusercontent.com/13305542/57159932-37ccb880-6d9c-11e9-89ac-35f1818ab70a.png)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows Version 1908 Build 17763.437
 - Accessibility Insights for Windows Version: 1.1.837.2
 - Target Application: Visual Studio 2019 and 2017
 - Target Application Version: 16.1 Preview and 15.9.11 respectively.

**Comment by ferBonnin** [comment]
Hey @armanio123 could you give us the Accessibility Insights for Windows Version of the other computer where FastPass is reporting this issue?

**Comment by armanio123** [comment]
I'm not sure since this is executed by a tester, the last screenshot shows: 1.1.589.2. I can ask to be sure but it will take some time to respond.

**Comment by ferBonnin** [comment]
@armanio123 that sounds like an old version of Accessibility Insights for Windows. We make bug fixes every release, could we ask the tester if he still repro the issue in the latest version or not?

**Comment by armanio123** [comment]
We have tried with the latest version available and the experience is consistent between computers. I'll close the issue. Thanks for taking a look.
