### ISSUE TITLE
[BUG] Canary build does not show the beaker when hovering elements

### ISSUE THREAD

**Issue by ferBonnin** [microsoft/accessibility-insights-windows#354]
**Describe the bug**
Canary ver 1.1.858.1 does not show beaker when inspecting elements

**To Reproduce**
1. open Accessibility Insights for Windows 
2. try to inspect elements

**Expected behavior**
beaker appears over elements to trigger automated checks

**Actual behavior**
no beaker

**Screenshots or .GIF**
![screenshot of the corner, no beaker](https://user-images.githubusercontent.com/9062104/57546600-f2ffcf00-7311-11e9-9f92-54aab279b683.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1809] Windows 10 1903
 - Accessibility Insights for Windows Version: Canary ver 1.1.858.1
 - Target Application: [e.g. Chrome, Wildlife Manager] Wildlife manager

**Comment by DaveTryon** [comment]
I just tried this with 1.1.858.1 on 2 different machines, and it worked as expected. I wonder if it's a variant of the DPI problems that we saw previously...
