### ISSUE TITLE
[BUG] Selecting Settings nav item after Connection nav item closes the Settings view.

### ISSUE THREAD

**Issue by risanaka** [microsoft/accessibility-insights-windows#364]
Please check whether the bug has [already been filed](https://github.com/Microsoft/accessibility-insights-windows/issues).

**Describe the bug**

If I select the Settings nav item after selecting the Connection nav item, it closes the Settings view.

**To Reproduce**
1. Launch Accessibility Insights for Windows.
1. Select the Connections nav item.
1. Select the Settings nav item.

**Expected behavior**

The main content switches to Settings > Application view.

**Actual behavior**
What actually happened.

The main content switches back to Live Inspect view.

**Screenshots or .GIF**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1809] (Get the version by running `winver` from the command line) Windows 10 1903
 - Accessibility Insights for Windows Version: v 1.1.863.1
 - Target Application: [e.g. Chrome, Wildlife Manager] N/A
 - Target Application Version: [e.g. 22] N/A

**Additional context**
Priority requested -

Seems odd that it "closes" the Settings view when, for all of the other nav items, selecting them after opening said nav item doesn't close it/return the user back to Live Inspect.

**Comment by AhmedAbdoOrtiga** [comment]
This might not be a bug though considering the cases we would need to handle if we switch to Settings > Application view, @DaveTryon what do you think

**Comment by DaveTryon** [comment]
Seems like a bug to me

**Comment by DaveTryon** [comment]
@cheade, the core issue here is a discrepancy between how the 2 nav buttons work. The connections button always takes the user to the Connections tab in the settings view. The Settings button acts as a toggle and closes the settings view if it's open. What are your thoughts on removing the toggle behavior, and simply having the settings button go directly to the Settings tab?

**Comment by cheade** [comment]
I noticed this as well and thought it was a bug. I would not anticipate the settings button to act as a toggle, it should act as navigation (having the settings button go directly to the main settings tab, and the connections button go directly to the connections tab).

**Comment by karanbirsingh** [comment]
@jalkire can you think of any implications of removing the toggle-like behavior of the settings button? If not, we can set this as ready-to-triage.

**Comment by DaveTryon** [comment]
This should have been set "ready for work", as it's already been triaged. We just forgot to update the status. If this is a mistake, we'd sure love to hear about it :)

**Comment by jalkire** [comment]
@karanbirsingh No, I can't think of any unintended consequences from this change

**Comment by karanbirsingh** [comment]
This has been merged into master and should show up in the next canary build (likely on 6/25)

**Comment by Sirisha-Kommushetty** [comment]
@risanaka - Can you validate this against the latest canary builds and close it? Thank you!

**Comment by risanaka** [comment]
@cheade to confirm: regardless of which settings tab I navigated to last, the settings icon should still take me to the Application tab within Settings, correct? If so, we can close this issue.

**Comment by cheade** [comment]
@risanaka yep! That would be correct behavior for settings in an application. 

I'm finding that the Settings icon doesn't receive the focus bar indicator on the left nav. Is this a separate bug?

**Comment by risanaka** [comment]
@cheade should be tracked as a separate bug, although I'm unable to repro the focus bar indicator issue.
