### ISSUE TITLE
[BUG] AIWin draws highlighters after loading an events file

### ISSUE THREAD

**Issue by DaveTryon** [microsoft/accessibility-insights-windows#365]
Please check whether the bug has [already been filed](https://github.com/Microsoft/accessibility-insights-windows/issues).

**Describe the bug**
After loading an events file, AIWin draws highlighters on screen, even though there's nothing to highlight

**To Reproduce**
1. Start AIWin
2. Open the A11yEvents file (see attached zip file)
3. Click on the last loaded event
4. See the highlight being drawn. A different highlight gets drawn if you click on the 3rd event from the last

**Expected behavior**
The highlighters shouldn't be drawn (there's no snapshot and no running app)

**Actual behavior**
Highlighters get drawn to match the bounding rectangle of the element that received the event. These highlighters include the snapshot button if it's enabled. Clicking on the button makes the highlighter disappear until another element is clicked. All the while it says "Live mode", which seems wrong...

**Screenshots or .GIF**

![Demo](https://user-images.githubusercontent.com/45672944/57942701-07e6e000-7887-11e9-9707-b587855be053.gif)

**Desktop (please complete the following information):**
 - OS: Windows 1903
 - Accessibility Insights for Windows Version: 1.1.837.2 (also happens in canary builds)
 - Target Application: Notepad++
- Target Application Version: 7.6.6

**Additional context**
Sample file is in this zip file:
[EventRecord 05-17-19.zip](https://github.com/microsoft/accessibility-insights-windows/files/3192303/EventRecord.05-17-19.zip)

**Comment by jalkire** [comment]
@DaveTryon that the highlighter appears is as designed. We can change the design if we want, but it's not a bug. The fact that there is a snapshot button is a bug, though.

**Comment by DaveTryon** [comment]
@cheade, what makes the most sense from a design perspective? The highlighter experience (minus the snapshot button) might make more sense if we had a screenshot, but the file intentionally omits the screenshot. We'd love to get your thoughts on how to proceed from this. When this question came up a long time ago, the decision was to leave the highlighter, since it gave at least some sort of context of what window was receiving the events.

**Comment by cheade** [comment]
Without a screenshot, the highlighters provide not much context. They'll give you the name if you have that yellow label turned on, but without a screenshot or the app itself, I don't see a benefit to having the highlighters there. It also seems like it would get in the way of navigating anything else.

**Comment by DaveTryon** [comment]
After talking with jalkire, we decided to disable the highlighter by default, but to allow the user to enable it via the highlighter button (there are occasions where there is some benefit to having the highlight available if the user requests it)

**Comment by DaveTryon** [comment]
Confirmed fixed in build 1.1.883.1
