### ISSUE TITLE
[BUG] number of downloads is broken

### ISSUE THREAD

**Issue by ferBonnin** [microsoft/accessibility-insights-windows#367]
**Describe the bug**
number of downloads is in negative numbers

**Expected behavior**
real number of downloads

**Actual behavior**
have a negative number for 5/8 due to a release getting deleted

**Comment by ferBonnin** [comment]
@lisli1 talked about this with John and Karan. assigning it to John

**Comment by jalkire** [comment]
@ferBonnin You should now see the correct number on 5/8 and not see this issue again going forward. I have also updated our backend to store release channel alongside the download count going forward. Starting tomorrow, the number on the dashboard will refer to production downloads only (we don't have the breakdown for historical data). Let me know if there is a more useful way to display the information than the current table!
