### ISSUE TITLE
[BUG] When the Always on top setting is on, even if windows is locked, the application still stays active

### ISSUE THREAD

**Issue by piyushsaxena2910** [microsoft/accessibility-insights-windows#425]
**Describe the bug**
Installed the msi on my windows 10 machine. When I lock my machine, the "Accessibility Insights for Windows" always stays on top, even with the locked screen. This only happens when the "Always on top" setting is selected.

**To Reproduce**
1. Install the "Accessibility Insights for Windows" MSI
2. Go to settings and turn on setting "Always on top"
3. Lock windows by pressing Win+L
4. The "Accessibility Insights for Windows" still shows up and it fully accessible

**Expected behavior**
When I lock my machine, the application should not be available.

**Actual behavior**
When I lock my machine, the application is fully available and I can play around with it.

**Screenshots or .GIF**
![image](https://user-images.githubusercontent.com/26318272/60934407-ebf62e00-a27a-11e9-89fe-e20de7ad9e0e.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10 OS Build 17763.557]
 - Accessibility Insights for Windows Version: 1.1.883.1

**Comment by Sirisha-Kommushetty** [comment]
@piyushsaxena2910 - This is "By Design" with Always on Top. Please close the app or turn off the "always on top" setting before locking your device.

**Comment by piyushsaxena2910** [comment]
@Sirisha-Kommushetty Thank you for your response!
