### ISSUE TITLE
[BUG] v1.1.0933.01 release note has some errors

### ISSUE THREAD

**Issue by risanaka** [microsoft/accessibility-insights-windows#451]
Please check whether the bug has [already been filed](https://github.com/Microsoft/accessibility-insights-windows/issues).

**Describe the bug**

The [latest production release note](https://github.com/microsoft/accessibility-insights-windows/releases/tag/v1.1.0933.01) has a few errors.

**To Reproduce**
1. Go to [latest production release note](https://github.com/microsoft/accessibility-insights-windows/releases/tag/v1.1.0933.01).
1. See error.

**Expected behavior**

Wonderful release note describing the latest cool things in Accessibility Insights for Windows.

**Actual behavior**
What actually happened.

Release note describing the latest cool things in Accessibility Insights for Windows, but including the following errors:
- Wrong version: The title of the release note is "August 5, 2019 Insider Release" instead of "August 5, 2019 Production Release"
- Typographical error: Under "UIAccess Changes", "advanced" is misspelled as "advancecd".
- Odd line break: Under "UIAccess Changes", There's a line break between "To address this, we have disabled" and "UIAccess by default."

**Screenshots or .GIF**
![Release notes with the wrong version, typographical error, and odd line break outlined in red.](https://user-images.githubusercontent.com/144273/62500873-31841900-b79d-11e9-8552-2ffefa3a95d5.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1809] (Get the version by running `winver` from the command line)
 - Accessibility Insights for Windows Version:
 - Target Application: [e.g. Chrome, Wildlife Manager]
 - Target Application Version: [e.g. 22]

**Additional context**
Priority requested -

**Comment by DaveTryon** [comment]
Thanks for catching these 😸. Please close out when you get the chance.

**Comment by risanaka** [comment]
Thanks for the quick fix, @DaveTryon :)
