### ISSUE TITLE
[DOCS] "Entire app" behavior confusing when child popup window exceeds size of parent

### ISSUE THREAD

**Issue by karanbirsingh** [microsoft/accessibility-insights-windows#469]
**Describe the bug**
When an application has a blocking child dialog, hovering over the child dialog does not change the UIA selection to the child dialog. Instead, the parent window remains selected. This is the intended behavior of 'entire app', but can be confusing in this context. In order to select the child window, the user needs to switch the "What to select" combobox to "Element" mode. We might want to consider a docs ([fastpass](https://accessibilityinsights.io/docs/en/windows/getstarted/fastpass), [inspect](https://accessibilityinsights.io/docs/en/windows/getstarted/inspect)) or wording update.

![parent window selected when hovering over child window](https://user-images.githubusercontent.com/7775527/63202016-a1678e80-c03c-11e9-91a2-b146be2cedee.png)

**To Reproduce**

With an app like the following, hover over the child window in "Entire app" mode.

XAML:
```
<Window x:Class="WpfApp5.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfApp5"
        mc:Ignorable="d"
        Title="MainWindow" Height="400" Width="400">
    <Grid>
        <Button Name="Settings" Click="Settings_Click"/>
    </Grid>
</Window>
```

Codebehind:
```
using System.Windows;

namespace WpfApp
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }

        private void Settings_Click(object sender, RoutedEventArgs e)
        {
            Window w = new Window();
            w.Height = 800;
            w.Width = 800;
            w.Owner = this;
            w.WindowStartupLocation = WindowStartupLocation.CenterOwner;
            w.ShowDialog();
        }
    }
}
```

**Actual behavior**
Hovering over the child window selects the parent window in Accessibility Insights.

**Comment by DaveTryon** [comment]
Moving back to "needs investigation" as Fer's request
