### ISSUE TITLE
Update to version 2.9.4 of the Roslyn analyzers

### ISSUE THREAD

**Issue by DaveTryon** [microsoft/accessibility-insights-windows#476]
**Is your feature request related to a problem? Please describe.**
AIWin is using Roslyn version 2.9.2 in most places. The current version is Roslyn 2.9.4. Based on similar work in Axe.Windows, this will require touching a large number of files. Creating a feature request for tracking. Change should have no impact on application functionality

**Comment by ferBonnin** [comment]
Per conversation with Peter, changing this to a bug and adding engineering category

**Comment by peterdur** [comment]
Per conversation with Dave and Fer, tracking this as feature 1588220.

**Comment by DaveTryon** [comment]
This went in with #530. Closing.
