### ISSUE TITLE
[Feature Request] Consider newer version of ADO assemblies

### ISSUE THREAD

**Issue by DaveTryon** [microsoft/accessibility-insights-windows#477]
The ADO assemblies have been refreshed several times since our last update. We're using version 15.112.1, but the most recent version is 16.43.2. There are no known security issues at this time, so this is a non-urgent change that we may choose not to do.

**Comment by ferBonnin** [comment]
Per conversation with Peter, this is not big enough for a feature, changing the type and adding engineering category

**Comment by DaveTryon** [comment]
This is in Canary
