### ISSUE TITLE
[BUG] Add tag "Accessibility Insights for Windows" when user files a bug in ADO

### ISSUE THREAD

**Issue by ferBonnin** [microsoft/accessibility-insights-windows#520]
**Describe the bug**
When a user files a bug in Azure Devops using the tool we would like to have a tag of "Accessibility insights for Windows" 

**To Reproduce**
1. Go to Live Inspect
2. Scan an app with issues
3. file a bug in AzureDevOps from automated checks
4. tags are only A11y, Accessibility and WCAG or Section 508 rule.

**Expected behavior**
There is also a tag for "Accessibility Insights for Windows"

**Comment by karanbirsingh** [comment]
See canary - https://github.com/microsoft/accessibility-insights-windows/releases/download/v1.1.0978.01/AccessibilityInsights.msi

**Comment by ferBonnin** [comment]
looks good!
