### ISSUE TITLE
[Feature Request] support selenium xpath/XML mappings for winappdriver

### ISSUE THREAD

**Issue by fenchu** [microsoft/accessibility-insights-windows#535]
I'm using accessibilityInsights with winappdriver. winappdriver uses XML mapping via appium/selenium webdriver. Would it be possible for accInsights to support webdrivers XML scheme, it is almost the same, but some different naming and caps.

I like AccInsights to address items like  Xpath

```
<Button AcceleratorKey="" AccessKey="Alt+o" AutomationId="1" ClassName="Button" FrameworkId="Win32" HasKeyboardFocus="False" HelpText="" IsContentElement="True" IsControlElement="True" IsEnabled="True" IsKeyboardFocusable="True" IsOffscreen="False" IsPassword="False" IsRequiredForForm="False" ItemStatus="" ItemType="" LocalizedControlType="button" Name="Open" Orientation="None" ProcessId="12412" RuntimeId="42.526484" x="988" y="705" width="88" height="26" />
```
in Xpath this button can be addressed like:
```
 "//Button[@AccessKey='Alt+o']"
or the Fixed one "\\Window\\Window\\Button[@Name='Open']"
```
![accInsight-open](https://user-images.githubusercontent.com/11349883/64791659-52981080-d578-11e9-9ab8-6815a241fbff.jpg)

Often I need to look at the "\\Window\\Button[4]" would be nice if we can get this numbering, or connect to winappdriver for this data. you get the entire XML schema for the current page by doing `driver.page_source()`

**Comment by adarshrema** [comment]
Hello @fenchu,
Thank you for your interest in Accessibility Insights and this feature request. This is a great suggestion, but not a priority for the team at this point.

We will keep this active and add it to our backlog. If you or someone in the community wants to help, please feel free to work on this. We would be happy to provide guidance.

**Comment by adarshrema** [comment]
Hello @fenchu, this issue has been open for a while with no feedback or interest from the community. This is not a priority for our team and we think it might be a good idea to reach out to the [WinAppDriver](https://github.com/microsoft/WinAppDriver/blob/master/Docs/AuthoringTestScripts.md#supported-locators-to-find-ui-elements) team instead.

**Comment by fenchu** [comment]
I think the winappdriver project is dead: https://github.com/microsoft/WinAppDriver/issues/1103.
Xml/xpath is the de-facto standard in automation used by all browsers for years.

**Comment by adarshrema** [comment]
@fenchu, is this something you would be interested in contributing to?
