### ISSUE TITLE
Implement a channel switch progress indicator

### ISSUE THREAD

**Issue by Shobhit1** [microsoft/accessibility-insights-windows#542]
**Is your feature request related to a problem? Please describe.**
So, if I am on a machine with slow internet connection or a VM (which generally has a slower internet connection then the base machine); changing channels from Production to Canary or from canary back to production take a long time. Also, if I open the accessibility-insights-windows application in between the process, the app seems to work in its last state.

**Describe the solution you'd like**
- a progress indicator on how the channel switching is happening.
- if the application in its previous channel is being uninstalled; then I shouldn't be able to use the application until I have switched channels.

**Comment by Sirisha-Kommushetty** [comment]
Thanks for filing the issue. We're looking into how this would apply for the long term.

**Comment by adarshrema** [comment]
Hello @shobhit1,
Thank you for your interest in Accessibility Insights and this feature request. This is great feedback and needs more investigation by the team.

We will keep this active and will update this here when we know more.

**Comment by adarshrema** [comment]
Needs design input. Keeping this active to prioritize against other work items.

**Comment by DaveTryon** [comment]
A very simple implementation of this would be cheap and a significant improvement over what we have (which is no feedback at all)

**Comment by DaveTryon** [comment]
We want to pursue this, pending an approved design
