### ISSUE TITLE
[BUG] File issue button link is cut off

### ISSUE THREAD

**Issue by cheade** [microsoft/accessibility-insights-windows#544]
**Describe the bug**
![image](https://user-images.githubusercontent.com/40274682/64978630-d6991380-d86a-11e9-8b7a-08be62459c31.png)

See "File issue" button link is cut off. The issue column is unable to be adjusted to accommodate full width of "file issue".

**To Reproduce**
1. Open Accessibility Insights
2. Run automated checks on an app that will produce Accessibility errors
3. View any error result in the UIA tree view.
4. "Test results" box contains the cut-off error, under the "Issue" column

**Expected behavior**
Issue column should be default wide enough to contain all of "File issue" without getting cut off. 

**Actual behavior**
"File issue" is cut off, and the issue column cannot be adjusted. 

**Desktop (please complete the following information):**
 - OS: Windows 10 version 1809 (OS Build 17763.437)
 - Accessibility Insights for Windows Version: Prerelease Build (1.1.988.1)
 - Target Application: Wildlife manager
 - Target Application Version: N/A

**Additional context**
Priority requested - low

**Comment by jalkire** [comment]
Context: this is happening because the width is a hardcoded value (due to WPF ListView behavior not lining up with what we wanted) set based on our original font size, which is no longer the default font size. It is not cut off when you set your font to small in settings: 
![image](https://user-images.githubusercontent.com/4615491/64983852-5d9fb900-d876-11e9-95d7-8afcb76c5b4a.png)

This easy to fix.

**Comment by DaveTryon** [comment]
@cheade, the fix for this will be in build 1.1.0990.01. This build should be in the Canary channel on 9/18. Please regress it against an appropriate build, then close it out. Thanks!

**Comment by DaveTryon** [comment]
@cheade, Build 1.1.990.1 (which contains this fix) just release to the Production channel. Please close at your convenience

**Comment by cheade** [comment]
Thanks, team!
