### ISSUE TITLE
[BUG] Application window always opens maximized

### ISSUE THREAD

**Issue by LiLoDavis** [microsoft/accessibility-insights-windows#563]
**Describe the bug**
On launch, the main application window always opens maximized, and the restore down button always shrinks the window to the same default size. As a consequence, I always have to fiddle with the window to get it to my preferred size and position.

**To Reproduce**
1. Open AI-Win.
2. Use the main application window's restore down button.
3. Manually adjust the window's size and screen position. 
3. Close the app.
4. Re-open the app.

**Expected behavior**
The main application window re-opens to its most recent size and screen position.

**Actual behavior**
The main application window opens maximized, and restore down does not restore to the most recent size/position.

**Screenshots or .GIF**

**Desktop (please complete the following information):**
 - OS: Windows 1903
 - Accessibility Insights for Windows Version: Prelease Build (1.1.993.1) 
 - Target Application: N/A
 - Target Application Version: N/A

**Comment by devaradhanm** [comment]
We should be saving the window status (Properties.Settings.Default.Save) of the application when on close event is fired.

**Comment by DaveTryon** [comment]
It looks like layout.json isn't being updated on app shutdown. Investigating.

**Comment by DaveTryon** [comment]
This has been merged to master. It will be in builds 1.1.993.1 or greater (should appear in the canary channel on 9/24/19)

**Comment by DaveTryon** [comment]
@LiLoDavis, please regress this against the current canary build. Thanks!

**Comment by LiLoDavis** [comment]
Looks good to me.
