### ISSUE TITLE
[BUG] There is no user feedback indicating that a non-admin AI4Win cannot scan an admin process

### ISSUE THREAD

**Issue by dbjorge** [microsoft/accessibility-insights-windows#584]
**Describe the bug**

Since removing UIAccess-by-default from Accessibility Insights for Windows, we've received user reports of confusing behavior when trying to use a (non-elevated) Accessibility Insights process to scan elevated processes.

It's by design that you can't scan a higher-privileged process from a lower-privileged process, but the behavior in this state is currently confusing; in some cases, Accessibility Insights silently ignores the elevated app, and in other cases, it can "see" the UI elements for the elevated app's window chrome but just shows it as containing a few empty panes. There's no indication that there's an elevation issue blocking the proper scanning; to a user, it just looks like the tool isn't working.

We should add some sort of UI feedback for a user in this state explaining what's happening and what they have to do to solve it (launch Accessibility Insights as an Administrator)

**To Reproduce**
1. Open any elevated process (eg, open Device Manager)
2. Open Accessibility Insights for Windows (not as an administrator)
3. Go to "Live Inspect"
4. Mouse over the elevated process

**Expected behavior**
AI4Win shows some sort of indication that it can't scan that process because it is elevated, with instructions to launch AI4Win as administrator to scan that process

**Actual behavior**
AI4Win silently ignores the elevated process

**Desktop (please complete the following information):**
 - OS: Windows 1903 (18362.356)
 - Accessibility Insights for Windows Version: v1.1.0990.01
 - Target Application: Any elevated application

**Comment by ferBonnin** [comment]
Per conversation with Peter we should do somethign about this. 
Documentation in this case is probably not the way to go, having something in the UI will be more helpful.

Requires additional investigation from PM and Design team

**Comment by DaveTryon** [comment]
@ferBonnin, there may be a way to do this. Looking at the telemetry, UIA throws an UnauthorizedAccessException when we attempt to interact with windows where permissions are denied.  We are unable to obtain any information about these elements (not even their sizes), but we could potentially display some AIWin UX element in response to receiving these Exceptions. That UX element could then be hidden when we successfully receive data. There's a corner case where this would break, but it seems unlikely. The case occurs when BOTH of the following are true:
- The UIA tree (from the top level down) includes windows from different processes
- The different processes are running at different elevation states

**Comment by ferBonnin** [comment]
Thanks for the investigation and suggestion Dave. This would probably need some design work for the message ( I don't recall us showing any other message like this in the tool). Once we have that, would this be feature size or bug size?

**Comment by DaveTryon** [comment]
@ferBonnin. This is larger than bug size. The Exceptions are currently being caught and suppressed inside Axe.Windows. We'd need to decide how to expose those Exceptions to AIWin, update Axe.Windows, publish a new NuGet package, consume the new package in AIWin, then integrate the notifications into the UX.

**Comment by ferBonnin** [comment]
Got it, thanks Dave. changing this to feature request, we will prioritize this against other feature requests
