### ISSUE TITLE
[General Question] Which rules of WCAG2.1 support in Accessibility Insights for Windows for Windows Forms Page test?

### ISSUE THREAD

**Issue by v-lga-hub** [microsoft/accessibility-insights-windows#607]
I know Accessibility Insights for Web has full WCAG2.1 coverage in the assessment experience. but i would like to know which rules of WCAG2.1 support in Accessibility Insights for Windows, especially for windows forms page?

**Comment by DaveTryon** [comment]
@ferBonnin, how are we handling documentation issues? This is more of an Axe.Windows question, but www.accessibilityinsights.io doesn't talk much about Axe.Windows...

**Comment by ferBonnin** [comment]
Hi @v-lga-hub we are in the process of creating a list of rules with their mapping in our rules engine repository: [axe-windows](https://github.com/Microsoft/axe-windows). We are tracking this in [Issue #164](https://github.com/microsoft/axe-windows/issues/164)

**Comment by ferBonnin** [comment]
Hi @v-lga-hub we have now a document with the [rules descriptions](https://github.com/microsoft/axe-windows/blob/master/docs/RulesDescription.md). Please let us know if this solves your question

**Comment by v-lga-hub** [comment]
I saw the document, it is helpful. thanks a lot.
