### ISSUE TITLE
[BUG] Crash when using keyboard to navigate UIA tree past last sibling

### ISSUE THREAD

**Issue by jalkire** [microsoft/accessibility-insights-windows#619]
**Describe the bug**
When using the ai-win hierarchy navigation hotkeys, if you attempt to navigate in an invalid way (ex to the next sibling when you are already on the last sibling, or to the first child when there is no child), ai-win crashes.

**To Reproduce**
1. Start ai-win and inspect an element
2. Use the next sibling hotkey (Ctrl + Shift + F8 by default) to navigate to the last sibling
3. Attempt to use hotkey again to navigate past the last sibling
4. Crash

**Expected behavior**
Either nothing should happen or it should loop back to the first sibling

**Actual behavior**
ai-win crashes.

Note that an analogous problem occurs with the navigate to previous sibling and first/last child element hotkeys, but not with the parent element hotkey.

**Desktop (please complete the following information):**
 - OS: Windows 10 1909
 - Accessibility Insights for Windows Version: 1.1.990.1
 - Target Application: any

**Comment by ferBonnin** [comment]
Per conversation with Peter, lets fix this.

**Comment by ferBonnin** [comment]
@jalkire per conversation with Peter, could you please take a look at this?

**Comment by DaveTryon** [comment]
@jalkire, we picked up the fixed version of Axe.Windows in #668, so this should now be resolved. Can you please regress/close? Thanks!

**Comment by jalkire** [comment]
Verified in canary.
