### ISSUE TITLE
UX Button behavior [BUG] 

### ISSUE THREAD

**Issue by cheade** [microsoft/accessibility-insights-windows#643]
**Describe the bug**
Button UX behavior and styling in the issue filing for Azure Boards section.

**To Reproduce**
1. Run automated checks on an app with errors
2. Click file issue (make sure you don't have a service connected, this should be a first-time setup)
3. Button to connect Azure Boards account is blue before any text has been entered.

**Expected behavior**
Azure Boards Issue filing setup:
Button should be disabled styling until a user enters in text to submit.

**Screenshots or .GIF**
Azure Boards:
![image](https://user-images.githubusercontent.com/40274682/69367074-692fa780-0c4c-11ea-8b96-db3f1fb4f911.png)

Desktop (please complete the following information):

OS: Windows 10 version 1809 (OS Build 17763.437)
Accessibility Insights for Windows Version: Prerelease Build (1.1.988.1)
Target Application: Wildlife manager
Target Application Version: N/A

**Additional context**
Priority requested - low
[Link to Figma file](https://www.figma.com/file/MxXdGGjWOjE7KaL3rfJNed5C/Accessibility-Insights-for-Desktop?node-id=442%3A3)

**Comment by DaveTryon** [comment]
@cheade, this is fixed in the most recent canary build. Please confirm, then either close the issue or assign it back to me with details on what is not yet correct. Thanks!

**Comment by cheade** [comment]
This has been resolved, thank you, @DaveTryon!
