### ISSUE TITLE
[BUG] image/text/text nodes remaining in UIA tree when not visible in connection control

### ISSUE THREAD

**Issue by karanbirsingh** [microsoft/accessibility-insights-windows#644]
Please check whether the bug has [already been filed](https://github.com/Microsoft/accessibility-insights-windows/issues).

**Describe the bug**
In the issue filing configuration page, the UIA tree shows three nodes that are not visible on the screen: image "", text "", text "". It's likely that these come from the old avatar, email, and display name. These are no longer in the UI, afaik. We should remove the UIA tree elements, as their presence leads to a null bounding rectangle while they're onscreen (axe-windows issue).

**To Reproduce**
[TestResults 11-21-19.zip](https://github.com/microsoft/accessibility-insights-windows/files/3876650/TestResults.11-21-19.zip)

**Comment by DaveTryon** [comment]
@karanbirsingh, please regress against build 1.1.1062.01, then either close or assign back to me, as appropriate. Thanks!

**Comment by karanbirsingh** [comment]
Looks great
