### ISSUE TITLE
[General Question] - Command line support?

### ISSUE THREAD

**Issue by AdamYoblick** [microsoft/accessibility-insights-windows#666]
Hello,

The winforms team is interested in running the accessibility insights tool as part of our CI build. I did some very brief initial investigation, but I didn't see any way to run accessibility tests from a command line.

Is there any advice around this? Would using axe-windows with a custom tool that navigates through our UI be the right approach here?

Thank you!
-Adam

**Comment by haonliu** [comment]
Hi @AdamYoblick,

We would recommend using WinAppDriver and Axe.Windows for running automated accessibility tests. You can see how the automated accessibility tests are run for AI-Win in the UITest project of AI-Win [here](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Faccessibility-insights-windows%2Ftree%2Fmaster%2Fsrc%2FUITests&data=02%7C01%7CHaonan.Liu%40microsoft.com%7C085cfadfc4704a0a336b08d77a7f352e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637112559075438922&sdata=AkHkySy8SDfca5c9tjfMs1sYBtLGpvruwqnEf7KeqJc%3D&reserved=0). The ReadMe file may be of particular interest.

**Comment by AdamYoblick** [comment]
Thank you @haonliu , I'll take a look 😄

**Comment by adarshrema** [comment]
Hello @AdamYoblick, can you please go ahead and close this if your question was answered satisfactorily? Thank you!
