### ISSUE TITLE
[BUG] Color contrast value background does not respect the active high contrast theme

### ISSUE THREAD

**Issue by guybark** [microsoft/accessibility-insights-windows#675]
Please check whether the bug has [already been filed](https://github.com/Microsoft/accessibility-insights-windows/issues).

**Describe the bug**
The area showing the color contrast value in AIWin has a background of gray, instead of a background color from the active high contrast theme. As such, the customer may be blocked from accessing the contrast information.

**To Reproduce**
1. Turn on the "High Contrast Black" theme.
2. Use AIWin to determine the color contrast value of any UI.
3. View the area in AIWin which is showing the color contrast value.

**Expected behavior**
The text shown in the area should have a foreground and background color that matches the related colors from the active high contrast theme. That is, white text on black background.

**Actual behavior**
The text appears as white-on-gray.

**Screenshots or .GIF**
![AIWin_HighContrast](https://user-images.githubusercontent.com/14315611/71294104-5502c700-232c-11ea-8bc8-16bf92f7721c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1903
 - Accessibility Insights for Windows Version: 1.1.1072.01
 - Target Application: Anything.
 - Target Application Version: Anything.

**Additional context**

Priority requested -

**Comment by adarshrema** [comment]
Hello @guybark, thank you for using Accessibility Insights for Windows and for reporting this issue. This has been marked ready for work and added to our backlog to be fixed.

**Comment by jalkire** [comment]
Fix is in the latest canary release.

**Comment by ferBonnin** [comment]
Hi @guybark , the fix for this bug is now available in the Canary release. You can change your release to verify this change by going to the Setting options and changing the Channel in Accessibility Insights for Windows.

Please let us know if this fixes the issue!

**Comment by DaveTryon** [comment]
@guybark, this is now live in the Production release
