### ISSUE TITLE
[Feature Request] Better visualization and navigation of a UIA tree

### ISSUE THREAD

**Issue by FalseLobster** [microsoft/accessibility-insights-windows#685]
**Is your feature request related to a problem? Please describe.**
I find it very hard to navigate the UIA tree of an application using the Inspect feature.  I wish there was a way to see the ENTIRE tree for a UIA node--- all the descendants, siblings of those descendants, etc...

Instead the UIA tree is treated almost like a call stack, where Accessibility Insights shows a given node and the entire parent chain.  No siblings are ever shown.

**Describe the solution you'd like**
Ideally I could pick a node and say "Show me all descendants" and it'd do so in a recursive fashion.  I could then expand collapse the Inspect tree and navigate it like any other tree view. (e.g. Using Right/Left arrow to expand/collapse nodes and up/down to go between levels)

**Describe alternatives you've considered**
I think the only alternative is to use the Ctrl+Shift+F7, Ctrl+Shift+F9, etc... shortcuts, but I find these cumbersome and recently seems to have ceased navigating to nodes that have been "scoped out" by the inspect view.

**Additional context**
I'm an engineer working on Office's Win32 applications, primarily the UI platform.  I do a lot of accessibility work.  This feature is a bit of a deal breaker for me and I almost always find myself abandoning Accessibility Insights in favor of the old inspect executable that ships with the Windows SDK.

**Comment by adarshrema** [comment]
Hello @FalseLobster, thank you for using Accessibility Insights for Windows and this feature request. I am closing this in favor of a duplicate request we are tracking as [issue #333](https://github.com/microsoft/accessibility-insights-windows/issues/333). Please follow that issue for updates. I will also add your +1 to the request there.
