### ISSUE TITLE
[BUG] "Listen to all events" checkbox excludes property-based events even if explicitly selected

### ISSUE THREAD

**Issue by WilliamXieMSFT** [microsoft/accessibility-insights-windows#694]
**Describe the bug**
Live Inspecting a CheckBox control does not report ToggleStatePropertyChanged when it is checked/unchecked.

**To Reproduce**
1. Create a simple WPF app with CheckBox: (xaml snippet)
`<CheckBox x:Name="MyCheckBox"
                  Content="Hello World"
            />`
2. Run the WPF app and Live Inspect the CheckBox:
![image](https://user-images.githubusercontent.com/29215642/73385457-0bd65900-4282-11ea-904d-8865bec2cc6f.png)

![image](https://user-images.githubusercontent.com/29215642/73385515-2577a080-4282-11ea-8bdf-192988b8cdcf.png)

3. Select "Listen to All Events" and focus on CheckBox. 
4. In Configuration, enable "TogglePattern.ToggleState" under My Events > Properties
![image](https://user-images.githubusercontent.com/29215642/73386147-37a60e80-4283-11ea-9c60-c693f8d5a300.png)

5. Hit "Space" key to toggle CheckBox on and off.

**Expected behavior**
ToggleStatePropertyChanged event should be reported when the CheckBox is checked/unchecked. UIA clients like Narrator and NVDA report "Checked" and "Unchecked" when this occurs.

NarratorBuddy output:
![image](https://user-images.githubusercontent.com/29215642/73385702-77202b00-4282-11ea-9ca9-17e3ebcb2cf2.png)

NVDA output:
![image](https://user-images.githubusercontent.com/29215642/73385869-c0707a80-4282-11ea-9f02-a57829a1c75d.png)

**Actual behavior**
Live Inspect events only record AutomationFocusChanged event but no changes to Property.

**Screenshots or .GIF**

**Desktop (please complete the following information):**
 - OS: Windows 10 v1903 (Build 18362.628)
 - Accessibility Insights for Windows Version: 1.1.1107.1
 - Target Application: .NET Framework 4.8 WPF App

**Additional context**
N/A

**Comment by karanbirsingh** [comment]
Hi @WilliamXieMSFT - thanks for the detailed report. It seems I can reproduce this if "Listen to all events" is checked. When I leave "Listen to all events" unchecked, the property events show up properly. Can you try that to see if it unblocks you?

![screenshot of event recording](https://user-images.githubusercontent.com/7775527/73563088-60f4a500-4411-11ea-88d0-e4dd86b8a256.png)

**Comment by WilliamXieMSFT** [comment]
@karanbirsingh Hi, thank you for your reply.

I can confirm that if I set My Events > Properties > TogglePattern.ToggleState only (without Listen to All Events), I do get the AutomationPropertyChanged event:
![image](https://user-images.githubusercontent.com/29215642/73567440-445d6a80-441b-11ea-8888-5408dcd2ca84.png)

And I can confirm that checking "Listen to All Events" causes the issue:
![image](https://user-images.githubusercontent.com/29215642/73567535-68b94700-441b-11ea-817c-d20dcc5db2ba.png)

I am unblocked with the workaround. Thanks!

**Comment by karanbirsingh** [comment]
Sounds good - I have updated the issue title so we can track this on our backlog. Thanks for the bug report!

**Comment by karanbirsingh** [comment]
@jalkire has found that the "Changes" event causes this issue - removing the "Changes" event leads property events to show up again

**Comment by RobGallo** [comment]
It turns out the problem here is in either UIA or the provider interfaces implemented by WPF. If one adds a listener for "Changes" events before listening for property change events, the problem occurs. If the order is reversed, the problem does not occur. However, because we have no evidence that reversing the order will not cause a similar, as yet unknown problem, we are not reversing the call order at this time.

We are submitting a bug to the UIA team to investigate this issue.

**Comment by WilliamXieMSFT** [comment]
Confirmed the bug is fixed in the canary build. Thanks!

![image](https://user-images.githubusercontent.com/29215642/80542494-ebda3280-8961-11ea-9f4e-e04314719728.png)
