### ISSUE TITLE
Color contrast analyzer could suggest alternative colors

### ISSUE THREAD

**Issue by Erarndt** [microsoft/accessibility-insights-windows#695]
**Is your feature request related to a problem? Please describe.**
Color contrast analyzer does a great job of discovering issues, and I think it could go one step further and offer suggestions on what specific colors to use to resolve the issue.

**Describe the solution you'd like**
There are tools available that will suggest colors that are close to the initial colors. It would be great if that functionality was integrated into the tool.

**Describe alternatives you've considered**
There are external tools that provide this already. Here's an example of one https://contrast-finder.tanaguru.com/

**Additional context**

**Comment by adarshrema** [comment]
Hello @Erarndt, thank you for using Accessibility Insights for Windows and for submitting this feature request. Have you tried using the Color Picker box to select foreground and background colors manually?

With current priorities, we think the ability to select a foreground and background color manually to re-run a test indirectly addresses the lack of auto suggestion.

**Comment by Erarndt** [comment]
Hi @adarshrema. The color picker is a very useful tool and I use that in combination with the external tool that I linked to in my initial post to help me resolve color contrast issues. How nice would it be to have a similar tool integrated into the product that would suggest similar colors to use?

**Comment by adarshrema** [comment]
Thank you for that feedback @Erarndt. We are unable to pick this up given our current priorities. I have added help wanted label to invite community contributions. Is this something you would like to work on and contribute?
