### ISSUE TITLE
Provide full support for testing Electron based applications

### ISSUE THREAD

**Issue by kenvanhyning** [microsoft/accessibility-insights-windows#717]
Azure Data Studio is based on VS Code and adds quite a rich set of graphical UI experiences.  Currently we do not use AI due to its lack of full support for testing Electron based applications.  

We would like to be able to push more issues to the developer rather than finding issues during accessibility testing.

**Comment by adarshrema** [comment]
Hello @kenvanhyning, thank you for your interest in Accessibility Insights and this feature request. This is definitely on our radar and we will keep this open to assess community interest, and to discuss specifics when we are ready to dig deeper.

**Comment by Hardhik** [comment]
I also notice that the Accessibility Insights for Windows app causes electron app to crash. This is noticed while trying to test the "Test Runner" from Azure DevOps.

**Comment by leonardder** [comment]
I'd say as Electron applications are web based, Accessibility Insights for web would be a better choice. Wouldn't it be possible to run Data Studio in Chrome/Edge, just like VS Code, and investigate that way?

**Comment by codeofdusk** [comment]
I agree. It looks like Electron [supports a subset of the Chrome Extension API](https://www.electronjs.org/docs/api/extensions), although I don't know if it's sufficient for Accessibility Insights (and I imagine adding the extension to a project could be streamlined).
