### ISSUE TITLE
[Feature Request] The ItemContainer pattern's FindItemByProperty UI should account for the starting element parameter

### ISSUE THREAD

**Issue by RobGallo** [microsoft/accessibility-insights-windows#745]
**Is your feature request related to a problem? Please describe.**

When an element supporting the ItemContainer pattern is inspected, and when the FindItemByProperty method is invoked from the pattern's actions dialog, it is not possible to specify the starting element for the search.

**Describe the solution you'd like**

Either 

A. AI-Win allows the user to select the starting element for the search along with the property id and property value.
B. AI-Win finds all the matching elements. (Note: it may be wise to limit the number of found elements in case it's large.)

**Additional context**

This issue is related to #744 , where steps to repro can be found.

**Comment by adarshrema** [comment]
Fixed in PR [#751](https://github.com/microsoft/accessibility-insights-windows/pull/751)

**Comment by DaveTryon** [comment]
The comment that this was fixed in PR #751 is incorrect. PR #751 fixed issue #744, but this issue represents a change in the UI and is still open
