### ISSUE TITLE
[Feature Request] Persist my UIA event selection during a AIWin session 

### ISSUE THREAD

**Issue by guybark** [microsoft/accessibility-insights-windows#762]
Say I make a careful custom selection for UIA event reporting, and then get a bunch of events reported by AIWin as desired. I then stop event reporting to do a bit of live inspection of the UI. I then return to the event selection UI and have to make my careful selection again. Could AIWin remember my previous choice, at least during a single session?

**Comment by jalkire** [comment]
Hi @guybark, we just wanted to confirm that you are aware of the ability to save a custom list of events and properties to listen to with the "My Events" section of the event configuration. The list of events you select with My Events will persist across different event recording sessions, unlike your checkbox selections. Does this feature meet your needs for event selection persistence, or is it missing something important?
