### ISSUE TITLE
WCAG 2.1: Reflow - Breadcrumb information is truncated in 'UI automation tree results view'' at 200% zoom 

### ISSUE THREAD

**Issue by iamrafan** [microsoft/accessibility-insights-windows#768]
**Describe the bug**
Breadcrumb information is truncated in 'UI automation tree results view'' when the pane splitter is in default position (Considering the splitter position in Automated Checks as default)

**To Reproduce**
Adjust the following display settings in Windows :
- Display resolution to ```1280 * 1024```
- Scaling size to ```200%```

1.  Launch AI-Windows
2. Run test on any app
3. Navigate to "View results in UI Automation Tree"
4. Set the pane splitter to a similar position as in automated checks
5. Observe that the complete breadcrumb information is not available

**Expected behavior**
Breadcrumb  information should not be hidden and be made available 

**Actual behavior**
Breadcrumb content  is hidden

**Screenshots or .GIF**
![4](https://user-images.githubusercontent.com/22068434/79999052-50802380-8470-11ea-9c8b-c1b4948f835c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise, Version1903
 - Accessibility Insights for Windows Version: Production Release: v1.1.1198.01

**Comment by adarshrema** [comment]
From internal testing for accessibility. To be combined with results from planned HC testing.
