### ISSUE TITLE
WCAG 2.1: Reflow - Horizontal scrolling is applied on the entire right pane instead of just the data table in 'tab stops'

### ISSUE THREAD

**Issue by iamrafan** [microsoft/accessibility-insights-windows#772]
**Describe the bug**
Accessing the complete data table requires horizontal scrolling which scrolls the entire right pane instead of just the data table. 

**To Reproduce**
Adjust the following display settings in Windows :
- Display resolution to ```1280 * 1024```
- Scaling size to ```200%```

1. Launch AI-Windows
2. Navigate to Tests->Tabstops
3. Observe that horizontal scrolling moves the entire right pane,

**Expected behavior**
Horizontal scrolling should scroll only the data table only, instead of the entire right pane

**Actual behavior**
Horizontal scrolling scrolls the entire right pane

**Screenshots or .GIF**
![Tabstops results table](https://user-images.githubusercontent.com/22068434/80004558-53324700-8477-11ea-811f-10eafd638a0b.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise, Version1903
 - Accessibility Insights for Windows Version: Production Release: v1.1.1198.01

**Comment by adarshrema** [comment]
From internal testing for accessibility. To be combined with results from planned HC testing.
