### ISSUE TITLE
WCAG 2.1: Reflow - Actions' pop up windows too large and partially off screen on launch at 200% zoom

### ISSUE THREAD

**Issue by iamrafan** [microsoft/accessibility-insights-windows#773]
**To Reproduce**
Adjust the following display settings in Windows :
- Display resolution to ```1280 * 1024```
- Scaling size to ```200%```

1. Launch AI-Windows
2. Live inspect any Windows app
3. Switch back to AI-Windows, '
4. Make sure Details' tab is open in the right pane
5. In patterns section, click on ```actions``` button related to any specific pattern
6. Observe the pop ups are slightly off screen

**Expected behavior**
Pop up and its related controls completely visible inside the viewport

**Actual behavior**
Action pop ups are partially hidden

**Screenshots or .GIF**
Two examples:
- LegacyIAccessiblePattern
![Screenshot (310)](https://user-images.githubusercontent.com/22068434/80008413-94792580-847c-11ea-96f0-e40c2043f3a3.png)

-TextPattern
![Screenshot (319)](https://user-images.githubusercontent.com/22068434/80008468-aa86e600-847c-11ea-86f4-6f5991118997.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise, Version1903
 - Accessibility Insights for Windows Version: Production Release: v1.1.1198.01

**Comment by adarshrema** [comment]
From internal testing for accessibility. To be combined with results from planned HC testing.
