### ISSUE TITLE
[BUG] "Getting started" dialog is too wide and partially off screen at 200% zoom

### ISSUE THREAD

**Issue by iamrafan** [microsoft/accessibility-insights-windows#787]
**Describe the bug**
As per our discussion, we need to reduce the width of the "welcome dialog" to make the grayed out area visible on all four sides and make it look like a pop up

**To Reproduce**
Adjust the following display settings in Windows :
- Display resolution to ```1280 * 1024```
- Scaling size to ```200%```

1. Make sure to clear the configurations(if any) to get to "Getting started" experience
2. Launch AI-Windows
3. Observe that the "Getting started"dialog is too wide and the grayed out area is not visible on left and right sides

**Expected behavior**
Reduce the width of the "Getting started" dialog on launch and make sure it is evident to the user that this is a pop up

**Actual behavior**
The dialog is too wide.

**Screenshots or .GIF**
![Screenshot (307)](https://user-images.githubusercontent.com/22068434/81616040-a07b4780-9397-11ea-9458-4f0988171a98.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise, Version1903
 - Accessibility Insights for Windows Version: Production Release: v1.1.1198.01

**Comment by DaveTryon** [comment]
This is fixed in the current canary build (see https://github.com/microsoft/accessibility-insights-windows/releases/tag/v1.1.1230.01)
