### ISSUE TITLE
Persist resized Property and Value column width within and across sessions[Feature Request]

### ISSUE THREAD

**Issue by adarshrema** [microsoft/accessibility-insights-windows#797]
Based on conversation with @guybark during office hours on 5/18/2020:
When I am using a single monitor and have 200% zoom with Accessibility Insights for Windows and another app almost side by side I need to resize the columns on properties and values every time I select a new element. Can you please make it remember my resize selection?

Repro steps
1. Adjust the following display settings in Windows:
* Screen resolution: 2256x1504. (This is the recommended resolution for my Surface Laptop 3.)
* Scaling: 200%. (The recommended scaling for my device is 150%.)
2. Launch AI-Win and run test on any app
3. Navigate to Details tab within LiveInspect
4. Adjust Property or Value column width to make sure that text is not truncated and visible on screen
5. Select a different element to Inspect on the UIA tree
6. The column width returns to default and does not persist the change made in step 4

Given the number of times I restart AIWin, it would be helpful for the column widths to persist across sessions.

Note: I do not maximize AI-Win window so I can see it right next to my target app window. I do not change the width of the left navigation pane as I often have UIA tree 7-8 level deep.

OS version: Windows 10 Version 1909, (OS Build 18363.836)
AI-Win version: 1.1.1198.1

**Comment by adarshrema** [comment]
Hello @guybark, this issue was triaged by our team and has been added to the backlog to be prioritized against other work items.

**Comment by juchampa** [comment]
This item is being closed due to insufficient interest from other users.
