### ISSUE TITLE
[BUG] AIWin doesn't report a Win32/WinForms ListView's support for UIA Grid and Table patterns 

### ISSUE THREAD

**Issue by guybark** [microsoft/accessibility-insights-windows#811]
**Describe the bug**
AIWin doesn't report a Win32/WinForms ListView's support for UIA Grid and Table patterns 

**To Reproduce**
1. Either create a WinForms app using .NET Framework 4.8 and add a multicolumn ListView with items, subitems, and column headers, or invoke the Properties dialog of an icon on your Windows desktop and move to the Win32 list in the Details tab of that dialog.
2. Use AIWin to examine the list element and the text elements representing the subitems in the list.

**Expected behavior**
If the list and subitems support the UIA Grid/Table patterns and GridItem/TableItem patterns respectively, then AIWin should report it. 

**Actual behavior**
AIWin reports that support for the UIA Grid/Table patterns and GridItem/TableItem patterns is missing. 

It seems that the support the UIA Grid/Table patterns and GridItem/TableItem patterns is available, as the support is reported by using the Inspect SDK tool, and Narrator's table-related commands work at the ListView.

**Desktop (please complete the following information):**
 - OS: Windows 10 1909, OS Build 18363.836.
 - Accessibility Insights for Windows Version: 1.1.1248.1
 - Target Application: Win32 and WinForms ListViews.
 
**Additional context**
I can't really use AIWin for bug investigations involving lists at this point.

**Comment by RobGallo** [comment]
Addressed in axe-windows PR [#409](https://github.com/microsoft/axe-windows/pull/409)

**Comment by ferBonnin** [comment]
@RobGallo can we mark this as resolve? what is needed to validate this in Accessibility Insights for Windows - Canary?

**Comment by RobGallo** [comment]
@ferBonnin  We need to release a new version of axe-windows and consume it in AI-Win. We will discuss whether or not to create a release of axe-windows today.

**Comment by DaveTryon** [comment]
Hi, @guybark! This has been released to production at https://github.com/microsoft/accessibility-insights-windows/releases/tag/v1.1.1334.02. Please regress as your convenience. Thanks!

**Comment by guybark** [comment]
I've verified using AIWin 1.1.1334.2 that AIWin now reports that the text elements in the list in the Win32 Properties dlg support the GridItem and TableItem patterns. Thanks for making the change.
