### ISSUE TITLE
[BUG] Unable to view the UIA tree once the pane width has been reduced to zero 

### ISSUE THREAD

**Issue by guybark** [microsoft/accessibility-insights-windows#814]
1. Run the AIWin tool and point it to some UI element to populate AIWin's UIA tree and details panes.
2. Using the mouse, reduce the width of the pane containing the UIA tree to zero. I did this deliberately in order to be able to generate a screenshot on a fairly small screen, where I needed to capture some target app's UI and AIWin's Details pane, but not the UIA tree. When repro'ing this, make sure, the pane width is reduced to zero, not just close to zero.
3. Close AIWin.
4. Open AIWin and try to get the UIA tree pane back with the mouse.

**Expected behavior**
Somehow the mouse can be used to get the UIA tree pane back.

**Actual behavior**
The double-header resizing arrow doesn't appear when trying to resize the now-invisible UIA tree pane, so there seems no way to get the pane back. Uninstalling and re-installing AIWin didn't help. In the end I searched the AIWin code to find where user settings are stored, which led me to the local Layout.json file, and I deleted it. When I next ran AIWin, its UIA had reverted to its default values.

The screenshot below shows the AIWin tool with the UIA tree pane reduced to zero-width.

**Screenshots or .GIF**
![image](https://user-images.githubusercontent.com/14315611/84068966-9fc9d700-a97e-11ea-8dd9-1d84d5d28022.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1909
 - Accessibility Insights for Windows Version: 1.1.1248.1

**Comment by DaveTryon** [comment]
Plan is to set a minimum width of 1 or 2 pixels on each side of the splitter, so that the splitter can always be retrieved with the mouse. @guybark, the splitter is already always accessible via keyboard (press tab until the splitter is highlighted, then use the arrow keys to reposition).

**Comment by guybark** [comment]
@DaveTryon - Thanks for the note on how to use the keyboard to change the width of the panes, that's really helpful! The splitter's keyboard focus feedback seems to respect colors from the active high contrast theme too. Nice!

**Comment by DaveTryon** [comment]
@guybark , please regress this using the current canary build. Thanks!
