### ISSUE TITLE
Is there support for running accessibility insights tool as part of app tests say in an Azure pipeline

### ISSUE THREAD

**Issue by ranjeshj** [Microsoft/accessibility-insights-windows#816]
**Your question here**
We can run the tool on a UWP app manually. Is there support to automate the fast pass tests in a PR or CI pipeline without having to manually launch the tool and click around ? That way we can catch violations before they are merged in.
Thanks!

**Comment by shalinijoshi19** [comment]
@adarshrema do we know if there is support to run this in ADO/CI for other platforms, esp Web + Mobile?

**Comment by adarshrema** [comment]
@shalinijoshi19, for web you can refer to samples available at [axe-pipelines-samples](https://github.com/microsoft/axe-pipelines-samples). We do not have comparable projects for mobile yet.
