### ISSUE TITLE
[BUG] AI for Windows throws an error using Text Pattern Explorer with Edge (both new and legacy)

### ISSUE THREAD

**Issue by kbabbitt** [microsoft/accessibility-insights-windows#840]
**Describe the bug**
"Failed to retrieve range(s): Object reference not set to an instance of an object." when exploring TextPattern on a text box in Chromium-based Edge or Edge Legacy.

**To Reproduce**
1. Start Accessibility Insights for Windows
2. Start Chromium-based Edge or Edge Legacy
3. Hover over the search box on the new tab page
4. In AI, click on "Text Pattern Explore..."

**Expected behavior**
Text Pattern Explorer dialog appears without errors

**Actual behavior**
Text Pattern Explorer dialog appears with "Failed to retrieve range(s): Object reference not set to an instance of an object" error.

**Desktop (please complete the following information):**
 - Windows 10 1909 (OS Build 18363.959)
 - Accessibility Insights for Windows Version: 1.1.1248.1
 - Target Application: Microsoft Edge 84.0.522.40, Microsoft Edge Legacy 44.18362.449.0

**Comment by adarshrema** [comment]
Needs investigation by the engineering team if this is an issue the Edge team needs to fix or if that has to happen at our end.

**Comment by DaveTryon** [comment]
This has been merged to master and will be in the next canary build. Will resolve once the build is released

**Comment by DaveTryon** [comment]
@kbabbitt, please regress against the latest canary release (https://github.com/microsoft/accessibility-insights-windows/releases/tag/v1.1.1307.01), then close if the fix works for you. Thanks!

**Comment by kbabbitt** [comment]
Looks good to me, thank you for the fix!
