### ISSUE TITLE
Add ability to copy test results

### ISSUE THREAD

**Issue by mrlacey** [microsoft/accessibility-insights-windows#880]
**Is your feature request related to a problem? Please describe.**
I sometimes need to write up the results of a test run in various places: Emails, notes, tickets, etc. but there's no easy way for me to get the results of a test run out of the tool.
I often end up having to type them out. :(

**Describe the solution you'd like**
It would be really good if I could just copy the results to the clipboard so I can paste them where I want them.
This could be where I can highlight the results and copy them with Ctrl+C (or a context menu)
Or you could add a button next to the results that will programmatically add them to the clipboard. A text link next to "File issue" that puts the same information in the clipboard would be great.

**Describe alternatives you've considered**
The ability to directly file an issue isn't always possible as not everything I work on has a GitHub or Azure Board. Also, I work on multiple projects and so having to regularly adjust the target domain isn't practical. Also, issues created this way overwrite the default contents of issue templates and so may not lead to issues created the way the repository wants.

**Additional context**
This is particularly an issue when the test result error message includes an invalid Unicode character. 
The following makes it hard to find the issue because I can't see the Unicode character. Being able to paste it somewhere that can display the character would have saved me a lot of time in trying to identify the character. (Bonus, telling me what the code of the character is would be nice too.)

![image](https://user-images.githubusercontent.com/189547/88405471-3c2d2900-cdc7-11ea-9d2c-4d67912f61a1.png)

**Comment by karanbirsingh** [comment]
Hi @mrlacey - thank you for filing the issue.

We do have some copy-to-clipboard behavior, but it is in a different view. One way to get there is:
- Run automated checks (as you have in the screenshot)
- Select the element you're interested in (the `text []` button)
- You should now be in the UI Automation Tree view
- Pressing Ctrl-C copies various text to the clipboard depending on where you have focus/selection. For instance, selecting an element in the tree prior to Ctrl-C will copy its properties (`A below`), and selecting Test Result(s) in the How To Fix tab will copy their descriptions (`B below`).

Here's a sample of the kind of text moved to the clipboard:
```
// A
Glimpse: button 'Ok'

Available properties
RuntimeId: [7,2FF4,AE0365]
BoundingRectangle: [l=501,t=1601,r=625,b=1663]
ProcessId: 12276
ControlType: Button(50000)
LocalizedControlType: button
Name: Ok
HasKeyboardFocus: False
IsKeyboardFocusable: True
IsEnabled: True
ClassName: Button
Culture: 0
IsControlElement: True
IsContentElement: True
IsPassword: False
NativeWindowHandle: 0
IsOffscreen: False
Orientation: None(0)
FrameworkId: WPF
IsRequiredForForm: False
IsDataValidForForm: False
ProviderDescription: [pid:12276,providerId:0x0 Main(parent link):Unidentified Provider (managed:MS.Internal.Automation.ElementProxy, PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)]
OptimizeForVisualContent: False
LiveSetting: 0
IsPeripheral: False
FillType: 0
VisualEffects: 0
HeadingLevel: HeadingLevel_None (80050)
IsDialog: False
TogglePattern.ToggleState: 2
ClickablePoint: {X=563,Y=1632}

Available patterns:
InvokePattern
TogglePattern

// B
A button must not support both the Invoke and Toggle patterns.
Modify the button to support exactly one of the following patterns:
 · Support the Invoke pattern if the button performs a command at the request of the user.
 · Support the Toggle pattern if the button can cycle through a series of up to three states.
 · Support the ExpandCollapse pattern if the button shows or hides additional content.

Focusable sibling elements must not have the same Name and LocalizedControlType.
Provide unique names for sibling controls that have the same ControlType property.
```

In other scenarios we sometimes [save results to a file](https://accessibilityinsights.io/docs/en/windows/getstarted/automatedchecks#saving-automated-check-results) to send results to others. This requires the ability to attach a file - and the recipient needs the application to view the results in their original context.

Is this similar to what you're looking for?

**Comment by mrlacey** [comment]
Oh, it's also possible to select an individual item on the Automated Checks failure list and use Ctrl+C to copy an individual item.  That's good enough for me.

BTW. Is there anything being done (or could there be) to make this more discoverable to others too?

**Comment by karanbirsingh** [comment]
Glad it's working - it's true the functionality isn't very discoverable. We will add that feedback to backlog to see what options we might have.

**Comment by adarshrema** [comment]
@mrlacey , marking this as resolved for you to confirm and close.

**Comment by mrlacey** [comment]
>  it's true the functionality isn't very discoverable. We will add that feedback to backlog to see what options we might have.

Happy to close this. But, has the discoverability issue been documented anywhere publicly that can be linked?

**Comment by adarshrema** [comment]
@mrlacey , we noticed some inconsistencies in the copy-to-clipboard behavior and have #887 to investigate this. Once we resolve that we will update documentation with details accordingly. We will plan to update this thread with details as we know more.
