### ISSUE TITLE
[BUG] UWP Flipview throws error for FeaturedItem not loaded during Entire app scan : The BoundingRectangle property must represent an area of at least 25 pixels

### ISSUE THREAD

**Issue by anand-bit-sin** [microsoft/accessibility-insights-windows#889]
Please check whether the bug has [already been filed](https://github.com/Microsoft/accessibility-insights-windows/issues).

**Describe the bug**
Flipview item in UWP which is not visible is flagged for Accessibility error

**To Reproduce**
1. Create a FlipView control in the UWP and add controls within multiple flipview items, data is bound through database from ViewModel
2. Run accessibility insights tool with the entire app setting
3. Navigate to one of the flipview items where image or media element gets loaded in next flipview
4. Image and media element throw error at some visual states, but pass on others: "The BoundingRectangle property must represent an area of at least 25 pixels". This is inconsistent.
This does not throw error if Element view is selected and verified for the displayed flipview item.

**Expected behavior**
It should consistently throw error if it finds image and media are having null bounding rectangle. It should flag error only if the current flipview item is having accessibility issue when in Entire app mode. 

**Actual behavior**
It inconsistently throw error if it finds image and media are having null bounding rectangle in different app window sizes. It flags error even if the current flipview item is not having accessibility issue when in Element mode, but flags error in Entire app mode. 

**Screenshots or .GIF**
![image](https://user-images.githubusercontent.com/13607981/89585924-583bbc00-d804-11ea-94b6-582308acc499.png)

**Desktop (please complete the following information):**
 - OS: Windos 10 1903 18362
 - Accessibility Insights for Windows Version: v1.1
 - Target Application: Custom UWP app
 - Target Application Version: NA

**Additional context**
Priority requested -

**Comment by DaveTryon** [comment]
@anand-bit-sin, can you pass along the contents of the details tab, as well? That will provide us with more information to help debug this. The ideal would be to have the entire a11ytest file, but we get the privacy concerns. Once you click on the details tab, you should be able to press Ctrl+C to copy the properties for the specific control in question. Thanks!

**Comment by anand-bit-sin** [comment]
@DaveTryon  
Here is the Details tab contents:

Group:
LocalizedControlType	group
Name	XXXXXX
ControlType	Group(50026)
IsKeyboardFocusable	False
BoundingRectangle	[l=509,t=1,r=509,b=717]
AccessKey	Property does not exist
AcceleratorKey	Property does not exist
HelpText	Property does not exist
AriaProperties	Property does not exist
AriaRole	Property does not exist

Image:
BoundingRectangle	[l=509,t=1,r=509,b=717]
Name	Property does not exist
ControlType	Image(50006)
LocalizedControlType	image
IsKeyboardFocusable	False
AccessKey	Property does not exist
AcceleratorKey	Property does not exist
HelpText	Property does not exist
AriaProperties	Property does not exist
AriaRole	Property does not exist

Media Player:
BoundingRectangle	[l=509,t=1,r=509,b=717]
Name	Property does not exist
ControlType	Custom(50025)
LocalizedControlType	media player
IsKeyboardFocusable	False
AccessKey	Property does not exist
AcceleratorKey	Property does not exist
HelpText	Property does not exist
AriaProperties	Property does not exist
AriaRole	Property does not exist

Patterns is ScrollItemPattern.

**Comment by DaveTryon** [comment]
Interesting. The BoundingRectangle is not null, but it's an empty rectangle (left and right are the same value so it's 0 pixels wide). This specific rule (BoundingRectangleSizeReasonable) skips controls with a null or malformed BoundingRectangle property, but it doesn't skip an empty rectangle. We'll discuss our options and update appropriately.

**Comment by adarshrema** [comment]
@RobGallo to update once we receive guidance from the UWP team

**Comment by RobGallo** [comment]
@anand-bit-sin , Could you share code with us which exhibits the problem? Engineers have not been able to repro the issue. Thanks!

**Comment by anand-bit-sin** [comment]
@RobGallo  The code is copyright, so cannot be shared, re-creating a sample would also take some time. Though some details about the flipview implementation is as follows: It is using a custom control, with ArrangeOverride in case a property is set to hide the element if it overlaps other UI element. In this scenario when the element overlaps with any other UI element based on max limits for other elements, the arrangeoverride creates an empty rectangle with 0 height and 0 width so that it's not visible. I think this is causing the tool to flag error for next flipview items when tried for the entire app. An ObservableCollection is being used to populate or refresh the properties of the flipview items.

**Comment by RobGallo** [comment]
@anand-bit-sin ,
It sounds like you're overriding the default behavior/implementing a custom control. Specifically it sounds like you are overriding the behavior for hiding items? Is that correct? If that's the case, you may want to set the IsOffScreen automation property for the element with a zero size rectangle to true. That will stop the error (and is correct for accessibility). However, when an item has/regains a valid bounding rectangle, you should be sure its IsOffScreen property is set to false. Otherwise, you will create an accessibility error that our tool can't catch.

**Comment by anand-bit-sin** [comment]
Thanks @RobGallo . Sorry for the delay. Yes, this is overriding the behavior to hide items. We will try to use the IsOffScreen automation property to set and reset when size is overridden.

**Comment by adarshrema** [comment]
Marking as needs author feedback while we wait for information from @anand-bit-sin per the last comment
