### ISSUE TITLE
Automatic detection of font sizes

### ISSUE THREAD

**Issue by adarshrema** [microsoft/accessibility-insights-windows#900]
Logging this on behalf of @brannonz

Something that numerous gaming teams have pinged me about in the past is how hard it is for them to determine if they have any font that fails our size guidelines (18px at 1080p).

It would be really interesting and helpful if Accessibility Insights could use OCR to detect text on a screen (or in a screenshot) and try to automatically calculate the font size based on the image resolution. We have had numerous instances of games in the industry being shipped with font that is not only not accessible for those with low vision, but that font that is so tiny even users with 20/20 vision have a hard time reading it at average sitting distances between user / monitor.

**Comment by juchampa** [comment]
This is a great idea and we'd love to see if there can be a contribution from the community for this.
