### ISSUE TITLE
[BUG] Accessibility tool show issue “Localized control type and ControlType must not both "custom" 

### ISSUE THREAD

**Issue by st8711000** [microsoft/accessibility-insights-windows#923]
[`Please`](url) check whether the bug has [already been filed](https://github.com/Microsoft/accessibility-insights-windows/issues).

**Describe the bug**
1.Accessibility tool show issue “The ControlType and LocalizedControlType must not both be set to "custom""
2.Narrator read “DataGrid.MainWindow+CleanDiskData”

**To Reproduce**
1. Download source code:
    https://drive.google.com/file/d/1qC2BVsTVWUGFI4xQtY9xVnjiBzviDkxZ/view?usp=sharing
2. Launch DataGrid.exe in DataGrid\DataGrid\bin\Debug folder
3. Run accessibility insights tool with the entire app setting(DataGrid.exe) 
4. Accessibility insights tool testing result appear error message: “The ControlType and LocalizedControlType must not both be 
    set to "custom""

**Expected behavior**
No issue appear

**Actual behavior**
Appear error message: “The ControlType and LocalizedControlType must not both be set to "custom""
![ttt](https://user-images.githubusercontent.com/14719836/92223502-208f6500-eed3-11ea-8910-d9a6db1f8473.jpg)

**Screenshots or .GIF**

**Desktop (please complete the following information):**
-OS: Windows 10 1903 18362
-Accessibility Insights for Windows Version: v1.1
-Target Application: WPF app
-Target Application Version: NA

**Additional context**
Priority requested -

**Comment by RobGallo** [comment]
This is a .Net issue. In your project you're using .Net Framework 4.5.2. If you update to 4.7.2, the problem goes away.

**Comment by st8711000** [comment]
hi 
Thanks for your help. If my project use .Net Framework 4.5.2 continuously, whether other solution to fix this issue
