### ISSUE TITLE
[General Question] Can't not detect some APPs with AccessibilityInsights tools

### ISSUE THREAD

**Issue by jamess-huang** [microsoft/accessibility-insights-windows#928]
We want to use AccessibilityInsights tool to check the APPs that we develop. However we find some APPs seem can't be detect by AccessibilityInsights tool when we hover over the element or the whole APP. This APP is not built by visual studio, it is built by BCB2009. Any information about the APP you need, please let us know, Thank you.

![Untitled](https://user-images.githubusercontent.com/29728194/92428253-2c27a800-f1c1-11ea-8717-911d44df9347.png)

**Comment by RobGallo** [comment]
@jamess-huang ,
Are you able to see any UI Automation properties of your app using the [Inspect](https://docs.microsoft.com/en-us/windows/win32/winauto/inspect-objects#:~:text=Inspect%20(Inspect.exe)%20is,as%20Microsoft%20Active%20Accessibility%20properties.) tool?

**Comment by jamess-huang** [comment]
@RobGallo 
Hello, Please check the picture below,
![Untitled](https://user-images.githubusercontent.com/29728194/92563132-a7648900-f2a9-11ea-8f98-12b9a663af80.png)

**Comment by RobGallo** [comment]
We believe the problem may be related to UI Access. Please try the instructions below, taken from https://accessibilityinsights.io/docs/en/windows/reference/faq

Sometimes Accessibility Insights for Windows can’t find my application. Is there a fix?
By default, Accessibility Insights for Windows can only scan applications that are not running as administrator. When this happens, there are 3 options:

If possible, run your application without administrative privileges.
Run Accessibility Insights for Windows as administrator (needs to be done for each session).
Enable UIAccess for Accessibility Insights for Windows (will impact all future sessions of Accessibility Insights for Windows). To do this, open an administrative command prompt and run UIAccess.cmd Enable from the directory where Accessibility Insights for Windows is installed.
Note: You will need to restart AI-Win before changes take effect.

**Comment by jamess-huang** [comment]
@RobGallo Thank you. It did because we run the APP under administrator mode. After we run Accessibility Insights with administrator, it can detect the APP successfully.
