### ISSUE TITLE
[General Question] Section 508 Compliance Coverage 

### ISSUE THREAD

**Issue by kalintodorov** [microsoft/accessibility-insights-windows#937]
Hi guys,

We have question regarding the tool for Windows - how much of the Section 508 compliance the tool covers? 
In other words if the tool shows no errors does this mean the app is Section 508 compliant?

Thanks in advance,
Kalin

**Comment by DaveTryon** [comment]
Hi, @kalintodorov! Accessibility Insights for Windows has an objective of no false positives, so the automated tests are limited to things that can reliably be automated without needing further analysis. Many of the checks in Section 508 can't be reliably automated, so while a clean result from automated checks and tab stops is a great start towards Section 508 compliance, manual assessments will still be necessary to obtain full Section 508 compliance.

You can get a sense of what portions of Section 508 are covered by downloading the rules documentation from Axe.Windows (our rules engine). The current most recent version can be found at https://github.com/microsoft/axe-windows/releases/download/v1.0.2/axe-windows-rules-1.0.2.md. 

It's also possible to view passed and uncertain results from automated checks:
1. Run automated checks, as usual
2. Click on "View Results in the UI Automation tree"
3. Walk through each element in the UI Automation tree
4. In the "How to fix" tab, you'll see a button labeled "Passed and Uncertain tests". Clicking this will show all of the tests that were run and their corresponding result. 

This workflow is really optimized for inspecting a specific control, and we don't currently have an option to expose all results by default.

**Comment by kalintodorov** [comment]
Thank you for the information! :)
