### ISSUE TITLE
Invoke ShowContextMenu on Nodes

### ISSUE THREAD

**Issue by jesmores** [microsoft/accessibility-insights-windows#946]
**Is your feature request related to a problem? Please describe.**
[Narrator Touch](https://support.microsoft.com/en-us/help/22812/windows-10-using-narrator-with-touch#:~:text=To%20show%20context%20menus%2C%20double-tap%20with%20two%20fingers.,Narrator%20command%20list%2C%20triple%20tap%20with%20four%20fingers.) has a way to invoke a context menu on the currently focused element by double-tapping with two fingers. It sounds like the underlying API to do this is [IUIAutomationElement3::ShowContextMenu](https://docs.microsoft.com/en-us/windows/win32/api/uiautomationclient/nf-uiautomationclient-iuiautomationelement3-showcontextmenu).

I don't see a way to simulate this gesture via Accessibility Insights. Not every development environment has touch capabilities, and with work becoming increasingly remote, it's harder to get to the office to borrow a touch device to validate this feature, so it's hard to validate changes that add or otherwise modify the behavior that responds to this gesture.

**Describe the solution you'd like**
Similar to how Accessibility Insights lets us trigger and simulate the various patterns exposed on a UIA node (such as Invoke or Expand) it would be nice to have a way to trigger the context menu touch gesture as well.

**Describe alternatives you've considered**
I have not tried any alternatives.

**Additional context**
Please let me know if Acc Insights already has this capability, and teach me where to access it.

**Comment by adarshrema** [comment]
Thanks for the feature request, @jesmores! This is currently not supported and we agree that this would be an interesting feature. This will also need some additional work to determine where it would fit in with the current user experience. We are leaving this feature as needs investigation to allow the community to up-vote if this is something they would like to have in Accessibility Insights for Windows.

**Comment by jesmores** [comment]
Thanks for taking a look. Do you know of any alternative ways to simulate the touch gesture in the absence of a touch device?

**Comment by adarshrema** [comment]
@guybark, would you know?

**Comment by RobGallo** [comment]
This issue has a confusing comment history; so I am trying to reset. I believe we need PM and design to tell us how we should implement the UX for invoking the context menu. Invoking the context menu itself should be too much work from an engineering perspective, on top of implementing the UX.

**Comment by DaveTryon** [comment]
Unfortunately, this is out of scope given our current priorities.

Thanks for using Accessibility Insights!
