### ISSUE TITLE
[BUG] Mouse tracking doesn't respect the tree view mode

### ISSUE THREAD

**Issue by DaveTryon** [microsoft/accessibility-insights-windows#974]
**Describe the bug**
Mouse tracking currently ignores the tree view mode. As a result, it's possible for elements to be "discovered" via the mouse that could never be discovered with just the keyboard, and it's possible to cause very confusing scan results.

**To Reproduce**
1. Expand and build the following UWP project: [PlaceholderTest.zip](https://github.com/microsoft/accessibility-insights-windows/files/5405087/PlaceholderTest.zip)
2. Run AIWin
3. Start the UWP test app
4. Using the mouse, hover over the edit control and inspect the text element named "This is the placeholder". Here's a sample screen
![image](https://user-images.githubusercontent.com/45672944/96517410-b2ea8e80-121d-11eb-86ea-19de8c3a97f1.png)

**Expected behavior**
Notice that this element is neither a ContentElement nor a ControlElement, so it should only appear in Raw tree view mode.

**Actual behavior**
Since it shows up here, there are multiple odd things that can happen. If you run the tests from this element, it will be reported as a failure, but won't be visible by default when you try to view it in the UIA tree. It will only be visible if you go into Raw tree view mode.

**Desktop (please complete the following information):**
 - OS: Windows 10 .2004
 - Accessibility Insights for Windows Version: 1.1.1387.1

**Additional context**
We need to think about how to message this, since some people may be expecting the old (broken) behavior and think it's a bug when it changes.

**Comment by adarshrema** [comment]
Fix the issue by updating mouse tracking to respect ra/ content/ control mode specified in settings.

**Comment by DaveTryon** [comment]
Reopening for proper validation

**Comment by DaveTryon** [comment]
Validated in build 1.1.1396.1
