### ISSUE TITLE
[General Question] What is "Element path Issue Rule source"

### ISSUE THREAD

**Issue by chingucoding** [microsoft/accessibility-insights-windows#980]
In the following screenshot, what does "Element path Issue Rule source" refer to?

![image](https://user-images.githubusercontent.com/16122379/97239553-2e36dc00-17ec-11eb-8fbc-b682ae27da26.png)

Do those refer to the columns of the failed rule below? In that case, I think it's a bit confusing to have it seem like a separate issue/error.

This came up in https://github.com/microsoft/microsoft-ui-xaml/issues/3481

**Comment by lamaks** [comment]
You will need to select the link `View results in the UI Automation tree` on the right to see element path of the target window scanned. The `How to fix` left panel will have the rule source and fix details if any.

![image](https://user-images.githubusercontent.com/40576301/97241608-da59d200-17ae-11eb-9447-775e7d2ba093.png)

**Comment by chingucoding** [comment]
Oh I see. Does it then even make sense too have that row in the automated checks list if it does not convey much meaning?

**Comment by DaveTryon** [comment]
@chingucoding, the row represents the headers of the columns in the table. This gets a bit clearer when seen in the context of the full list:

![image](https://user-images.githubusercontent.com/45672944/97760722-0a5fe880-1ac1-11eb-8821-a8028c257e03.png)

The grouping, the redundant info, and the fact that the groups are non-expanded at first, all combine to make it a little less obvious that this a header row. To be honest, we may be trying to convey too much information in this table, but it's information that current users have requested that we expose at this level for a variety of reasons. At some point in time, we may move from a tabular format to a format more like what we use to report automated check failures in Accessibility Insights for Web, but we haven't yet committed to that path.

In the meanwhile, thanks for your question! Please close this issue out if you feel that your question has been answered to your satisfaction.

**Comment by chingucoding** [comment]
Alright, thanks. That answers my question, thank you!
